using System.ComponentModel;
using System.Numerics;
using TaleWorlds.CampaignSystem.ViewModelCollection.ArmyManagement;
using TaleWorlds.Core;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.Library;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets.GatherArmy;

namespace SandBox.GauntletUI.AutoGenerated0;

public class ArmyManagement__TaleWorlds_CampaignSystem_ViewModelCollection_ArmyManagement_ArmyManagementVM_Dependency_5_GatherArmyTuple__InheritedPrefab : GatherArmyTupleButtonWidget
{
	private GatherArmyTupleButtonWidget _widget;

	private ListPanel _widget_0;

	private Widget _widget_0_0;

	private ImageIdentifierWidget _widget_0_0_0;

	private BrushWidget _widget_0_0_1;

	private RichTextWidget _widget_0_1;

	private Widget _widget_0_2;

	private MaskedTextureWidget _widget_0_2_0;

	private TextWidget _widget_0_3;

	private Widget _widget_0_4;

	private ListPanel _widget_0_4_0;

	private TextWidget _widget_0_4_0_0;

	private Widget _widget_0_4_0_1;

	private TextWidget _widget_0_5;

	private ArmyManagementItemVM _datasource_Root;

	private ImageIdentifierVM _datasource_Root_LordFace;

	private ImageIdentifierVM _datasource_Root_ClanBanner;

	public ArmyManagement__TaleWorlds_CampaignSystem_ViewModelCollection_ArmyManagement_ArmyManagementVM_Dependency_5_GatherArmyTuple__InheritedPrefab(UIContext context)
		: base(context)
	{
	}

	public virtual void CreateWidgets()
	{
		_widget = this;
		_widget_0 = new ListPanel(base.Context);
		_widget.AddChild(_widget_0);
		_widget_0_0 = new Widget(base.Context);
		_widget_0.AddChild(_widget_0_0);
		_widget_0_0_0 = new ImageIdentifierWidget(base.Context);
		_widget_0_0.AddChild(_widget_0_0_0);
		_widget_0_0_1 = new BrushWidget(base.Context);
		_widget_0_0.AddChild(_widget_0_0_1);
		_widget_0_1 = new RichTextWidget(base.Context);
		_widget_0.AddChild(_widget_0_1);
		_widget_0_2 = new Widget(base.Context);
		_widget_0.AddChild(_widget_0_2);
		_widget_0_2_0 = new MaskedTextureWidget(base.Context);
		_widget_0_2.AddChild(_widget_0_2_0);
		_widget_0_3 = new TextWidget(base.Context);
		_widget_0.AddChild(_widget_0_3);
		_widget_0_4 = new Widget(base.Context);
		_widget_0.AddChild(_widget_0_4);
		_widget_0_4_0 = new ListPanel(base.Context);
		_widget_0_4.AddChild(_widget_0_4_0);
		_widget_0_4_0_0 = new TextWidget(base.Context);
		_widget_0_4_0.AddChild(_widget_0_4_0_0);
		_widget_0_4_0_1 = new Widget(base.Context);
		_widget_0_4_0.AddChild(_widget_0_4_0_1);
		_widget_0_5 = new TextWidget(base.Context);
		_widget_0.AddChild(_widget_0_5);
	}

	public virtual void SetIds()
	{
	}

	public virtual void SetAttributes()
	{
		base.DoNotPassEventsToChildren = true;
		base.WidthSizePolicy = SizePolicy.Fixed;
		base.HeightSizePolicy = SizePolicy.Fixed;
		base.SuggestedWidth = 605f;
		base.SuggestedHeight = 88f;
		base.Brush = base.Context.GetBrush("ArmyManagement.Army.Tuple");
		base.HoveredCursorState = "RightClickLink";
		base.OverrideDefaultStateSwitchingEnabled = true;
		base.UpdateChildrenStates = true;
		_widget_0.WidthSizePolicy = SizePolicy.StretchToParent;
		_widget_0.HeightSizePolicy = SizePolicy.StretchToParent;
		_widget_0.UpdateChildrenStates = true;
		_widget_0_0.WidthSizePolicy = SizePolicy.Fixed;
		_widget_0_0.HeightSizePolicy = SizePolicy.Fixed;
		_widget_0_0.SuggestedWidth = 112f;
		_widget_0_0.SuggestedHeight = 81f;
		_widget_0_0.VerticalAlignment = VerticalAlignment.Center;
		_widget_0_0.MarginLeft = 13f;
		_widget_0_0.UpdateChildrenStates = true;
		_widget_0_0_0.WidthSizePolicy = SizePolicy.StretchToParent;
		_widget_0_0_0.HeightSizePolicy = SizePolicy.StretchToParent;
		_widget_0_0_0.MarginLeft = 6f;
		_widget_0_0_0.MarginRight = 6f;
		_widget_0_0_0.MarginTop = 4f;
		_widget_0_0_0.MarginBottom = 3f;
		_widget_0_0_1.WidthSizePolicy = SizePolicy.Fixed;
		_widget_0_0_1.HeightSizePolicy = SizePolicy.Fixed;
		_widget_0_0_1.SuggestedWidth = 26f;
		_widget_0_0_1.SuggestedHeight = 26f;
		_widget_0_0_1.Brush = base.Context.GetBrush("ArmyManagement.CheckmarkStatus");
		_widget_0_0_1.VerticalAlignment = VerticalAlignment.Center;
		_widget_0_0_1.PositionXOffset = 6f;
		_widget_0_1.WidthSizePolicy = SizePolicy.Fixed;
		_widget_0_1.HeightSizePolicy = SizePolicy.StretchToParent;
		_widget_0_1.SuggestedWidth = 155f;
		_widget_0_1.MarginLeft = 10f;
		_widget_0_1.Brush = base.Context.GetBrush("ArmyManagement.Army.Tuple.Name");
		_widget_0_2.WidthSizePolicy = SizePolicy.Fixed;
		_widget_0_2.HeightSizePolicy = SizePolicy.StretchToParent;
		_widget_0_2.SuggestedWidth = 75f;
		_widget_0_2.VerticalAlignment = VerticalAlignment.Center;
		_widget_0_2_0.WidthSizePolicy = SizePolicy.Fixed;
		_widget_0_2_0.HeightSizePolicy = SizePolicy.Fixed;
		_widget_0_2_0.SuggestedWidth = 58.48f;
		_widget_0_2_0.SuggestedHeight = 74.39f;
		_widget_0_2_0.HorizontalAlignment = HorizontalAlignment.Left;
		_widget_0_2_0.VerticalAlignment = VerticalAlignment.Top;
		_widget_0_2_0.MarginLeft = 9f;
		_widget_0_2_0.PositionYOffset = 1f;
		_widget_0_2_0.Brush = base.Context.GetBrush("Flat.Tuple.Banner.Small");
		_widget_0_2_0.IsDisabled = true;
		_widget_0_3.WidthSizePolicy = SizePolicy.Fixed;
		_widget_0_3.HeightSizePolicy = SizePolicy.StretchToParent;
		_widget_0_3.SuggestedWidth = 80f;
		_widget_0_3.MarginLeft = 5f;
		_widget_0_3.Brush = base.Context.GetBrush("ArmyManagement.Army.Tuple.Value");
		_widget_0_4.WidthSizePolicy = SizePolicy.Fixed;
		_widget_0_4.HeightSizePolicy = SizePolicy.StretchToParent;
		_widget_0_4.SuggestedWidth = 70f;
		_widget_0_4.ClipContents = true;
		_widget_0_4_0.WidthSizePolicy = SizePolicy.CoverChildren;
		_widget_0_4_0.HeightSizePolicy = SizePolicy.CoverChildren;
		_widget_0_4_0.HorizontalAlignment = HorizontalAlignment.Center;
		_widget_0_4_0.VerticalAlignment = VerticalAlignment.Center;
		_widget_0_4_0_0.WidthSizePolicy = SizePolicy.CoverChildren;
		_widget_0_4_0_0.HeightSizePolicy = SizePolicy.CoverChildren;
		_widget_0_4_0_0.Brush = base.Context.GetBrush("ArmyManagement.Army.Tuple.Value");
		_widget_0_4_0_0.MarginTop = 5f;
		_widget_0_4_0_1.WidthSizePolicy = SizePolicy.Fixed;
		_widget_0_4_0_1.HeightSizePolicy = SizePolicy.Fixed;
		_widget_0_4_0_1.SuggestedWidth = 17f;
		_widget_0_4_0_1.SuggestedHeight = 27f;
		_widget_0_4_0_1.VerticalAlignment = VerticalAlignment.Center;
		_widget_0_4_0_1.Sprite = base.Context.SpriteData.GetSprite("SPKingdom\\influence_icon_small");
		_widget_0_5.WidthSizePolicy = SizePolicy.Fixed;
		_widget_0_5.HeightSizePolicy = SizePolicy.StretchToParent;
		_widget_0_5.SuggestedWidth = 70f;
		_widget_0_5.MarginLeft = 5f;
		_widget_0_5.Brush = base.Context.GetBrush("ArmyManagement.Army.Tuple.Value");
	}

	public virtual void DestroyDataSource()
	{
		if (_datasource_Root != null)
		{
			_datasource_Root.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
			_widget.EventFire -= EventListenerOf_widget;
			_widget.PropertyChanged -= PropertyChangedListenerOf_widget;
			_widget.boolPropertyChanged -= boolPropertyChangedListenerOf_widget;
			_widget.floatPropertyChanged -= floatPropertyChangedListenerOf_widget;
			_widget.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget;
			_widget.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget;
			_widget.doublePropertyChanged -= doublePropertyChangedListenerOf_widget;
			_widget.intPropertyChanged -= intPropertyChangedListenerOf_widget;
			_widget.uintPropertyChanged -= uintPropertyChangedListenerOf_widget;
			_widget.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget;
			_widget_0_1.PropertyChanged -= PropertyChangedListenerOf_widget_0_1;
			_widget_0_1.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_1;
			_widget_0_1.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_1;
			_widget_0_1.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_1;
			_widget_0_1.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_1;
			_widget_0_1.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_1;
			_widget_0_1.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_1;
			_widget_0_1.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_1;
			_widget_0_1.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_1;
			_widget_0_3.PropertyChanged -= PropertyChangedListenerOf_widget_0_3;
			_widget_0_3.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_3;
			_widget_0_3.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_3;
			_widget_0_3.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_3;
			_widget_0_3.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_3;
			_widget_0_3.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_3;
			_widget_0_3.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_3;
			_widget_0_3.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_3;
			_widget_0_3.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_3;
			_widget_0_4_0_0.PropertyChanged -= PropertyChangedListenerOf_widget_0_4_0_0;
			_widget_0_4_0_0.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_4_0_0;
			_widget_0_4_0_0.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_4_0_0;
			_widget_0_4_0_0.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_4_0_0;
			_widget_0_4_0_0.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_4_0_0;
			_widget_0_4_0_0.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_4_0_0;
			_widget_0_4_0_0.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_4_0_0;
			_widget_0_4_0_0.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_4_0_0;
			_widget_0_4_0_0.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_4_0_0;
			_widget_0_5.PropertyChanged -= PropertyChangedListenerOf_widget_0_5;
			_widget_0_5.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_5;
			_widget_0_5.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_5;
			_widget_0_5.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_5;
			_widget_0_5.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_5;
			_widget_0_5.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_5;
			_widget_0_5.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_5;
			_widget_0_5.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_5;
			_widget_0_5.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_5;
			if (_datasource_Root_LordFace != null)
			{
				_datasource_Root_LordFace.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_LordFace;
				_datasource_Root_LordFace.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_LordFace;
				_datasource_Root_LordFace.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_LordFace;
				_datasource_Root_LordFace.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_LordFace;
				_datasource_Root_LordFace.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_LordFace;
				_datasource_Root_LordFace.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_LordFace;
				_datasource_Root_LordFace.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_LordFace;
				_datasource_Root_LordFace.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_LordFace;
				_datasource_Root_LordFace.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_LordFace;
				_widget_0_0_0.PropertyChanged -= PropertyChangedListenerOf_widget_0_0_0;
				_widget_0_0_0.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_0_0;
				_widget_0_0_0.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_0_0;
				_widget_0_0_0.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_0_0;
				_widget_0_0_0.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_0_0;
				_widget_0_0_0.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_0_0;
				_widget_0_0_0.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_0_0;
				_widget_0_0_0.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_0_0;
				_widget_0_0_0.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_0_0;
				_datasource_Root_LordFace = null;
			}
			if (_datasource_Root_ClanBanner != null)
			{
				_datasource_Root_ClanBanner.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_ClanBanner;
				_datasource_Root_ClanBanner.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_ClanBanner;
				_datasource_Root_ClanBanner.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_ClanBanner;
				_datasource_Root_ClanBanner.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_ClanBanner;
				_datasource_Root_ClanBanner.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_ClanBanner;
				_datasource_Root_ClanBanner.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_ClanBanner;
				_datasource_Root_ClanBanner.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_ClanBanner;
				_datasource_Root_ClanBanner.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_ClanBanner;
				_datasource_Root_ClanBanner.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_ClanBanner;
				_widget_0_2_0.PropertyChanged -= PropertyChangedListenerOf_widget_0_2_0;
				_widget_0_2_0.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_2_0;
				_widget_0_2_0.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_2_0;
				_widget_0_2_0.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_2_0;
				_widget_0_2_0.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_2_0;
				_widget_0_2_0.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_2_0;
				_widget_0_2_0.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_2_0;
				_widget_0_2_0.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_2_0;
				_widget_0_2_0.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_2_0;
				_datasource_Root_ClanBanner = null;
			}
			_datasource_Root = null;
		}
	}

	public virtual void SetDataSource(ArmyManagementItemVM dataSource)
	{
		RefreshDataSource_datasource_Root(dataSource);
	}

	private void EventListenerOf_widget(Widget widget, string commandName, object[] args)
	{
		if (commandName == "Click")
		{
			_datasource_Root.ExecuteAction();
		}
		if (commandName == "AlternateClick")
		{
			_datasource_Root.ExecuteOpenEncyclopedia();
		}
		if (commandName == "HoverBegin")
		{
			_datasource_Root.ExecuteBeginHint();
		}
		if (commandName == "HoverEnd")
		{
			_datasource_Root.ExecuteEndHint();
		}
	}

	private void PropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void intPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget(string propertyName)
	{
		switch (propertyName)
		{
		case "IsEligible":
			_datasource_Root.IsEligible = _widget.IsEligible;
			break;
		case "IsInCart":
			_datasource_Root.IsInCart = _widget.IsInCart;
			break;
		case "IsTransferDisabled":
			_datasource_Root.IsTransferDisabled = _widget.IsTransferDisabled;
			break;
		}
	}

	private void PropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_0_1(string propertyName)
	{
		if (propertyName == "Text")
		{
			_datasource_Root.NameText = _widget_0_1.Text;
		}
	}

	private void PropertyChangedListenerOf_widget_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_0_3(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_0_3(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_0_3(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_3(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_3(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_0_3(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_0_3(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_0_3(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_0_3(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_0_3(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_0_3(string propertyName)
	{
		if (propertyName == "IntText")
		{
			_datasource_Root.Strength = _widget_0_3.IntText;
		}
	}

	private void PropertyChangedListenerOf_widget_0_4_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_0_4_0_0(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_0_4_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_0_4_0_0(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_0_4_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_0_4_0_0(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_0_4_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_4_0_0(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_0_4_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_4_0_0(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_0_4_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_0_4_0_0(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_0_4_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_0_4_0_0(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_0_4_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_0_4_0_0(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_0_4_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_0_4_0_0(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_0_4_0_0(string propertyName)
	{
		if (propertyName == "IntText")
		{
			_datasource_Root.Cost = _widget_0_4_0_0.IntText;
		}
	}

	private void PropertyChangedListenerOf_widget_0_5(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_0_5(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_0_5(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_0_5(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_0_5(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_0_5(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_0_5(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_5(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_0_5(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_5(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_0_5(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_0_5(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_0_5(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_0_5(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_0_5(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_0_5(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_0_5(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_0_5(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_0_5(string propertyName)
	{
		if (propertyName == "Text")
		{
			_datasource_Root.DistanceText = _widget_0_5.Text;
		}
	}

	private void PropertyChangedListenerOf_widget_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_0_0_0(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_0_0_0(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_0_0_0(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_0_0(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_0_0(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_0_0_0(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_0_0_0(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_0_0_0(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_0_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_0_0_0(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_0_0_0(string propertyName)
	{
		if (!(propertyName == "AdditionalArgs") && !(propertyName == "ImageId"))
		{
			_ = propertyName == "ImageTypeCode";
		}
	}

	private void PropertyChangedListenerOf_widget_0_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_0_2_0(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_0_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_0_2_0(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_0_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_0_2_0(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_0_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_2_0(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_0_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_2_0(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_0_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_0_2_0(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_0_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_0_2_0(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_0_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_0_2_0(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_0_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_0_2_0(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_0_2_0(string propertyName)
	{
		if (!(propertyName == "AdditionalArgs") && !(propertyName == "ImageId"))
		{
			_ = propertyName == "ImageTypeCode";
		}
	}

	private void ViewModelPropertyChangedListenerOf_datasource_Root(object sender, PropertyChangedEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root(object sender, PropertyChangedWithValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root(object sender, PropertyChangedWithBoolValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root(object sender, PropertyChangedWithFloatValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithUIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root(object sender, PropertyChangedWithColorValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root(object sender, PropertyChangedWithDoubleValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root(object sender, PropertyChangedWithVec2ValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void HandleViewModelPropertyChangeOf_datasource_Root(string propertyName)
	{
		switch (propertyName)
		{
		case "LordFace":
			RefreshDataSource_datasource_Root_LordFace(_datasource_Root.LordFace);
			break;
		case "ClanBanner":
			RefreshDataSource_datasource_Root_ClanBanner(_datasource_Root.ClanBanner);
			break;
		case "IsEligible":
			_widget.IsEligible = _datasource_Root.IsEligible;
			break;
		case "IsInCart":
			_widget.IsInCart = _datasource_Root.IsInCart;
			break;
		case "IsTransferDisabled":
			_widget.IsTransferDisabled = _datasource_Root.IsTransferDisabled;
			break;
		case "NameText":
			_widget_0_1.Text = _datasource_Root.NameText;
			break;
		case "Strength":
			_widget_0_3.IntText = _datasource_Root.Strength;
			break;
		case "Cost":
			_widget_0_4_0_0.IntText = _datasource_Root.Cost;
			break;
		case "DistanceText":
			_widget_0_5.Text = _datasource_Root.DistanceText;
			break;
		}
	}

	private void ViewModelPropertyChangedListenerOf_datasource_Root_LordFace(object sender, PropertyChangedEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_LordFace(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root_LordFace(object sender, PropertyChangedWithValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_LordFace(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_LordFace(object sender, PropertyChangedWithBoolValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_LordFace(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_LordFace(object sender, PropertyChangedWithIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_LordFace(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_LordFace(object sender, PropertyChangedWithFloatValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_LordFace(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_LordFace(object sender, PropertyChangedWithUIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_LordFace(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_LordFace(object sender, PropertyChangedWithColorValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_LordFace(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_LordFace(object sender, PropertyChangedWithDoubleValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_LordFace(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_LordFace(object sender, PropertyChangedWithVec2ValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_LordFace(e.PropertyName);
	}

	private void HandleViewModelPropertyChangeOf_datasource_Root_LordFace(string propertyName)
	{
		switch (propertyName)
		{
		case "AdditionalArgs":
			_widget_0_0_0.AdditionalArgs = _datasource_Root_LordFace.AdditionalArgs;
			break;
		case "Id":
			_widget_0_0_0.ImageId = _datasource_Root_LordFace.Id;
			break;
		case "ImageTypeCode":
			_widget_0_0_0.ImageTypeCode = _datasource_Root_LordFace.ImageTypeCode;
			break;
		}
	}

	private void ViewModelPropertyChangedListenerOf_datasource_Root_ClanBanner(object sender, PropertyChangedEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_ClanBanner(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root_ClanBanner(object sender, PropertyChangedWithValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_ClanBanner(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_ClanBanner(object sender, PropertyChangedWithBoolValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_ClanBanner(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_ClanBanner(object sender, PropertyChangedWithIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_ClanBanner(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_ClanBanner(object sender, PropertyChangedWithFloatValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_ClanBanner(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_ClanBanner(object sender, PropertyChangedWithUIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_ClanBanner(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_ClanBanner(object sender, PropertyChangedWithColorValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_ClanBanner(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_ClanBanner(object sender, PropertyChangedWithDoubleValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_ClanBanner(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_ClanBanner(object sender, PropertyChangedWithVec2ValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_ClanBanner(e.PropertyName);
	}

	private void HandleViewModelPropertyChangeOf_datasource_Root_ClanBanner(string propertyName)
	{
		switch (propertyName)
		{
		case "AdditionalArgs":
			_widget_0_2_0.AdditionalArgs = _datasource_Root_ClanBanner.AdditionalArgs;
			break;
		case "Id":
			_widget_0_2_0.ImageId = _datasource_Root_ClanBanner.Id;
			break;
		case "ImageTypeCode":
			_widget_0_2_0.ImageTypeCode = _datasource_Root_ClanBanner.ImageTypeCode;
			break;
		}
	}

	private void RefreshDataSource_datasource_Root(ArmyManagementItemVM newDataSource)
	{
		if (_datasource_Root != null)
		{
			_datasource_Root.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
			_widget.EventFire -= EventListenerOf_widget;
			_widget.PropertyChanged -= PropertyChangedListenerOf_widget;
			_widget.boolPropertyChanged -= boolPropertyChangedListenerOf_widget;
			_widget.floatPropertyChanged -= floatPropertyChangedListenerOf_widget;
			_widget.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget;
			_widget.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget;
			_widget.doublePropertyChanged -= doublePropertyChangedListenerOf_widget;
			_widget.intPropertyChanged -= intPropertyChangedListenerOf_widget;
			_widget.uintPropertyChanged -= uintPropertyChangedListenerOf_widget;
			_widget.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget;
			_widget_0_1.PropertyChanged -= PropertyChangedListenerOf_widget_0_1;
			_widget_0_1.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_1;
			_widget_0_1.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_1;
			_widget_0_1.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_1;
			_widget_0_1.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_1;
			_widget_0_1.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_1;
			_widget_0_1.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_1;
			_widget_0_1.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_1;
			_widget_0_1.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_1;
			_widget_0_3.PropertyChanged -= PropertyChangedListenerOf_widget_0_3;
			_widget_0_3.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_3;
			_widget_0_3.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_3;
			_widget_0_3.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_3;
			_widget_0_3.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_3;
			_widget_0_3.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_3;
			_widget_0_3.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_3;
			_widget_0_3.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_3;
			_widget_0_3.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_3;
			_widget_0_4_0_0.PropertyChanged -= PropertyChangedListenerOf_widget_0_4_0_0;
			_widget_0_4_0_0.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_4_0_0;
			_widget_0_4_0_0.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_4_0_0;
			_widget_0_4_0_0.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_4_0_0;
			_widget_0_4_0_0.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_4_0_0;
			_widget_0_4_0_0.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_4_0_0;
			_widget_0_4_0_0.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_4_0_0;
			_widget_0_4_0_0.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_4_0_0;
			_widget_0_4_0_0.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_4_0_0;
			_widget_0_5.PropertyChanged -= PropertyChangedListenerOf_widget_0_5;
			_widget_0_5.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_5;
			_widget_0_5.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_5;
			_widget_0_5.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_5;
			_widget_0_5.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_5;
			_widget_0_5.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_5;
			_widget_0_5.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_5;
			_widget_0_5.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_5;
			_widget_0_5.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_5;
			if (_datasource_Root_LordFace != null)
			{
				_datasource_Root_LordFace.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_LordFace;
				_datasource_Root_LordFace.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_LordFace;
				_datasource_Root_LordFace.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_LordFace;
				_datasource_Root_LordFace.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_LordFace;
				_datasource_Root_LordFace.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_LordFace;
				_datasource_Root_LordFace.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_LordFace;
				_datasource_Root_LordFace.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_LordFace;
				_datasource_Root_LordFace.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_LordFace;
				_datasource_Root_LordFace.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_LordFace;
				_widget_0_0_0.PropertyChanged -= PropertyChangedListenerOf_widget_0_0_0;
				_widget_0_0_0.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_0_0;
				_widget_0_0_0.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_0_0;
				_widget_0_0_0.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_0_0;
				_widget_0_0_0.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_0_0;
				_widget_0_0_0.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_0_0;
				_widget_0_0_0.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_0_0;
				_widget_0_0_0.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_0_0;
				_widget_0_0_0.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_0_0;
				_datasource_Root_LordFace = null;
			}
			if (_datasource_Root_ClanBanner != null)
			{
				_datasource_Root_ClanBanner.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_ClanBanner;
				_datasource_Root_ClanBanner.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_ClanBanner;
				_datasource_Root_ClanBanner.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_ClanBanner;
				_datasource_Root_ClanBanner.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_ClanBanner;
				_datasource_Root_ClanBanner.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_ClanBanner;
				_datasource_Root_ClanBanner.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_ClanBanner;
				_datasource_Root_ClanBanner.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_ClanBanner;
				_datasource_Root_ClanBanner.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_ClanBanner;
				_datasource_Root_ClanBanner.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_ClanBanner;
				_widget_0_2_0.PropertyChanged -= PropertyChangedListenerOf_widget_0_2_0;
				_widget_0_2_0.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_2_0;
				_widget_0_2_0.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_2_0;
				_widget_0_2_0.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_2_0;
				_widget_0_2_0.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_2_0;
				_widget_0_2_0.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_2_0;
				_widget_0_2_0.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_2_0;
				_widget_0_2_0.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_2_0;
				_widget_0_2_0.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_2_0;
				_datasource_Root_ClanBanner = null;
			}
			_datasource_Root = null;
		}
		_datasource_Root = newDataSource;
		if (_datasource_Root != null)
		{
			_datasource_Root.PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithValue += ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithBoolValue += ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithIntValue += ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithFloatValue += ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithUIntValue += ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithColorValue += ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithDoubleValue += ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithVec2Value += ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
			_widget.IsEligible = _datasource_Root.IsEligible;
			_widget.IsInCart = _datasource_Root.IsInCart;
			_widget.IsTransferDisabled = _datasource_Root.IsTransferDisabled;
			_widget.EventFire += EventListenerOf_widget;
			_widget.PropertyChanged += PropertyChangedListenerOf_widget;
			_widget.boolPropertyChanged += boolPropertyChangedListenerOf_widget;
			_widget.floatPropertyChanged += floatPropertyChangedListenerOf_widget;
			_widget.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget;
			_widget.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget;
			_widget.doublePropertyChanged += doublePropertyChangedListenerOf_widget;
			_widget.intPropertyChanged += intPropertyChangedListenerOf_widget;
			_widget.uintPropertyChanged += uintPropertyChangedListenerOf_widget;
			_widget.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget;
			_widget_0_1.Text = _datasource_Root.NameText;
			_widget_0_1.PropertyChanged += PropertyChangedListenerOf_widget_0_1;
			_widget_0_1.boolPropertyChanged += boolPropertyChangedListenerOf_widget_0_1;
			_widget_0_1.floatPropertyChanged += floatPropertyChangedListenerOf_widget_0_1;
			_widget_0_1.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_0_1;
			_widget_0_1.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_0_1;
			_widget_0_1.doublePropertyChanged += doublePropertyChangedListenerOf_widget_0_1;
			_widget_0_1.intPropertyChanged += intPropertyChangedListenerOf_widget_0_1;
			_widget_0_1.uintPropertyChanged += uintPropertyChangedListenerOf_widget_0_1;
			_widget_0_1.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_0_1;
			_widget_0_3.IntText = _datasource_Root.Strength;
			_widget_0_3.PropertyChanged += PropertyChangedListenerOf_widget_0_3;
			_widget_0_3.boolPropertyChanged += boolPropertyChangedListenerOf_widget_0_3;
			_widget_0_3.floatPropertyChanged += floatPropertyChangedListenerOf_widget_0_3;
			_widget_0_3.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_0_3;
			_widget_0_3.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_0_3;
			_widget_0_3.doublePropertyChanged += doublePropertyChangedListenerOf_widget_0_3;
			_widget_0_3.intPropertyChanged += intPropertyChangedListenerOf_widget_0_3;
			_widget_0_3.uintPropertyChanged += uintPropertyChangedListenerOf_widget_0_3;
			_widget_0_3.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_0_3;
			_widget_0_4_0_0.IntText = _datasource_Root.Cost;
			_widget_0_4_0_0.PropertyChanged += PropertyChangedListenerOf_widget_0_4_0_0;
			_widget_0_4_0_0.boolPropertyChanged += boolPropertyChangedListenerOf_widget_0_4_0_0;
			_widget_0_4_0_0.floatPropertyChanged += floatPropertyChangedListenerOf_widget_0_4_0_0;
			_widget_0_4_0_0.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_0_4_0_0;
			_widget_0_4_0_0.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_0_4_0_0;
			_widget_0_4_0_0.doublePropertyChanged += doublePropertyChangedListenerOf_widget_0_4_0_0;
			_widget_0_4_0_0.intPropertyChanged += intPropertyChangedListenerOf_widget_0_4_0_0;
			_widget_0_4_0_0.uintPropertyChanged += uintPropertyChangedListenerOf_widget_0_4_0_0;
			_widget_0_4_0_0.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_0_4_0_0;
			_widget_0_5.Text = _datasource_Root.DistanceText;
			_widget_0_5.PropertyChanged += PropertyChangedListenerOf_widget_0_5;
			_widget_0_5.boolPropertyChanged += boolPropertyChangedListenerOf_widget_0_5;
			_widget_0_5.floatPropertyChanged += floatPropertyChangedListenerOf_widget_0_5;
			_widget_0_5.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_0_5;
			_widget_0_5.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_0_5;
			_widget_0_5.doublePropertyChanged += doublePropertyChangedListenerOf_widget_0_5;
			_widget_0_5.intPropertyChanged += intPropertyChangedListenerOf_widget_0_5;
			_widget_0_5.uintPropertyChanged += uintPropertyChangedListenerOf_widget_0_5;
			_widget_0_5.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_0_5;
			_datasource_Root_LordFace = _datasource_Root.LordFace;
			if (_datasource_Root_LordFace != null)
			{
				_datasource_Root_LordFace.PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root_LordFace;
				_datasource_Root_LordFace.PropertyChangedWithValue += ViewModelPropertyChangedWithValueListenerOf_datasource_Root_LordFace;
				_datasource_Root_LordFace.PropertyChangedWithBoolValue += ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_LordFace;
				_datasource_Root_LordFace.PropertyChangedWithIntValue += ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_LordFace;
				_datasource_Root_LordFace.PropertyChangedWithFloatValue += ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_LordFace;
				_datasource_Root_LordFace.PropertyChangedWithUIntValue += ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_LordFace;
				_datasource_Root_LordFace.PropertyChangedWithColorValue += ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_LordFace;
				_datasource_Root_LordFace.PropertyChangedWithDoubleValue += ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_LordFace;
				_datasource_Root_LordFace.PropertyChangedWithVec2Value += ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_LordFace;
				_widget_0_0_0.AdditionalArgs = _datasource_Root_LordFace.AdditionalArgs;
				_widget_0_0_0.ImageId = _datasource_Root_LordFace.Id;
				_widget_0_0_0.ImageTypeCode = _datasource_Root_LordFace.ImageTypeCode;
				_widget_0_0_0.PropertyChanged += PropertyChangedListenerOf_widget_0_0_0;
				_widget_0_0_0.boolPropertyChanged += boolPropertyChangedListenerOf_widget_0_0_0;
				_widget_0_0_0.floatPropertyChanged += floatPropertyChangedListenerOf_widget_0_0_0;
				_widget_0_0_0.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_0_0_0;
				_widget_0_0_0.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_0_0_0;
				_widget_0_0_0.doublePropertyChanged += doublePropertyChangedListenerOf_widget_0_0_0;
				_widget_0_0_0.intPropertyChanged += intPropertyChangedListenerOf_widget_0_0_0;
				_widget_0_0_0.uintPropertyChanged += uintPropertyChangedListenerOf_widget_0_0_0;
				_widget_0_0_0.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_0_0_0;
			}
			_datasource_Root_ClanBanner = _datasource_Root.ClanBanner;
			if (_datasource_Root_ClanBanner != null)
			{
				_datasource_Root_ClanBanner.PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root_ClanBanner;
				_datasource_Root_ClanBanner.PropertyChangedWithValue += ViewModelPropertyChangedWithValueListenerOf_datasource_Root_ClanBanner;
				_datasource_Root_ClanBanner.PropertyChangedWithBoolValue += ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_ClanBanner;
				_datasource_Root_ClanBanner.PropertyChangedWithIntValue += ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_ClanBanner;
				_datasource_Root_ClanBanner.PropertyChangedWithFloatValue += ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_ClanBanner;
				_datasource_Root_ClanBanner.PropertyChangedWithUIntValue += ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_ClanBanner;
				_datasource_Root_ClanBanner.PropertyChangedWithColorValue += ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_ClanBanner;
				_datasource_Root_ClanBanner.PropertyChangedWithDoubleValue += ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_ClanBanner;
				_datasource_Root_ClanBanner.PropertyChangedWithVec2Value += ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_ClanBanner;
				_widget_0_2_0.AdditionalArgs = _datasource_Root_ClanBanner.AdditionalArgs;
				_widget_0_2_0.ImageId = _datasource_Root_ClanBanner.Id;
				_widget_0_2_0.ImageTypeCode = _datasource_Root_ClanBanner.ImageTypeCode;
				_widget_0_2_0.PropertyChanged += PropertyChangedListenerOf_widget_0_2_0;
				_widget_0_2_0.boolPropertyChanged += boolPropertyChangedListenerOf_widget_0_2_0;
				_widget_0_2_0.floatPropertyChanged += floatPropertyChangedListenerOf_widget_0_2_0;
				_widget_0_2_0.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_0_2_0;
				_widget_0_2_0.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_0_2_0;
				_widget_0_2_0.doublePropertyChanged += doublePropertyChangedListenerOf_widget_0_2_0;
				_widget_0_2_0.intPropertyChanged += intPropertyChangedListenerOf_widget_0_2_0;
				_widget_0_2_0.uintPropertyChanged += uintPropertyChangedListenerOf_widget_0_2_0;
				_widget_0_2_0.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_0_2_0;
			}
		}
	}

	private void RefreshDataSource_datasource_Root_LordFace(ImageIdentifierVM newDataSource)
	{
		if (_datasource_Root_LordFace != null)
		{
			_datasource_Root_LordFace.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_LordFace;
			_datasource_Root_LordFace.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_LordFace;
			_datasource_Root_LordFace.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_LordFace;
			_datasource_Root_LordFace.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_LordFace;
			_datasource_Root_LordFace.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_LordFace;
			_datasource_Root_LordFace.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_LordFace;
			_datasource_Root_LordFace.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_LordFace;
			_datasource_Root_LordFace.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_LordFace;
			_datasource_Root_LordFace.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_LordFace;
			_widget_0_0_0.PropertyChanged -= PropertyChangedListenerOf_widget_0_0_0;
			_widget_0_0_0.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_0_0;
			_widget_0_0_0.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_0_0;
			_widget_0_0_0.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_0_0;
			_widget_0_0_0.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_0_0;
			_widget_0_0_0.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_0_0;
			_widget_0_0_0.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_0_0;
			_widget_0_0_0.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_0_0;
			_widget_0_0_0.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_0_0;
			_datasource_Root_LordFace = null;
		}
		_datasource_Root_LordFace = newDataSource;
		_datasource_Root_LordFace = _datasource_Root.LordFace;
		if (_datasource_Root_LordFace != null)
		{
			_datasource_Root_LordFace.PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root_LordFace;
			_datasource_Root_LordFace.PropertyChangedWithValue += ViewModelPropertyChangedWithValueListenerOf_datasource_Root_LordFace;
			_datasource_Root_LordFace.PropertyChangedWithBoolValue += ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_LordFace;
			_datasource_Root_LordFace.PropertyChangedWithIntValue += ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_LordFace;
			_datasource_Root_LordFace.PropertyChangedWithFloatValue += ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_LordFace;
			_datasource_Root_LordFace.PropertyChangedWithUIntValue += ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_LordFace;
			_datasource_Root_LordFace.PropertyChangedWithColorValue += ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_LordFace;
			_datasource_Root_LordFace.PropertyChangedWithDoubleValue += ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_LordFace;
			_datasource_Root_LordFace.PropertyChangedWithVec2Value += ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_LordFace;
			_widget_0_0_0.AdditionalArgs = _datasource_Root_LordFace.AdditionalArgs;
			_widget_0_0_0.ImageId = _datasource_Root_LordFace.Id;
			_widget_0_0_0.ImageTypeCode = _datasource_Root_LordFace.ImageTypeCode;
			_widget_0_0_0.PropertyChanged += PropertyChangedListenerOf_widget_0_0_0;
			_widget_0_0_0.boolPropertyChanged += boolPropertyChangedListenerOf_widget_0_0_0;
			_widget_0_0_0.floatPropertyChanged += floatPropertyChangedListenerOf_widget_0_0_0;
			_widget_0_0_0.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_0_0_0;
			_widget_0_0_0.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_0_0_0;
			_widget_0_0_0.doublePropertyChanged += doublePropertyChangedListenerOf_widget_0_0_0;
			_widget_0_0_0.intPropertyChanged += intPropertyChangedListenerOf_widget_0_0_0;
			_widget_0_0_0.uintPropertyChanged += uintPropertyChangedListenerOf_widget_0_0_0;
			_widget_0_0_0.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_0_0_0;
		}
	}

	private void RefreshDataSource_datasource_Root_ClanBanner(ImageIdentifierVM newDataSource)
	{
		if (_datasource_Root_ClanBanner != null)
		{
			_datasource_Root_ClanBanner.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_ClanBanner;
			_datasource_Root_ClanBanner.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_ClanBanner;
			_datasource_Root_ClanBanner.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_ClanBanner;
			_datasource_Root_ClanBanner.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_ClanBanner;
			_datasource_Root_ClanBanner.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_ClanBanner;
			_datasource_Root_ClanBanner.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_ClanBanner;
			_datasource_Root_ClanBanner.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_ClanBanner;
			_datasource_Root_ClanBanner.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_ClanBanner;
			_datasource_Root_ClanBanner.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_ClanBanner;
			_widget_0_2_0.PropertyChanged -= PropertyChangedListenerOf_widget_0_2_0;
			_widget_0_2_0.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_2_0;
			_widget_0_2_0.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_2_0;
			_widget_0_2_0.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_2_0;
			_widget_0_2_0.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_2_0;
			_widget_0_2_0.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_2_0;
			_widget_0_2_0.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_2_0;
			_widget_0_2_0.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_2_0;
			_widget_0_2_0.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_2_0;
			_datasource_Root_ClanBanner = null;
		}
		_datasource_Root_ClanBanner = newDataSource;
		_datasource_Root_ClanBanner = _datasource_Root.ClanBanner;
		if (_datasource_Root_ClanBanner != null)
		{
			_datasource_Root_ClanBanner.PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root_ClanBanner;
			_datasource_Root_ClanBanner.PropertyChangedWithValue += ViewModelPropertyChangedWithValueListenerOf_datasource_Root_ClanBanner;
			_datasource_Root_ClanBanner.PropertyChangedWithBoolValue += ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_ClanBanner;
			_datasource_Root_ClanBanner.PropertyChangedWithIntValue += ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_ClanBanner;
			_datasource_Root_ClanBanner.PropertyChangedWithFloatValue += ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_ClanBanner;
			_datasource_Root_ClanBanner.PropertyChangedWithUIntValue += ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_ClanBanner;
			_datasource_Root_ClanBanner.PropertyChangedWithColorValue += ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_ClanBanner;
			_datasource_Root_ClanBanner.PropertyChangedWithDoubleValue += ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_ClanBanner;
			_datasource_Root_ClanBanner.PropertyChangedWithVec2Value += ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_ClanBanner;
			_widget_0_2_0.AdditionalArgs = _datasource_Root_ClanBanner.AdditionalArgs;
			_widget_0_2_0.ImageId = _datasource_Root_ClanBanner.Id;
			_widget_0_2_0.ImageTypeCode = _datasource_Root_ClanBanner.ImageTypeCode;
			_widget_0_2_0.PropertyChanged += PropertyChangedListenerOf_widget_0_2_0;
			_widget_0_2_0.boolPropertyChanged += boolPropertyChangedListenerOf_widget_0_2_0;
			_widget_0_2_0.floatPropertyChanged += floatPropertyChangedListenerOf_widget_0_2_0;
			_widget_0_2_0.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_0_2_0;
			_widget_0_2_0.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_0_2_0;
			_widget_0_2_0.doublePropertyChanged += doublePropertyChangedListenerOf_widget_0_2_0;
			_widget_0_2_0.intPropertyChanged += intPropertyChangedListenerOf_widget_0_2_0;
			_widget_0_2_0.uintPropertyChanged += uintPropertyChangedListenerOf_widget_0_2_0;
			_widget_0_2_0.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_0_2_0;
		}
	}
}
