using System.ComponentModel;
using System.Numerics;
using TaleWorlds.CampaignSystem.ViewModelCollection.GameMenu;
using TaleWorlds.Core;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.Library;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets;

namespace SandBox.GauntletUI.AutoGenerated0;

public class GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_3_ItemTemplate : ButtonWidget
{
	private ButtonWidget _widget;

	private ImageIdentifierWidget _widget_0;

	private GameMenuPlunderItemVM _datasource_Root;

	private ImageIdentifierVM _datasource_Root_Visual;

	public GameMenu__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_GameMenuVM_Dependency_3_ItemTemplate(UIContext context)
		: base(context)
	{
	}

	private VisualDefinition CreateVisualDefinitionMenu()
	{
		VisualDefinition visualDefinition = new VisualDefinition("Menu", 0.65f, 0f, easeIn: true);
		visualDefinition.AddVisualState(new VisualState("Default")
		{
			PositionXOffset = 0f
		});
		visualDefinition.AddVisualState(new VisualState("Disabled")
		{
			PositionXOffset = -530f
		});
		return visualDefinition;
	}

	private VisualDefinition CreateVisualDefinitionInfoPanel()
	{
		VisualDefinition visualDefinition = new VisualDefinition("InfoPanel", 0.45f, 0f, easeIn: true);
		visualDefinition.AddVisualState(new VisualState("Default")
		{
			SuggestedWidth = 900f,
			SuggestedHeight = 170f,
			PositionXOffset = 50f
		});
		visualDefinition.AddVisualState(new VisualState("Disabled")
		{
			SuggestedWidth = 900f,
			SuggestedHeight = 0f,
			PositionXOffset = 50f
		});
		return visualDefinition;
	}

	public void CreateWidgets()
	{
		_widget = this;
		_widget_0 = new ImageIdentifierWidget(base.Context);
		_widget.AddChild(_widget_0);
	}

	public void SetIds()
	{
		_widget_0.Id = "ImageIdentifierWidget";
	}

	public void SetAttributes()
	{
		base.DoNotPassEventsToChildren = true;
		base.WidthSizePolicy = SizePolicy.Fixed;
		base.HeightSizePolicy = SizePolicy.Fixed;
		base.SuggestedWidth = 50f;
		base.SuggestedHeight = 30f;
		base.HorizontalAlignment = HorizontalAlignment.Center;
		base.VerticalAlignment = VerticalAlignment.Center;
		base.Brush = base.Context.GetBrush("FaceGen.Card.Only.Default");
		base.ClipContents = true;
		_widget_0.DoNotAcceptEvents = true;
		_widget_0.WidthSizePolicy = SizePolicy.Fixed;
		_widget_0.HeightSizePolicy = SizePolicy.Fixed;
		_widget_0.SuggestedWidth = 50f;
		_widget_0.SuggestedHeight = 22f;
		_widget_0.VerticalAlignment = VerticalAlignment.Center;
		_widget_0.IsBig = true;
	}

	public void DestroyDataSource()
	{
		if (_datasource_Root != null)
		{
			_datasource_Root.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
			_widget.EventFire -= EventListenerOf_widget;
			if (_datasource_Root_Visual != null)
			{
				_datasource_Root_Visual.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_Visual;
				_datasource_Root_Visual.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Visual;
				_datasource_Root_Visual.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Visual;
				_datasource_Root_Visual.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Visual;
				_datasource_Root_Visual.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Visual;
				_datasource_Root_Visual.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Visual;
				_datasource_Root_Visual.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Visual;
				_datasource_Root_Visual.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Visual;
				_datasource_Root_Visual.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Visual;
				_widget_0.PropertyChanged -= PropertyChangedListenerOf_widget_0;
				_widget_0.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0;
				_widget_0.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0;
				_widget_0.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0;
				_widget_0.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0;
				_widget_0.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0;
				_widget_0.intPropertyChanged -= intPropertyChangedListenerOf_widget_0;
				_widget_0.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0;
				_widget_0.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0;
				_datasource_Root_Visual = null;
			}
			_datasource_Root = null;
		}
	}

	public void SetDataSource(GameMenuPlunderItemVM dataSource)
	{
		RefreshDataSource_datasource_Root(dataSource);
	}

	private void EventListenerOf_widget(Widget widget, string commandName, object[] args)
	{
		if (commandName == "HoverBegin")
		{
			_datasource_Root.ExecuteBeginTooltip();
		}
		if (commandName == "HoverEnd")
		{
			_datasource_Root.ExecuteEndTooltip();
		}
	}

	private void PropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_0(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_0(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_0(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_0(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_0(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_0(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_0(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_0(string propertyName)
	{
		if (!(propertyName == "AdditionalArgs") && !(propertyName == "ImageId"))
		{
			_ = propertyName == "ImageTypeCode";
		}
	}

	private void ViewModelPropertyChangedListenerOf_datasource_Root(object sender, PropertyChangedEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root(object sender, PropertyChangedWithValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root(object sender, PropertyChangedWithBoolValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root(object sender, PropertyChangedWithFloatValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithUIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root(object sender, PropertyChangedWithColorValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root(object sender, PropertyChangedWithDoubleValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root(object sender, PropertyChangedWithVec2ValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void HandleViewModelPropertyChangeOf_datasource_Root(string propertyName)
	{
		if (propertyName == "Visual")
		{
			RefreshDataSource_datasource_Root_Visual(_datasource_Root.Visual);
		}
	}

	private void ViewModelPropertyChangedListenerOf_datasource_Root_Visual(object sender, PropertyChangedEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Visual(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Visual(object sender, PropertyChangedWithValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Visual(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Visual(object sender, PropertyChangedWithBoolValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Visual(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Visual(object sender, PropertyChangedWithIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Visual(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Visual(object sender, PropertyChangedWithFloatValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Visual(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Visual(object sender, PropertyChangedWithUIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Visual(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Visual(object sender, PropertyChangedWithColorValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Visual(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Visual(object sender, PropertyChangedWithDoubleValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Visual(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Visual(object sender, PropertyChangedWithVec2ValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Visual(e.PropertyName);
	}

	private void HandleViewModelPropertyChangeOf_datasource_Root_Visual(string propertyName)
	{
		switch (propertyName)
		{
		case "AdditionalArgs":
			_widget_0.AdditionalArgs = _datasource_Root_Visual.AdditionalArgs;
			break;
		case "Id":
			_widget_0.ImageId = _datasource_Root_Visual.Id;
			break;
		case "ImageTypeCode":
			_widget_0.ImageTypeCode = _datasource_Root_Visual.ImageTypeCode;
			break;
		}
	}

	private void RefreshDataSource_datasource_Root(GameMenuPlunderItemVM newDataSource)
	{
		if (_datasource_Root != null)
		{
			_datasource_Root.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
			_widget.EventFire -= EventListenerOf_widget;
			if (_datasource_Root_Visual != null)
			{
				_datasource_Root_Visual.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_Visual;
				_datasource_Root_Visual.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Visual;
				_datasource_Root_Visual.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Visual;
				_datasource_Root_Visual.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Visual;
				_datasource_Root_Visual.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Visual;
				_datasource_Root_Visual.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Visual;
				_datasource_Root_Visual.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Visual;
				_datasource_Root_Visual.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Visual;
				_datasource_Root_Visual.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Visual;
				_widget_0.PropertyChanged -= PropertyChangedListenerOf_widget_0;
				_widget_0.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0;
				_widget_0.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0;
				_widget_0.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0;
				_widget_0.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0;
				_widget_0.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0;
				_widget_0.intPropertyChanged -= intPropertyChangedListenerOf_widget_0;
				_widget_0.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0;
				_widget_0.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0;
				_datasource_Root_Visual = null;
			}
			_datasource_Root = null;
		}
		_datasource_Root = newDataSource;
		if (_datasource_Root != null)
		{
			_datasource_Root.PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithValue += ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithBoolValue += ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithIntValue += ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithFloatValue += ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithUIntValue += ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithColorValue += ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithDoubleValue += ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithVec2Value += ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
			_widget.EventFire += EventListenerOf_widget;
			_datasource_Root_Visual = _datasource_Root.Visual;
			if (_datasource_Root_Visual != null)
			{
				_datasource_Root_Visual.PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root_Visual;
				_datasource_Root_Visual.PropertyChangedWithValue += ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Visual;
				_datasource_Root_Visual.PropertyChangedWithBoolValue += ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Visual;
				_datasource_Root_Visual.PropertyChangedWithIntValue += ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Visual;
				_datasource_Root_Visual.PropertyChangedWithFloatValue += ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Visual;
				_datasource_Root_Visual.PropertyChangedWithUIntValue += ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Visual;
				_datasource_Root_Visual.PropertyChangedWithColorValue += ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Visual;
				_datasource_Root_Visual.PropertyChangedWithDoubleValue += ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Visual;
				_datasource_Root_Visual.PropertyChangedWithVec2Value += ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Visual;
				_widget_0.AdditionalArgs = _datasource_Root_Visual.AdditionalArgs;
				_widget_0.ImageId = _datasource_Root_Visual.Id;
				_widget_0.ImageTypeCode = _datasource_Root_Visual.ImageTypeCode;
				_widget_0.PropertyChanged += PropertyChangedListenerOf_widget_0;
				_widget_0.boolPropertyChanged += boolPropertyChangedListenerOf_widget_0;
				_widget_0.floatPropertyChanged += floatPropertyChangedListenerOf_widget_0;
				_widget_0.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_0;
				_widget_0.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_0;
				_widget_0.doublePropertyChanged += doublePropertyChangedListenerOf_widget_0;
				_widget_0.intPropertyChanged += intPropertyChangedListenerOf_widget_0;
				_widget_0.uintPropertyChanged += uintPropertyChangedListenerOf_widget_0;
				_widget_0.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_0;
			}
		}
	}

	private void RefreshDataSource_datasource_Root_Visual(ImageIdentifierVM newDataSource)
	{
		if (_datasource_Root_Visual != null)
		{
			_datasource_Root_Visual.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Visual;
			_widget_0.PropertyChanged -= PropertyChangedListenerOf_widget_0;
			_widget_0.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0;
			_widget_0.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0;
			_widget_0.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0;
			_widget_0.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0;
			_widget_0.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0;
			_widget_0.intPropertyChanged -= intPropertyChangedListenerOf_widget_0;
			_widget_0.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0;
			_widget_0.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0;
			_datasource_Root_Visual = null;
		}
		_datasource_Root_Visual = newDataSource;
		_datasource_Root_Visual = _datasource_Root.Visual;
		if (_datasource_Root_Visual != null)
		{
			_datasource_Root_Visual.PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithValue += ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithBoolValue += ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithIntValue += ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithFloatValue += ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithUIntValue += ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithColorValue += ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithDoubleValue += ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithVec2Value += ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Visual;
			_widget_0.AdditionalArgs = _datasource_Root_Visual.AdditionalArgs;
			_widget_0.ImageId = _datasource_Root_Visual.Id;
			_widget_0.ImageTypeCode = _datasource_Root_Visual.ImageTypeCode;
			_widget_0.PropertyChanged += PropertyChangedListenerOf_widget_0;
			_widget_0.boolPropertyChanged += boolPropertyChangedListenerOf_widget_0;
			_widget_0.floatPropertyChanged += floatPropertyChangedListenerOf_widget_0;
			_widget_0.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_0;
			_widget_0.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_0;
			_widget_0.doublePropertyChanged += doublePropertyChangedListenerOf_widget_0;
			_widget_0.intPropertyChanged += intPropertyChangedListenerOf_widget_0;
			_widget_0.uintPropertyChanged += uintPropertyChangedListenerOf_widget_0;
			_widget_0.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_0;
		}
	}
}
