using System.ComponentModel;
using SandBox.ViewModelCollection.Nameplate;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.GauntletUI.Data;
using TaleWorlds.Library;

namespace SandBox.GauntletUI.AutoGenerated0;

public class PartyNameplate__SandBox_ViewModelCollection_Nameplate_PartyNameplatesVM : Widget, IGeneratedGauntletMovieRoot
{
	private Widget _widget;

	private Widget _widget_0;

	private PartyNameplatesVM _datasource_Root;

	private MBBindingList<PartyNameplateVM> _datasource_Root_Nameplates;

	public PartyNameplate__SandBox_ViewModelCollection_Nameplate_PartyNameplatesVM(UIContext context)
		: base(context)
	{
	}

	public void CreateWidgets()
	{
		_widget = this;
		_widget_0 = new Widget(base.Context);
		_widget.AddChild(_widget_0);
	}

	public void SetIds()
	{
	}

	public void SetAttributes()
	{
		base.HeightSizePolicy = SizePolicy.StretchToParent;
		base.WidthSizePolicy = SizePolicy.StretchToParent;
		base.DoNotAcceptEvents = true;
		_widget_0.HeightSizePolicy = SizePolicy.StretchToParent;
		_widget_0.WidthSizePolicy = SizePolicy.StretchToParent;
		_widget_0.DoNotAcceptEvents = true;
	}

	public void RefreshBindingWithChildren()
	{
		PartyNameplatesVM datasource_Root = _datasource_Root;
		SetDataSource(null);
		SetDataSource(datasource_Root);
	}

	public void DestroyDataSource()
	{
		if (_datasource_Root == null)
		{
			return;
		}
		_datasource_Root.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
		if (_datasource_Root_Nameplates != null)
		{
			_datasource_Root_Nameplates.ListChanged -= OnList_datasource_Root_NameplatesChanged;
			for (int num = _widget_0.ChildCount - 1; num >= 0; num--)
			{
				Widget child = _widget_0.GetChild(num);
				((PartyNameplate__SandBox_ViewModelCollection_Nameplate_PartyNameplatesVM_Dependency_1_ItemTemplate)child).OnBeforeRemovedChild(child);
				((PartyNameplate__SandBox_ViewModelCollection_Nameplate_PartyNameplatesVM_Dependency_1_ItemTemplate)_widget_0.GetChild(num)).DestroyDataSource();
			}
			_datasource_Root_Nameplates = null;
		}
		_datasource_Root = null;
	}

	public void SetDataSource(PartyNameplatesVM dataSource)
	{
		RefreshDataSource_datasource_Root(dataSource);
	}

	private void ViewModelPropertyChangedListenerOf_datasource_Root(object sender, PropertyChangedEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root(object sender, PropertyChangedWithValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root(object sender, PropertyChangedWithBoolValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root(object sender, PropertyChangedWithFloatValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithUIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root(object sender, PropertyChangedWithColorValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root(object sender, PropertyChangedWithDoubleValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root(object sender, PropertyChangedWithVec2ValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void HandleViewModelPropertyChangeOf_datasource_Root(string propertyName)
	{
		if (propertyName == "Nameplates")
		{
			RefreshDataSource_datasource_Root_Nameplates(_datasource_Root.Nameplates);
		}
	}

	public void OnList_datasource_Root_NameplatesChanged(object sender, TaleWorlds.Library.ListChangedEventArgs e)
	{
		switch (e.ListChangedType)
		{
		case TaleWorlds.Library.ListChangedType.Reset:
		{
			for (int num = _widget_0.ChildCount - 1; num >= 0; num--)
			{
				Widget child3 = _widget_0.GetChild(num);
				((PartyNameplate__SandBox_ViewModelCollection_Nameplate_PartyNameplatesVM_Dependency_1_ItemTemplate)child3).OnBeforeRemovedChild(child3);
				Widget child4 = _widget_0.GetChild(num);
				((PartyNameplate__SandBox_ViewModelCollection_Nameplate_PartyNameplatesVM_Dependency_1_ItemTemplate)child4).SetDataSource(null);
				_widget_0.RemoveChild(child4);
			}
			break;
		}
		case TaleWorlds.Library.ListChangedType.Sorted:
		{
			for (int i = 0; i < _datasource_Root_Nameplates.Count; i++)
			{
				PartyNameplateVM bindingObject = _datasource_Root_Nameplates[i];
				_widget_0.FindChild((Widget widget) => widget.GetComponent<GeneratedWidgetData>().Data == bindingObject).SetSiblingIndex(i);
			}
			break;
		}
		case TaleWorlds.Library.ListChangedType.ItemAdded:
		{
			PartyNameplate__SandBox_ViewModelCollection_Nameplate_PartyNameplatesVM_Dependency_1_ItemTemplate partyNameplate__SandBox_ViewModelCollection_Nameplate_PartyNameplatesVM_Dependency_1_ItemTemplate = new PartyNameplate__SandBox_ViewModelCollection_Nameplate_PartyNameplatesVM_Dependency_1_ItemTemplate(base.Context);
			GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(partyNameplate__SandBox_ViewModelCollection_Nameplate_PartyNameplatesVM_Dependency_1_ItemTemplate);
			PartyNameplateVM dataSource = (PartyNameplateVM)(generatedWidgetData.Data = _datasource_Root_Nameplates[e.NewIndex]);
			partyNameplate__SandBox_ViewModelCollection_Nameplate_PartyNameplatesVM_Dependency_1_ItemTemplate.AddComponent(generatedWidgetData);
			_widget_0.AddChildAtIndex(partyNameplate__SandBox_ViewModelCollection_Nameplate_PartyNameplatesVM_Dependency_1_ItemTemplate, e.NewIndex);
			partyNameplate__SandBox_ViewModelCollection_Nameplate_PartyNameplatesVM_Dependency_1_ItemTemplate.CreateWidgets();
			partyNameplate__SandBox_ViewModelCollection_Nameplate_PartyNameplatesVM_Dependency_1_ItemTemplate.SetIds();
			partyNameplate__SandBox_ViewModelCollection_Nameplate_PartyNameplatesVM_Dependency_1_ItemTemplate.SetAttributes();
			partyNameplate__SandBox_ViewModelCollection_Nameplate_PartyNameplatesVM_Dependency_1_ItemTemplate.SetDataSource(dataSource);
			break;
		}
		case TaleWorlds.Library.ListChangedType.ItemBeforeDeleted:
		{
			Widget child2 = _widget_0.GetChild(e.NewIndex);
			((PartyNameplate__SandBox_ViewModelCollection_Nameplate_PartyNameplatesVM_Dependency_1_ItemTemplate)child2).OnBeforeRemovedChild(child2);
			break;
		}
		case TaleWorlds.Library.ListChangedType.ItemDeleted:
		{
			Widget child = _widget_0.GetChild(e.NewIndex);
			((PartyNameplate__SandBox_ViewModelCollection_Nameplate_PartyNameplatesVM_Dependency_1_ItemTemplate)child).SetDataSource(null);
			_widget_0.RemoveChild(child);
			break;
		}
		case TaleWorlds.Library.ListChangedType.ItemChanged:
			break;
		}
	}

	private void RefreshDataSource_datasource_Root(PartyNameplatesVM newDataSource)
	{
		if (_datasource_Root != null)
		{
			_datasource_Root.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
			if (_datasource_Root_Nameplates != null)
			{
				_datasource_Root_Nameplates.ListChanged -= OnList_datasource_Root_NameplatesChanged;
				for (int num = _widget_0.ChildCount - 1; num >= 0; num--)
				{
					Widget child = _widget_0.GetChild(num);
					((PartyNameplate__SandBox_ViewModelCollection_Nameplate_PartyNameplatesVM_Dependency_1_ItemTemplate)child).OnBeforeRemovedChild(child);
					Widget child2 = _widget_0.GetChild(num);
					((PartyNameplate__SandBox_ViewModelCollection_Nameplate_PartyNameplatesVM_Dependency_1_ItemTemplate)child2).SetDataSource(null);
					_widget_0.RemoveChild(child2);
				}
				_datasource_Root_Nameplates = null;
			}
			_datasource_Root = null;
		}
		_datasource_Root = newDataSource;
		if (_datasource_Root == null)
		{
			return;
		}
		_datasource_Root.PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithValue += ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithBoolValue += ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithIntValue += ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithFloatValue += ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithUIntValue += ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithColorValue += ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithDoubleValue += ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithVec2Value += ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
		_datasource_Root_Nameplates = _datasource_Root.Nameplates;
		if (_datasource_Root_Nameplates != null)
		{
			_datasource_Root_Nameplates.ListChanged += OnList_datasource_Root_NameplatesChanged;
			for (int i = 0; i < _datasource_Root_Nameplates.Count; i++)
			{
				PartyNameplate__SandBox_ViewModelCollection_Nameplate_PartyNameplatesVM_Dependency_1_ItemTemplate partyNameplate__SandBox_ViewModelCollection_Nameplate_PartyNameplatesVM_Dependency_1_ItemTemplate = new PartyNameplate__SandBox_ViewModelCollection_Nameplate_PartyNameplatesVM_Dependency_1_ItemTemplate(base.Context);
				GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(partyNameplate__SandBox_ViewModelCollection_Nameplate_PartyNameplatesVM_Dependency_1_ItemTemplate);
				PartyNameplateVM dataSource = (PartyNameplateVM)(generatedWidgetData.Data = _datasource_Root_Nameplates[i]);
				partyNameplate__SandBox_ViewModelCollection_Nameplate_PartyNameplatesVM_Dependency_1_ItemTemplate.AddComponent(generatedWidgetData);
				_widget_0.AddChildAtIndex(partyNameplate__SandBox_ViewModelCollection_Nameplate_PartyNameplatesVM_Dependency_1_ItemTemplate, i);
				partyNameplate__SandBox_ViewModelCollection_Nameplate_PartyNameplatesVM_Dependency_1_ItemTemplate.CreateWidgets();
				partyNameplate__SandBox_ViewModelCollection_Nameplate_PartyNameplatesVM_Dependency_1_ItemTemplate.SetIds();
				partyNameplate__SandBox_ViewModelCollection_Nameplate_PartyNameplatesVM_Dependency_1_ItemTemplate.SetAttributes();
				partyNameplate__SandBox_ViewModelCollection_Nameplate_PartyNameplatesVM_Dependency_1_ItemTemplate.SetDataSource(dataSource);
			}
		}
	}

	private void RefreshDataSource_datasource_Root_Nameplates(MBBindingList<PartyNameplateVM> newDataSource)
	{
		if (_datasource_Root_Nameplates != null)
		{
			_datasource_Root_Nameplates.ListChanged -= OnList_datasource_Root_NameplatesChanged;
			for (int num = _widget_0.ChildCount - 1; num >= 0; num--)
			{
				Widget child = _widget_0.GetChild(num);
				((PartyNameplate__SandBox_ViewModelCollection_Nameplate_PartyNameplatesVM_Dependency_1_ItemTemplate)child).OnBeforeRemovedChild(child);
				Widget child2 = _widget_0.GetChild(num);
				((PartyNameplate__SandBox_ViewModelCollection_Nameplate_PartyNameplatesVM_Dependency_1_ItemTemplate)child2).SetDataSource(null);
				_widget_0.RemoveChild(child2);
			}
			_datasource_Root_Nameplates = null;
		}
		_datasource_Root_Nameplates = newDataSource;
		_datasource_Root_Nameplates = _datasource_Root.Nameplates;
		if (_datasource_Root_Nameplates != null)
		{
			_datasource_Root_Nameplates.ListChanged += OnList_datasource_Root_NameplatesChanged;
			for (int i = 0; i < _datasource_Root_Nameplates.Count; i++)
			{
				PartyNameplate__SandBox_ViewModelCollection_Nameplate_PartyNameplatesVM_Dependency_1_ItemTemplate partyNameplate__SandBox_ViewModelCollection_Nameplate_PartyNameplatesVM_Dependency_1_ItemTemplate = new PartyNameplate__SandBox_ViewModelCollection_Nameplate_PartyNameplatesVM_Dependency_1_ItemTemplate(base.Context);
				GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(partyNameplate__SandBox_ViewModelCollection_Nameplate_PartyNameplatesVM_Dependency_1_ItemTemplate);
				PartyNameplateVM dataSource = (PartyNameplateVM)(generatedWidgetData.Data = _datasource_Root_Nameplates[i]);
				partyNameplate__SandBox_ViewModelCollection_Nameplate_PartyNameplatesVM_Dependency_1_ItemTemplate.AddComponent(generatedWidgetData);
				_widget_0.AddChildAtIndex(partyNameplate__SandBox_ViewModelCollection_Nameplate_PartyNameplatesVM_Dependency_1_ItemTemplate, i);
				partyNameplate__SandBox_ViewModelCollection_Nameplate_PartyNameplatesVM_Dependency_1_ItemTemplate.CreateWidgets();
				partyNameplate__SandBox_ViewModelCollection_Nameplate_PartyNameplatesVM_Dependency_1_ItemTemplate.SetIds();
				partyNameplate__SandBox_ViewModelCollection_Nameplate_PartyNameplatesVM_Dependency_1_ItemTemplate.SetAttributes();
				partyNameplate__SandBox_ViewModelCollection_Nameplate_PartyNameplatesVM_Dependency_1_ItemTemplate.SetDataSource(dataSource);
			}
		}
	}
}
