using System.ComponentModel;
using System.Numerics;
using TaleWorlds.CampaignSystem.ViewModelCollection.GameMenu.Overlay;
using TaleWorlds.CampaignSystem.ViewModelCollection.Quests;
using TaleWorlds.Core;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.GauntletUI.Data;
using TaleWorlds.GauntletUI.Layout;
using TaleWorlds.Library;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets.Menu.Overlay;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets.Tutorial;
using TaleWorlds.TwoDimension;

namespace SandBox.GauntletUI.AutoGenerated0;

public class SettlementOverlay__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_Overlay_SettlementMenuOverlayVM_Dependency_8_GameMenuPartyItem__InheritedPrefab : GameMenuPartyItemButtonWidget
{
	private GameMenuPartyItemButtonWidget _widget;

	private Widget _widget_0;

	private ImageWidget _widget_0_0;

	private MaskedTextureWidget _widget_0_1;

	private ImageIdentifierWidget _widget_0_2;

	private ListPanel _widget_0_3;

	private Widget _widget_1;

	private TextWidget _widget_2;

	private TextWidget _widget_3;

	private TextWidget _widget_4;

	private TextWidget _widget_5;

	private TextWidget _widget_6;

	private TutorialHighlightItemBrushWidget _widget_7;

	private GameMenuPartyItemVM _datasource_Root;

	private ImageIdentifierVM _datasource_Root_Banner_9;

	private ImageIdentifierVM _datasource_Root_Visual;

	private MBBindingList<QuestMarkerVM> _datasource_Root_Quests;

	public SettlementOverlay__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_Overlay_SettlementMenuOverlayVM_Dependency_8_GameMenuPartyItem__InheritedPrefab(UIContext context)
		: base(context)
	{
	}

	public virtual void CreateWidgets()
	{
		_widget = this;
		_widget_0 = new Widget(base.Context);
		_widget.AddChild(_widget_0);
		_widget_0_0 = new ImageWidget(base.Context);
		_widget_0.AddChild(_widget_0_0);
		_widget_0_1 = new MaskedTextureWidget(base.Context);
		_widget_0.AddChild(_widget_0_1);
		_widget_0_2 = new ImageIdentifierWidget(base.Context);
		_widget_0.AddChild(_widget_0_2);
		_widget_0_3 = new ListPanel(base.Context);
		_widget_0.AddChild(_widget_0_3);
		_widget_1 = new Widget(base.Context);
		_widget.AddChild(_widget_1);
		_widget_2 = new TextWidget(base.Context);
		_widget.AddChild(_widget_2);
		_widget_3 = new TextWidget(base.Context);
		_widget.AddChild(_widget_3);
		_widget_4 = new TextWidget(base.Context);
		_widget.AddChild(_widget_4);
		_widget_5 = new TextWidget(base.Context);
		_widget.AddChild(_widget_5);
		_widget_6 = new TextWidget(base.Context);
		_widget.AddChild(_widget_6);
		_widget_7 = new TutorialHighlightItemBrushWidget(base.Context);
		_widget.AddChild(_widget_7);
	}

	public virtual void SetIds()
	{
		_widget_0.Id = "RelationBackgroundWidget";
		_widget_0_0.Id = "BackgroundImageWidget";
		_widget_0_2.Id = "CharacterImage";
		_widget_3.Id = "NameTextWidget";
		_widget_4.Id = "NameTextWidget";
		_widget_5.Id = "NameTextWidget";
		_widget_6.Id = "NameTextWidget";
	}

	public virtual void SetAttributes()
	{
		base.DoNotPassEventsToChildren = true;
		base.WidthSizePolicy = SizePolicy.Fixed;
		base.HeightSizePolicy = SizePolicy.Fixed;
		base.SuggestedWidth = 125f;
		base.SuggestedHeight = 150f;
		base.CurrentCharacterImageWidget = _widget_0_2;
		base.UpdateChildrenStates = true;
		base.IsPartyItem = true;
		base.PartyBackgroundBrush = base.Context.GetBrush("GameMenu.Tableau.Background.Party");
		base.CharacterBackgroundBrush = base.Context.GetBrush("GameMenu.Tableau.Background.Character");
		base.BackgroundImageWidget = _widget_0_0;
		base.HoveredCursorState = "RightClickLink";
		_widget_0.WidthSizePolicy = SizePolicy.StretchToParent;
		_widget_0.HeightSizePolicy = SizePolicy.Fixed;
		_widget_0.SuggestedHeight = 85f;
		_widget_0.HorizontalAlignment = HorizontalAlignment.Center;
		_widget_0.MarginLeft = 4f;
		_widget_0.MarginRight = 4f;
		_widget_0.MarginTop = 4f;
		_widget_0.MarginBottom = 4f;
		_widget_0.UpdateChildrenStates = true;
		_widget_0_0.WidthSizePolicy = SizePolicy.StretchToParent;
		_widget_0_0.HeightSizePolicy = SizePolicy.StretchToParent;
		_widget_0_0.OverrideDefaultStateSwitchingDisabled = true;
		_widget_0_1.WidthSizePolicy = SizePolicy.Fixed;
		_widget_0_1.HeightSizePolicy = SizePolicy.Fixed;
		_widget_0_1.SuggestedWidth = 40.8f;
		_widget_0_1.SuggestedHeight = 65.74f;
		_widget_0_1.HorizontalAlignment = HorizontalAlignment.Right;
		_widget_0_1.VerticalAlignment = VerticalAlignment.Top;
		_widget_0_1.MarginTop = 1f;
		_widget_0_1.MarginRight = 3f;
		_widget_0_1.Brush = base.Context.GetBrush("Flat.Tuple.Banner.Small.Hero");
		_widget_0_1.IsDisabled = true;
		_widget_0_2.WidthSizePolicy = SizePolicy.StretchToParent;
		_widget_0_2.HeightSizePolicy = SizePolicy.StretchToParent;
		_widget_0_3.WidthSizePolicy = SizePolicy.CoverChildren;
		_widget_0_3.HeightSizePolicy = SizePolicy.CoverChildren;
		_widget_0_3.StackLayout.LayoutMethod = LayoutMethod.HorizontalLeftToRight;
		_widget_0_3.HorizontalAlignment = HorizontalAlignment.Right;
		_widget_0_3.VerticalAlignment = VerticalAlignment.Bottom;
		_widget_0_3.IsEnabled = false;
		_widget_0_3.DoNotAcceptEvents = true;
		_widget_1.WidthSizePolicy = SizePolicy.Fixed;
		_widget_1.HeightSizePolicy = SizePolicy.Fixed;
		_widget_1.SuggestedWidth = 38f;
		_widget_1.SuggestedHeight = 25f;
		_widget_1.HorizontalAlignment = HorizontalAlignment.Left;
		_widget_1.VerticalAlignment = VerticalAlignment.Top;
		_widget_1.MarginLeft = 5f;
		_widget_1.MarginTop = 7f;
		_widget_1.Sprite = base.Context.SpriteData.GetSprite("General\\Mission\\dungeon");
		_widget_1.Color = new Color(0.9568628f, 0.882353f, 0.7686275f);
		_widget_1.DoNotAcceptEvents = true;
		_widget_2.WidthSizePolicy = SizePolicy.CoverChildren;
		_widget_2.HeightSizePolicy = SizePolicy.Fixed;
		_widget_2.SuggestedHeight = 25f;
		_widget_2.HorizontalAlignment = HorizontalAlignment.Left;
		_widget_2.VerticalAlignment = VerticalAlignment.Top;
		_widget_2.MarginLeft = 8f;
		_widget_2.MarginRight = 8f;
		_widget_2.MarginTop = 7f;
		_widget_2.Brush = base.Context.GetBrush("EncounterTextBrush");
		_widget_2.Brush.FontSize = 18;
		_widget_2.Brush.TextHorizontalAlignment = TextHorizontalAlignment.Right;
		_widget_3.WidthSizePolicy = SizePolicy.StretchToParent;
		_widget_3.HeightSizePolicy = SizePolicy.Fixed;
		_widget_3.SuggestedHeight = 40f;
		_widget_3.VerticalAlignment = VerticalAlignment.Bottom;
		_widget_3.MarginLeft = 5f;
		_widget_3.MarginRight = 5f;
		_widget_3.MarginBottom = 15f;
		_widget_3.Brush = base.Context.GetBrush("EncounterTextBrush");
		_widget_3.Brush.FontSize = 16;
		_widget_4.WidthSizePolicy = SizePolicy.StretchToParent;
		_widget_4.HeightSizePolicy = SizePolicy.Fixed;
		_widget_4.SuggestedHeight = 40f;
		_widget_4.VerticalAlignment = VerticalAlignment.Bottom;
		_widget_4.MarginLeft = 5f;
		_widget_4.MarginRight = 5f;
		_widget_4.MarginBottom = 15f;
		_widget_4.Brush = base.Context.GetBrush("EncounterTextBrush");
		_widget_4.Brush.FontSize = 16;
		_widget_4.Brush.FontColor = new Color(0.5490196f, 0.8588236f, 0.7098039f);
		_widget_5.WidthSizePolicy = SizePolicy.StretchToParent;
		_widget_5.HeightSizePolicy = SizePolicy.Fixed;
		_widget_5.SuggestedHeight = 40f;
		_widget_5.VerticalAlignment = VerticalAlignment.Bottom;
		_widget_5.MarginLeft = 5f;
		_widget_5.MarginRight = 5f;
		_widget_5.MarginBottom = 15f;
		_widget_5.Brush = base.Context.GetBrush("EncounterTextBrush");
		_widget_5.Brush.FontSize = 16;
		_widget_5.Brush.FontColor = new Color(13f / 15f, 0.3294118f, 0.3294118f);
		_widget_6.WidthSizePolicy = SizePolicy.StretchToParent;
		_widget_6.HeightSizePolicy = SizePolicy.Fixed;
		_widget_6.SuggestedHeight = 40f;
		_widget_6.VerticalAlignment = VerticalAlignment.Bottom;
		_widget_6.MarginLeft = 5f;
		_widget_6.MarginRight = 5f;
		_widget_6.MarginBottom = 15f;
		_widget_6.Brush = base.Context.GetBrush("EncounterTextBrush");
		_widget_6.Brush.FontSize = 16;
		_widget_6.Brush.FontColor = new Color(0.3058824f, 0.8784314f, 0.2980392f);
		_widget_7.WidthSizePolicy = SizePolicy.StretchToParent;
		_widget_7.HeightSizePolicy = SizePolicy.StretchToParent;
		_widget_7.Brush = base.Context.GetBrush("TutorialHighlightBrush");
		_widget_7.IsEnabled = false;
		_widget_7.IsVisible = false;
	}

	public virtual void DestroyDataSource()
	{
		if (_datasource_Root == null)
		{
			return;
		}
		_datasource_Root.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
		_widget.EventFire -= EventListenerOf_widget;
		_widget.PropertyChanged -= PropertyChangedListenerOf_widget;
		_widget.boolPropertyChanged -= boolPropertyChangedListenerOf_widget;
		_widget.floatPropertyChanged -= floatPropertyChangedListenerOf_widget;
		_widget.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget;
		_widget.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget;
		_widget.doublePropertyChanged -= doublePropertyChangedListenerOf_widget;
		_widget.intPropertyChanged -= intPropertyChangedListenerOf_widget;
		_widget.uintPropertyChanged -= uintPropertyChangedListenerOf_widget;
		_widget.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget;
		_widget_1.PropertyChanged -= PropertyChangedListenerOf_widget_1;
		_widget_1.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_1;
		_widget_1.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_1;
		_widget_1.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_1;
		_widget_1.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_1;
		_widget_1.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_1;
		_widget_1.intPropertyChanged -= intPropertyChangedListenerOf_widget_1;
		_widget_1.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_1;
		_widget_1.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_1;
		_widget_2.PropertyChanged -= PropertyChangedListenerOf_widget_2;
		_widget_2.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_2;
		_widget_2.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_2;
		_widget_2.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_2;
		_widget_2.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_2;
		_widget_2.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_2;
		_widget_2.intPropertyChanged -= intPropertyChangedListenerOf_widget_2;
		_widget_2.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_2;
		_widget_2.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_2;
		_widget_3.PropertyChanged -= PropertyChangedListenerOf_widget_3;
		_widget_3.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_3;
		_widget_3.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_3;
		_widget_3.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_3;
		_widget_3.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_3;
		_widget_3.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_3;
		_widget_3.intPropertyChanged -= intPropertyChangedListenerOf_widget_3;
		_widget_3.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_3;
		_widget_3.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_3;
		_widget_4.PropertyChanged -= PropertyChangedListenerOf_widget_4;
		_widget_4.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_4;
		_widget_4.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_4;
		_widget_4.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_4;
		_widget_4.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_4;
		_widget_4.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_4;
		_widget_4.intPropertyChanged -= intPropertyChangedListenerOf_widget_4;
		_widget_4.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_4;
		_widget_4.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_4;
		_widget_5.PropertyChanged -= PropertyChangedListenerOf_widget_5;
		_widget_5.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_5;
		_widget_5.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_5;
		_widget_5.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_5;
		_widget_5.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_5;
		_widget_5.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_5;
		_widget_5.intPropertyChanged -= intPropertyChangedListenerOf_widget_5;
		_widget_5.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_5;
		_widget_5.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_5;
		_widget_6.PropertyChanged -= PropertyChangedListenerOf_widget_6;
		_widget_6.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_6;
		_widget_6.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_6;
		_widget_6.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_6;
		_widget_6.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_6;
		_widget_6.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_6;
		_widget_6.intPropertyChanged -= intPropertyChangedListenerOf_widget_6;
		_widget_6.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_6;
		_widget_6.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_6;
		_widget_7.PropertyChanged -= PropertyChangedListenerOf_widget_7;
		_widget_7.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_7;
		_widget_7.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_7;
		_widget_7.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_7;
		_widget_7.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_7;
		_widget_7.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_7;
		_widget_7.intPropertyChanged -= intPropertyChangedListenerOf_widget_7;
		_widget_7.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_7;
		_widget_7.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_7;
		if (_datasource_Root_Banner_9 != null)
		{
			_datasource_Root_Banner_9.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_Banner_9;
			_datasource_Root_Banner_9.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Banner_9;
			_datasource_Root_Banner_9.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Banner_9;
			_datasource_Root_Banner_9.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Banner_9;
			_datasource_Root_Banner_9.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Banner_9;
			_datasource_Root_Banner_9.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Banner_9;
			_datasource_Root_Banner_9.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Banner_9;
			_datasource_Root_Banner_9.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Banner_9;
			_datasource_Root_Banner_9.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Banner_9;
			_widget_0_1.PropertyChanged -= PropertyChangedListenerOf_widget_0_1;
			_widget_0_1.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_1;
			_widget_0_1.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_1;
			_widget_0_1.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_1;
			_widget_0_1.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_1;
			_widget_0_1.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_1;
			_widget_0_1.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_1;
			_widget_0_1.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_1;
			_widget_0_1.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_1;
			_datasource_Root_Banner_9 = null;
		}
		if (_datasource_Root_Visual != null)
		{
			_datasource_Root_Visual.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Visual;
			_widget_0_2.PropertyChanged -= PropertyChangedListenerOf_widget_0_2;
			_widget_0_2.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_2;
			_widget_0_2.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_2;
			_widget_0_2.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_2;
			_widget_0_2.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_2;
			_widget_0_2.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_2;
			_widget_0_2.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_2;
			_widget_0_2.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_2;
			_widget_0_2.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_2;
			_datasource_Root_Visual = null;
		}
		if (_datasource_Root_Quests != null)
		{
			_datasource_Root_Quests.ListChanged -= OnList_datasource_Root_QuestsChanged;
			for (int num = _widget_0_3.ChildCount - 1; num >= 0; num--)
			{
				Widget child = _widget_0_3.GetChild(num);
				((SettlementOverlay__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_Overlay_SettlementMenuOverlayVM_Dependency_12_ItemTemplate)child).OnBeforeRemovedChild(child);
				((SettlementOverlay__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_Overlay_SettlementMenuOverlayVM_Dependency_12_ItemTemplate)_widget_0_3.GetChild(num)).DestroyDataSource();
			}
			_datasource_Root_Quests = null;
		}
		_datasource_Root = null;
	}

	public virtual void SetDataSource(GameMenuPartyItemVM dataSource)
	{
		RefreshDataSource_datasource_Root(dataSource);
	}

	private void EventListenerOf_widget(Widget widget, string commandName, object[] args)
	{
		if (commandName == "AlternateClick")
		{
			_datasource_Root.ExecuteOpenEncyclopedia();
		}
		if (commandName == "Click")
		{
			_datasource_Root.ExecuteSetAsContextMenuItem();
		}
		if (commandName == "HoverBegin")
		{
			_datasource_Root.ExecuteOpenTooltip();
		}
		if (commandName == "HoverEnd")
		{
			_datasource_Root.ExecuteCloseTooltip();
		}
	}

	private void PropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void intPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget(string propertyName)
	{
		switch (propertyName)
		{
		case "Description":
			_datasource_Root.DescriptionText = _widget.Description;
			break;
		case "Location":
			_datasource_Root.LocationText = _widget.Location;
			break;
		case "Power":
			_datasource_Root.PowerText = _widget.Power;
			break;
		case "Name":
			_datasource_Root.NameText = _widget.Name;
			break;
		case "Profession":
			_datasource_Root.ProfessionText = _widget.Profession;
			break;
		case "Relation":
			_datasource_Root.Relation = _widget.Relation;
			break;
		}
	}

	private void PropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_1(string propertyName)
	{
		if (propertyName == "IsVisible")
		{
			_datasource_Root.IsCharacterInPrison = _widget_1.IsVisible;
		}
	}

	private void PropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_2(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_2(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_2(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_2(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_2(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_2(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_2(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_2(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_2(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_2(string propertyName)
	{
		if (propertyName == "Text")
		{
			_datasource_Root.PartySizeLbl = _widget_2.Text;
		}
	}

	private void PropertyChangedListenerOf_widget_3(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_3(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_3(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_3(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_3(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_3(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_3(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_3(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_3(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_3(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_3(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_3(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_3(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_3(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_3(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_3(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_3(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_3(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_3(string propertyName)
	{
		if (propertyName == "Text")
		{
			_datasource_Root.NameText = _widget_3.Text;
		}
		else if (propertyName == "IsVisible")
		{
			_datasource_Root.IsNeutral = _widget_3.IsVisible;
		}
	}

	private void PropertyChangedListenerOf_widget_4(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_4(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_4(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_4(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_4(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_4(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_4(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_4(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_4(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_4(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_4(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_4(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_4(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_4(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_4(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_4(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_4(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_4(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_4(string propertyName)
	{
		if (propertyName == "Text")
		{
			_datasource_Root.NameText = _widget_4.Text;
		}
		else if (propertyName == "IsVisible")
		{
			_datasource_Root.IsPlayer = _widget_4.IsVisible;
		}
	}

	private void PropertyChangedListenerOf_widget_5(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_5(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_5(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_5(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_5(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_5(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_5(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_5(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_5(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_5(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_5(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_5(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_5(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_5(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_5(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_5(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_5(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_5(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_5(string propertyName)
	{
		if (propertyName == "Text")
		{
			_datasource_Root.NameText = _widget_5.Text;
		}
		else if (propertyName == "IsVisible")
		{
			_datasource_Root.IsEnemy = _widget_5.IsVisible;
		}
	}

	private void PropertyChangedListenerOf_widget_6(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_6(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_6(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_6(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_6(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_6(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_6(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_6(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_6(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_6(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_6(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_6(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_6(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_6(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_6(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_6(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_6(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_6(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_6(string propertyName)
	{
		if (propertyName == "Text")
		{
			_datasource_Root.NameText = _widget_6.Text;
		}
		else if (propertyName == "IsVisible")
		{
			_datasource_Root.IsAlly = _widget_6.IsVisible;
		}
	}

	private void PropertyChangedListenerOf_widget_7(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_7(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_7(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_7(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_7(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_7(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_7(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_7(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_7(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_7(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_7(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_7(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_7(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_7(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_7(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_7(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_7(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_7(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_7(string propertyName)
	{
		if (propertyName == "IsHighlightEnabled")
		{
			_datasource_Root.IsHighlightEnabled = _widget_7.IsHighlightEnabled;
		}
	}

	private void PropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_0_1(string propertyName)
	{
		if (!(propertyName == "AdditionalArgs") && !(propertyName == "ImageId"))
		{
			_ = propertyName == "ImageTypeCode";
		}
	}

	private void PropertyChangedListenerOf_widget_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_0_2(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_0_2(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_0_2(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_2(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_2(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_0_2(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_0_2(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_0_2(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_0_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_0_2(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_0_2(string propertyName)
	{
		if (!(propertyName == "AdditionalArgs") && !(propertyName == "ImageId"))
		{
			_ = propertyName == "ImageTypeCode";
		}
	}

	private void ViewModelPropertyChangedListenerOf_datasource_Root(object sender, PropertyChangedEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root(object sender, PropertyChangedWithValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root(object sender, PropertyChangedWithBoolValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root(object sender, PropertyChangedWithFloatValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithUIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root(object sender, PropertyChangedWithColorValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root(object sender, PropertyChangedWithDoubleValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root(object sender, PropertyChangedWithVec2ValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void HandleViewModelPropertyChangeOf_datasource_Root(string propertyName)
	{
		switch (propertyName)
		{
		case "Banner_9":
			RefreshDataSource_datasource_Root_Banner_9(_datasource_Root.Banner_9);
			break;
		case "Visual":
			RefreshDataSource_datasource_Root_Visual(_datasource_Root.Visual);
			break;
		case "Quests":
			RefreshDataSource_datasource_Root_Quests(_datasource_Root.Quests);
			break;
		case "DescriptionText":
			_widget.Description = _datasource_Root.DescriptionText;
			break;
		case "LocationText":
			_widget.Location = _datasource_Root.LocationText;
			break;
		case "PowerText":
			_widget.Power = _datasource_Root.PowerText;
			break;
		case "NameText":
			_widget.Name = _datasource_Root.NameText;
			_widget_3.Text = _datasource_Root.NameText;
			_widget_4.Text = _datasource_Root.NameText;
			_widget_5.Text = _datasource_Root.NameText;
			_widget_6.Text = _datasource_Root.NameText;
			break;
		case "ProfessionText":
			_widget.Profession = _datasource_Root.ProfessionText;
			break;
		case "Relation":
			_widget.Relation = _datasource_Root.Relation;
			break;
		case "IsCharacterInPrison":
			_widget_1.IsVisible = _datasource_Root.IsCharacterInPrison;
			break;
		case "PartySizeLbl":
			_widget_2.Text = _datasource_Root.PartySizeLbl;
			break;
		case "IsNeutral":
			_widget_3.IsVisible = _datasource_Root.IsNeutral;
			break;
		case "IsPlayer":
			_widget_4.IsVisible = _datasource_Root.IsPlayer;
			break;
		case "IsEnemy":
			_widget_5.IsVisible = _datasource_Root.IsEnemy;
			break;
		case "IsAlly":
			_widget_6.IsVisible = _datasource_Root.IsAlly;
			break;
		case "IsHighlightEnabled":
			_widget_7.IsHighlightEnabled = _datasource_Root.IsHighlightEnabled;
			break;
		}
	}

	private void ViewModelPropertyChangedListenerOf_datasource_Root_Banner_9(object sender, PropertyChangedEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Banner_9(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Banner_9(object sender, PropertyChangedWithValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Banner_9(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Banner_9(object sender, PropertyChangedWithBoolValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Banner_9(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Banner_9(object sender, PropertyChangedWithIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Banner_9(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Banner_9(object sender, PropertyChangedWithFloatValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Banner_9(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Banner_9(object sender, PropertyChangedWithUIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Banner_9(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Banner_9(object sender, PropertyChangedWithColorValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Banner_9(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Banner_9(object sender, PropertyChangedWithDoubleValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Banner_9(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Banner_9(object sender, PropertyChangedWithVec2ValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Banner_9(e.PropertyName);
	}

	private void HandleViewModelPropertyChangeOf_datasource_Root_Banner_9(string propertyName)
	{
		switch (propertyName)
		{
		case "AdditionalArgs":
			_widget_0_1.AdditionalArgs = _datasource_Root_Banner_9.AdditionalArgs;
			break;
		case "Id":
			_widget_0_1.ImageId = _datasource_Root_Banner_9.Id;
			break;
		case "ImageTypeCode":
			_widget_0_1.ImageTypeCode = _datasource_Root_Banner_9.ImageTypeCode;
			break;
		}
	}

	private void ViewModelPropertyChangedListenerOf_datasource_Root_Visual(object sender, PropertyChangedEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Visual(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Visual(object sender, PropertyChangedWithValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Visual(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Visual(object sender, PropertyChangedWithBoolValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Visual(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Visual(object sender, PropertyChangedWithIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Visual(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Visual(object sender, PropertyChangedWithFloatValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Visual(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Visual(object sender, PropertyChangedWithUIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Visual(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Visual(object sender, PropertyChangedWithColorValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Visual(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Visual(object sender, PropertyChangedWithDoubleValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Visual(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Visual(object sender, PropertyChangedWithVec2ValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Visual(e.PropertyName);
	}

	private void HandleViewModelPropertyChangeOf_datasource_Root_Visual(string propertyName)
	{
		switch (propertyName)
		{
		case "AdditionalArgs":
			_widget_0_2.AdditionalArgs = _datasource_Root_Visual.AdditionalArgs;
			break;
		case "Id":
			_widget_0_2.ImageId = _datasource_Root_Visual.Id;
			break;
		case "ImageTypeCode":
			_widget_0_2.ImageTypeCode = _datasource_Root_Visual.ImageTypeCode;
			break;
		}
	}

	public void OnList_datasource_Root_QuestsChanged(object sender, TaleWorlds.Library.ListChangedEventArgs e)
	{
		switch (e.ListChangedType)
		{
		case TaleWorlds.Library.ListChangedType.Reset:
		{
			for (int num = _widget_0_3.ChildCount - 1; num >= 0; num--)
			{
				Widget child3 = _widget_0_3.GetChild(num);
				((SettlementOverlay__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_Overlay_SettlementMenuOverlayVM_Dependency_12_ItemTemplate)child3).OnBeforeRemovedChild(child3);
				Widget child4 = _widget_0_3.GetChild(num);
				((SettlementOverlay__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_Overlay_SettlementMenuOverlayVM_Dependency_12_ItemTemplate)child4).SetDataSource(null);
				_widget_0_3.RemoveChild(child4);
			}
			break;
		}
		case TaleWorlds.Library.ListChangedType.Sorted:
		{
			for (int i = 0; i < _datasource_Root_Quests.Count; i++)
			{
				QuestMarkerVM bindingObject = _datasource_Root_Quests[i];
				_widget_0_3.FindChild((Widget widget) => widget.GetComponent<GeneratedWidgetData>().Data == bindingObject).SetSiblingIndex(i);
			}
			break;
		}
		case TaleWorlds.Library.ListChangedType.ItemAdded:
		{
			SettlementOverlay__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_Overlay_SettlementMenuOverlayVM_Dependency_12_ItemTemplate settlementOverlay__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_Overlay_SettlementMenuOverlayVM_Dependency_12_ItemTemplate = new SettlementOverlay__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_Overlay_SettlementMenuOverlayVM_Dependency_12_ItemTemplate(base.Context);
			GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(settlementOverlay__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_Overlay_SettlementMenuOverlayVM_Dependency_12_ItemTemplate);
			QuestMarkerVM dataSource = (QuestMarkerVM)(generatedWidgetData.Data = _datasource_Root_Quests[e.NewIndex]);
			settlementOverlay__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_Overlay_SettlementMenuOverlayVM_Dependency_12_ItemTemplate.AddComponent(generatedWidgetData);
			_widget_0_3.AddChildAtIndex(settlementOverlay__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_Overlay_SettlementMenuOverlayVM_Dependency_12_ItemTemplate, e.NewIndex);
			settlementOverlay__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_Overlay_SettlementMenuOverlayVM_Dependency_12_ItemTemplate.CreateWidgets();
			settlementOverlay__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_Overlay_SettlementMenuOverlayVM_Dependency_12_ItemTemplate.SetIds();
			settlementOverlay__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_Overlay_SettlementMenuOverlayVM_Dependency_12_ItemTemplate.SetAttributes();
			settlementOverlay__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_Overlay_SettlementMenuOverlayVM_Dependency_12_ItemTemplate.SetDataSource(dataSource);
			break;
		}
		case TaleWorlds.Library.ListChangedType.ItemBeforeDeleted:
		{
			Widget child2 = _widget_0_3.GetChild(e.NewIndex);
			((SettlementOverlay__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_Overlay_SettlementMenuOverlayVM_Dependency_12_ItemTemplate)child2).OnBeforeRemovedChild(child2);
			break;
		}
		case TaleWorlds.Library.ListChangedType.ItemDeleted:
		{
			Widget child = _widget_0_3.GetChild(e.NewIndex);
			((SettlementOverlay__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_Overlay_SettlementMenuOverlayVM_Dependency_12_ItemTemplate)child).SetDataSource(null);
			_widget_0_3.RemoveChild(child);
			break;
		}
		case TaleWorlds.Library.ListChangedType.ItemChanged:
			break;
		}
	}

	private void RefreshDataSource_datasource_Root(GameMenuPartyItemVM newDataSource)
	{
		if (_datasource_Root != null)
		{
			_datasource_Root.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
			_widget.EventFire -= EventListenerOf_widget;
			_widget.PropertyChanged -= PropertyChangedListenerOf_widget;
			_widget.boolPropertyChanged -= boolPropertyChangedListenerOf_widget;
			_widget.floatPropertyChanged -= floatPropertyChangedListenerOf_widget;
			_widget.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget;
			_widget.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget;
			_widget.doublePropertyChanged -= doublePropertyChangedListenerOf_widget;
			_widget.intPropertyChanged -= intPropertyChangedListenerOf_widget;
			_widget.uintPropertyChanged -= uintPropertyChangedListenerOf_widget;
			_widget.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget;
			_widget_1.PropertyChanged -= PropertyChangedListenerOf_widget_1;
			_widget_1.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_1;
			_widget_1.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_1;
			_widget_1.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_1;
			_widget_1.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_1;
			_widget_1.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_1;
			_widget_1.intPropertyChanged -= intPropertyChangedListenerOf_widget_1;
			_widget_1.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_1;
			_widget_1.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_1;
			_widget_2.PropertyChanged -= PropertyChangedListenerOf_widget_2;
			_widget_2.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_2;
			_widget_2.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_2;
			_widget_2.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_2;
			_widget_2.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_2;
			_widget_2.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_2;
			_widget_2.intPropertyChanged -= intPropertyChangedListenerOf_widget_2;
			_widget_2.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_2;
			_widget_2.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_2;
			_widget_3.PropertyChanged -= PropertyChangedListenerOf_widget_3;
			_widget_3.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_3;
			_widget_3.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_3;
			_widget_3.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_3;
			_widget_3.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_3;
			_widget_3.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_3;
			_widget_3.intPropertyChanged -= intPropertyChangedListenerOf_widget_3;
			_widget_3.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_3;
			_widget_3.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_3;
			_widget_4.PropertyChanged -= PropertyChangedListenerOf_widget_4;
			_widget_4.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_4;
			_widget_4.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_4;
			_widget_4.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_4;
			_widget_4.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_4;
			_widget_4.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_4;
			_widget_4.intPropertyChanged -= intPropertyChangedListenerOf_widget_4;
			_widget_4.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_4;
			_widget_4.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_4;
			_widget_5.PropertyChanged -= PropertyChangedListenerOf_widget_5;
			_widget_5.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_5;
			_widget_5.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_5;
			_widget_5.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_5;
			_widget_5.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_5;
			_widget_5.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_5;
			_widget_5.intPropertyChanged -= intPropertyChangedListenerOf_widget_5;
			_widget_5.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_5;
			_widget_5.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_5;
			_widget_6.PropertyChanged -= PropertyChangedListenerOf_widget_6;
			_widget_6.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_6;
			_widget_6.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_6;
			_widget_6.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_6;
			_widget_6.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_6;
			_widget_6.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_6;
			_widget_6.intPropertyChanged -= intPropertyChangedListenerOf_widget_6;
			_widget_6.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_6;
			_widget_6.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_6;
			_widget_7.PropertyChanged -= PropertyChangedListenerOf_widget_7;
			_widget_7.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_7;
			_widget_7.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_7;
			_widget_7.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_7;
			_widget_7.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_7;
			_widget_7.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_7;
			_widget_7.intPropertyChanged -= intPropertyChangedListenerOf_widget_7;
			_widget_7.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_7;
			_widget_7.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_7;
			if (_datasource_Root_Banner_9 != null)
			{
				_datasource_Root_Banner_9.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_Banner_9;
				_datasource_Root_Banner_9.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Banner_9;
				_datasource_Root_Banner_9.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Banner_9;
				_datasource_Root_Banner_9.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Banner_9;
				_datasource_Root_Banner_9.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Banner_9;
				_datasource_Root_Banner_9.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Banner_9;
				_datasource_Root_Banner_9.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Banner_9;
				_datasource_Root_Banner_9.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Banner_9;
				_datasource_Root_Banner_9.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Banner_9;
				_widget_0_1.PropertyChanged -= PropertyChangedListenerOf_widget_0_1;
				_widget_0_1.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_1;
				_widget_0_1.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_1;
				_widget_0_1.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_1;
				_widget_0_1.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_1;
				_widget_0_1.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_1;
				_widget_0_1.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_1;
				_widget_0_1.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_1;
				_widget_0_1.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_1;
				_datasource_Root_Banner_9 = null;
			}
			if (_datasource_Root_Visual != null)
			{
				_datasource_Root_Visual.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_Visual;
				_datasource_Root_Visual.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Visual;
				_datasource_Root_Visual.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Visual;
				_datasource_Root_Visual.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Visual;
				_datasource_Root_Visual.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Visual;
				_datasource_Root_Visual.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Visual;
				_datasource_Root_Visual.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Visual;
				_datasource_Root_Visual.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Visual;
				_datasource_Root_Visual.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Visual;
				_widget_0_2.PropertyChanged -= PropertyChangedListenerOf_widget_0_2;
				_widget_0_2.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_2;
				_widget_0_2.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_2;
				_widget_0_2.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_2;
				_widget_0_2.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_2;
				_widget_0_2.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_2;
				_widget_0_2.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_2;
				_widget_0_2.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_2;
				_widget_0_2.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_2;
				_datasource_Root_Visual = null;
			}
			if (_datasource_Root_Quests != null)
			{
				_datasource_Root_Quests.ListChanged -= OnList_datasource_Root_QuestsChanged;
				for (int num = _widget_0_3.ChildCount - 1; num >= 0; num--)
				{
					Widget child = _widget_0_3.GetChild(num);
					((SettlementOverlay__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_Overlay_SettlementMenuOverlayVM_Dependency_12_ItemTemplate)child).OnBeforeRemovedChild(child);
					Widget child2 = _widget_0_3.GetChild(num);
					((SettlementOverlay__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_Overlay_SettlementMenuOverlayVM_Dependency_12_ItemTemplate)child2).SetDataSource(null);
					_widget_0_3.RemoveChild(child2);
				}
				_datasource_Root_Quests = null;
			}
			_datasource_Root = null;
		}
		_datasource_Root = newDataSource;
		if (_datasource_Root == null)
		{
			return;
		}
		_datasource_Root.PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithValue += ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithBoolValue += ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithIntValue += ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithFloatValue += ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithUIntValue += ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithColorValue += ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithDoubleValue += ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithVec2Value += ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
		_widget.Description = _datasource_Root.DescriptionText;
		_widget.Location = _datasource_Root.LocationText;
		_widget.Power = _datasource_Root.PowerText;
		_widget.Name = _datasource_Root.NameText;
		_widget.Profession = _datasource_Root.ProfessionText;
		_widget.Relation = _datasource_Root.Relation;
		_widget.EventFire += EventListenerOf_widget;
		_widget.PropertyChanged += PropertyChangedListenerOf_widget;
		_widget.boolPropertyChanged += boolPropertyChangedListenerOf_widget;
		_widget.floatPropertyChanged += floatPropertyChangedListenerOf_widget;
		_widget.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget;
		_widget.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget;
		_widget.doublePropertyChanged += doublePropertyChangedListenerOf_widget;
		_widget.intPropertyChanged += intPropertyChangedListenerOf_widget;
		_widget.uintPropertyChanged += uintPropertyChangedListenerOf_widget;
		_widget.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget;
		_widget_1.IsVisible = _datasource_Root.IsCharacterInPrison;
		_widget_1.PropertyChanged += PropertyChangedListenerOf_widget_1;
		_widget_1.boolPropertyChanged += boolPropertyChangedListenerOf_widget_1;
		_widget_1.floatPropertyChanged += floatPropertyChangedListenerOf_widget_1;
		_widget_1.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_1;
		_widget_1.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_1;
		_widget_1.doublePropertyChanged += doublePropertyChangedListenerOf_widget_1;
		_widget_1.intPropertyChanged += intPropertyChangedListenerOf_widget_1;
		_widget_1.uintPropertyChanged += uintPropertyChangedListenerOf_widget_1;
		_widget_1.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_1;
		_widget_2.Text = _datasource_Root.PartySizeLbl;
		_widget_2.PropertyChanged += PropertyChangedListenerOf_widget_2;
		_widget_2.boolPropertyChanged += boolPropertyChangedListenerOf_widget_2;
		_widget_2.floatPropertyChanged += floatPropertyChangedListenerOf_widget_2;
		_widget_2.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_2;
		_widget_2.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_2;
		_widget_2.doublePropertyChanged += doublePropertyChangedListenerOf_widget_2;
		_widget_2.intPropertyChanged += intPropertyChangedListenerOf_widget_2;
		_widget_2.uintPropertyChanged += uintPropertyChangedListenerOf_widget_2;
		_widget_2.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_2;
		_widget_3.Text = _datasource_Root.NameText;
		_widget_3.IsVisible = _datasource_Root.IsNeutral;
		_widget_3.PropertyChanged += PropertyChangedListenerOf_widget_3;
		_widget_3.boolPropertyChanged += boolPropertyChangedListenerOf_widget_3;
		_widget_3.floatPropertyChanged += floatPropertyChangedListenerOf_widget_3;
		_widget_3.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_3;
		_widget_3.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_3;
		_widget_3.doublePropertyChanged += doublePropertyChangedListenerOf_widget_3;
		_widget_3.intPropertyChanged += intPropertyChangedListenerOf_widget_3;
		_widget_3.uintPropertyChanged += uintPropertyChangedListenerOf_widget_3;
		_widget_3.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_3;
		_widget_4.Text = _datasource_Root.NameText;
		_widget_4.IsVisible = _datasource_Root.IsPlayer;
		_widget_4.PropertyChanged += PropertyChangedListenerOf_widget_4;
		_widget_4.boolPropertyChanged += boolPropertyChangedListenerOf_widget_4;
		_widget_4.floatPropertyChanged += floatPropertyChangedListenerOf_widget_4;
		_widget_4.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_4;
		_widget_4.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_4;
		_widget_4.doublePropertyChanged += doublePropertyChangedListenerOf_widget_4;
		_widget_4.intPropertyChanged += intPropertyChangedListenerOf_widget_4;
		_widget_4.uintPropertyChanged += uintPropertyChangedListenerOf_widget_4;
		_widget_4.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_4;
		_widget_5.Text = _datasource_Root.NameText;
		_widget_5.IsVisible = _datasource_Root.IsEnemy;
		_widget_5.PropertyChanged += PropertyChangedListenerOf_widget_5;
		_widget_5.boolPropertyChanged += boolPropertyChangedListenerOf_widget_5;
		_widget_5.floatPropertyChanged += floatPropertyChangedListenerOf_widget_5;
		_widget_5.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_5;
		_widget_5.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_5;
		_widget_5.doublePropertyChanged += doublePropertyChangedListenerOf_widget_5;
		_widget_5.intPropertyChanged += intPropertyChangedListenerOf_widget_5;
		_widget_5.uintPropertyChanged += uintPropertyChangedListenerOf_widget_5;
		_widget_5.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_5;
		_widget_6.Text = _datasource_Root.NameText;
		_widget_6.IsVisible = _datasource_Root.IsAlly;
		_widget_6.PropertyChanged += PropertyChangedListenerOf_widget_6;
		_widget_6.boolPropertyChanged += boolPropertyChangedListenerOf_widget_6;
		_widget_6.floatPropertyChanged += floatPropertyChangedListenerOf_widget_6;
		_widget_6.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_6;
		_widget_6.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_6;
		_widget_6.doublePropertyChanged += doublePropertyChangedListenerOf_widget_6;
		_widget_6.intPropertyChanged += intPropertyChangedListenerOf_widget_6;
		_widget_6.uintPropertyChanged += uintPropertyChangedListenerOf_widget_6;
		_widget_6.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_6;
		_widget_7.IsHighlightEnabled = _datasource_Root.IsHighlightEnabled;
		_widget_7.PropertyChanged += PropertyChangedListenerOf_widget_7;
		_widget_7.boolPropertyChanged += boolPropertyChangedListenerOf_widget_7;
		_widget_7.floatPropertyChanged += floatPropertyChangedListenerOf_widget_7;
		_widget_7.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_7;
		_widget_7.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_7;
		_widget_7.doublePropertyChanged += doublePropertyChangedListenerOf_widget_7;
		_widget_7.intPropertyChanged += intPropertyChangedListenerOf_widget_7;
		_widget_7.uintPropertyChanged += uintPropertyChangedListenerOf_widget_7;
		_widget_7.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_7;
		_datasource_Root_Banner_9 = _datasource_Root.Banner_9;
		if (_datasource_Root_Banner_9 != null)
		{
			_datasource_Root_Banner_9.PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root_Banner_9;
			_datasource_Root_Banner_9.PropertyChangedWithValue += ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Banner_9;
			_datasource_Root_Banner_9.PropertyChangedWithBoolValue += ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Banner_9;
			_datasource_Root_Banner_9.PropertyChangedWithIntValue += ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Banner_9;
			_datasource_Root_Banner_9.PropertyChangedWithFloatValue += ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Banner_9;
			_datasource_Root_Banner_9.PropertyChangedWithUIntValue += ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Banner_9;
			_datasource_Root_Banner_9.PropertyChangedWithColorValue += ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Banner_9;
			_datasource_Root_Banner_9.PropertyChangedWithDoubleValue += ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Banner_9;
			_datasource_Root_Banner_9.PropertyChangedWithVec2Value += ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Banner_9;
			_widget_0_1.AdditionalArgs = _datasource_Root_Banner_9.AdditionalArgs;
			_widget_0_1.ImageId = _datasource_Root_Banner_9.Id;
			_widget_0_1.ImageTypeCode = _datasource_Root_Banner_9.ImageTypeCode;
			_widget_0_1.PropertyChanged += PropertyChangedListenerOf_widget_0_1;
			_widget_0_1.boolPropertyChanged += boolPropertyChangedListenerOf_widget_0_1;
			_widget_0_1.floatPropertyChanged += floatPropertyChangedListenerOf_widget_0_1;
			_widget_0_1.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_0_1;
			_widget_0_1.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_0_1;
			_widget_0_1.doublePropertyChanged += doublePropertyChangedListenerOf_widget_0_1;
			_widget_0_1.intPropertyChanged += intPropertyChangedListenerOf_widget_0_1;
			_widget_0_1.uintPropertyChanged += uintPropertyChangedListenerOf_widget_0_1;
			_widget_0_1.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_0_1;
		}
		_datasource_Root_Visual = _datasource_Root.Visual;
		if (_datasource_Root_Visual != null)
		{
			_datasource_Root_Visual.PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithValue += ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithBoolValue += ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithIntValue += ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithFloatValue += ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithUIntValue += ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithColorValue += ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithDoubleValue += ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithVec2Value += ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Visual;
			_widget_0_2.AdditionalArgs = _datasource_Root_Visual.AdditionalArgs;
			_widget_0_2.ImageId = _datasource_Root_Visual.Id;
			_widget_0_2.ImageTypeCode = _datasource_Root_Visual.ImageTypeCode;
			_widget_0_2.PropertyChanged += PropertyChangedListenerOf_widget_0_2;
			_widget_0_2.boolPropertyChanged += boolPropertyChangedListenerOf_widget_0_2;
			_widget_0_2.floatPropertyChanged += floatPropertyChangedListenerOf_widget_0_2;
			_widget_0_2.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_0_2;
			_widget_0_2.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_0_2;
			_widget_0_2.doublePropertyChanged += doublePropertyChangedListenerOf_widget_0_2;
			_widget_0_2.intPropertyChanged += intPropertyChangedListenerOf_widget_0_2;
			_widget_0_2.uintPropertyChanged += uintPropertyChangedListenerOf_widget_0_2;
			_widget_0_2.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_0_2;
		}
		_datasource_Root_Quests = _datasource_Root.Quests;
		if (_datasource_Root_Quests != null)
		{
			_datasource_Root_Quests.ListChanged += OnList_datasource_Root_QuestsChanged;
			for (int i = 0; i < _datasource_Root_Quests.Count; i++)
			{
				SettlementOverlay__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_Overlay_SettlementMenuOverlayVM_Dependency_12_ItemTemplate settlementOverlay__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_Overlay_SettlementMenuOverlayVM_Dependency_12_ItemTemplate = new SettlementOverlay__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_Overlay_SettlementMenuOverlayVM_Dependency_12_ItemTemplate(base.Context);
				GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(settlementOverlay__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_Overlay_SettlementMenuOverlayVM_Dependency_12_ItemTemplate);
				QuestMarkerVM dataSource = (QuestMarkerVM)(generatedWidgetData.Data = _datasource_Root_Quests[i]);
				settlementOverlay__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_Overlay_SettlementMenuOverlayVM_Dependency_12_ItemTemplate.AddComponent(generatedWidgetData);
				_widget_0_3.AddChildAtIndex(settlementOverlay__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_Overlay_SettlementMenuOverlayVM_Dependency_12_ItemTemplate, i);
				settlementOverlay__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_Overlay_SettlementMenuOverlayVM_Dependency_12_ItemTemplate.CreateWidgets();
				settlementOverlay__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_Overlay_SettlementMenuOverlayVM_Dependency_12_ItemTemplate.SetIds();
				settlementOverlay__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_Overlay_SettlementMenuOverlayVM_Dependency_12_ItemTemplate.SetAttributes();
				settlementOverlay__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_Overlay_SettlementMenuOverlayVM_Dependency_12_ItemTemplate.SetDataSource(dataSource);
			}
		}
	}

	private void RefreshDataSource_datasource_Root_Banner_9(ImageIdentifierVM newDataSource)
	{
		if (_datasource_Root_Banner_9 != null)
		{
			_datasource_Root_Banner_9.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_Banner_9;
			_datasource_Root_Banner_9.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Banner_9;
			_datasource_Root_Banner_9.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Banner_9;
			_datasource_Root_Banner_9.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Banner_9;
			_datasource_Root_Banner_9.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Banner_9;
			_datasource_Root_Banner_9.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Banner_9;
			_datasource_Root_Banner_9.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Banner_9;
			_datasource_Root_Banner_9.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Banner_9;
			_datasource_Root_Banner_9.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Banner_9;
			_widget_0_1.PropertyChanged -= PropertyChangedListenerOf_widget_0_1;
			_widget_0_1.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_1;
			_widget_0_1.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_1;
			_widget_0_1.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_1;
			_widget_0_1.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_1;
			_widget_0_1.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_1;
			_widget_0_1.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_1;
			_widget_0_1.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_1;
			_widget_0_1.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_1;
			_datasource_Root_Banner_9 = null;
		}
		_datasource_Root_Banner_9 = newDataSource;
		_datasource_Root_Banner_9 = _datasource_Root.Banner_9;
		if (_datasource_Root_Banner_9 != null)
		{
			_datasource_Root_Banner_9.PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root_Banner_9;
			_datasource_Root_Banner_9.PropertyChangedWithValue += ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Banner_9;
			_datasource_Root_Banner_9.PropertyChangedWithBoolValue += ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Banner_9;
			_datasource_Root_Banner_9.PropertyChangedWithIntValue += ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Banner_9;
			_datasource_Root_Banner_9.PropertyChangedWithFloatValue += ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Banner_9;
			_datasource_Root_Banner_9.PropertyChangedWithUIntValue += ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Banner_9;
			_datasource_Root_Banner_9.PropertyChangedWithColorValue += ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Banner_9;
			_datasource_Root_Banner_9.PropertyChangedWithDoubleValue += ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Banner_9;
			_datasource_Root_Banner_9.PropertyChangedWithVec2Value += ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Banner_9;
			_widget_0_1.AdditionalArgs = _datasource_Root_Banner_9.AdditionalArgs;
			_widget_0_1.ImageId = _datasource_Root_Banner_9.Id;
			_widget_0_1.ImageTypeCode = _datasource_Root_Banner_9.ImageTypeCode;
			_widget_0_1.PropertyChanged += PropertyChangedListenerOf_widget_0_1;
			_widget_0_1.boolPropertyChanged += boolPropertyChangedListenerOf_widget_0_1;
			_widget_0_1.floatPropertyChanged += floatPropertyChangedListenerOf_widget_0_1;
			_widget_0_1.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_0_1;
			_widget_0_1.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_0_1;
			_widget_0_1.doublePropertyChanged += doublePropertyChangedListenerOf_widget_0_1;
			_widget_0_1.intPropertyChanged += intPropertyChangedListenerOf_widget_0_1;
			_widget_0_1.uintPropertyChanged += uintPropertyChangedListenerOf_widget_0_1;
			_widget_0_1.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_0_1;
		}
	}

	private void RefreshDataSource_datasource_Root_Visual(ImageIdentifierVM newDataSource)
	{
		if (_datasource_Root_Visual != null)
		{
			_datasource_Root_Visual.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Visual;
			_widget_0_2.PropertyChanged -= PropertyChangedListenerOf_widget_0_2;
			_widget_0_2.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_2;
			_widget_0_2.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_2;
			_widget_0_2.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_2;
			_widget_0_2.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_2;
			_widget_0_2.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_2;
			_widget_0_2.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_2;
			_widget_0_2.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_2;
			_widget_0_2.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_2;
			_datasource_Root_Visual = null;
		}
		_datasource_Root_Visual = newDataSource;
		_datasource_Root_Visual = _datasource_Root.Visual;
		if (_datasource_Root_Visual != null)
		{
			_datasource_Root_Visual.PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithValue += ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithBoolValue += ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithIntValue += ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithFloatValue += ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithUIntValue += ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithColorValue += ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithDoubleValue += ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Visual;
			_datasource_Root_Visual.PropertyChangedWithVec2Value += ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Visual;
			_widget_0_2.AdditionalArgs = _datasource_Root_Visual.AdditionalArgs;
			_widget_0_2.ImageId = _datasource_Root_Visual.Id;
			_widget_0_2.ImageTypeCode = _datasource_Root_Visual.ImageTypeCode;
			_widget_0_2.PropertyChanged += PropertyChangedListenerOf_widget_0_2;
			_widget_0_2.boolPropertyChanged += boolPropertyChangedListenerOf_widget_0_2;
			_widget_0_2.floatPropertyChanged += floatPropertyChangedListenerOf_widget_0_2;
			_widget_0_2.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_0_2;
			_widget_0_2.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_0_2;
			_widget_0_2.doublePropertyChanged += doublePropertyChangedListenerOf_widget_0_2;
			_widget_0_2.intPropertyChanged += intPropertyChangedListenerOf_widget_0_2;
			_widget_0_2.uintPropertyChanged += uintPropertyChangedListenerOf_widget_0_2;
			_widget_0_2.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_0_2;
		}
	}

	private void RefreshDataSource_datasource_Root_Quests(MBBindingList<QuestMarkerVM> newDataSource)
	{
		if (_datasource_Root_Quests != null)
		{
			_datasource_Root_Quests.ListChanged -= OnList_datasource_Root_QuestsChanged;
			for (int num = _widget_0_3.ChildCount - 1; num >= 0; num--)
			{
				Widget child = _widget_0_3.GetChild(num);
				((SettlementOverlay__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_Overlay_SettlementMenuOverlayVM_Dependency_12_ItemTemplate)child).OnBeforeRemovedChild(child);
				Widget child2 = _widget_0_3.GetChild(num);
				((SettlementOverlay__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_Overlay_SettlementMenuOverlayVM_Dependency_12_ItemTemplate)child2).SetDataSource(null);
				_widget_0_3.RemoveChild(child2);
			}
			_datasource_Root_Quests = null;
		}
		_datasource_Root_Quests = newDataSource;
		_datasource_Root_Quests = _datasource_Root.Quests;
		if (_datasource_Root_Quests != null)
		{
			_datasource_Root_Quests.ListChanged += OnList_datasource_Root_QuestsChanged;
			for (int i = 0; i < _datasource_Root_Quests.Count; i++)
			{
				SettlementOverlay__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_Overlay_SettlementMenuOverlayVM_Dependency_12_ItemTemplate settlementOverlay__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_Overlay_SettlementMenuOverlayVM_Dependency_12_ItemTemplate = new SettlementOverlay__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_Overlay_SettlementMenuOverlayVM_Dependency_12_ItemTemplate(base.Context);
				GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(settlementOverlay__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_Overlay_SettlementMenuOverlayVM_Dependency_12_ItemTemplate);
				QuestMarkerVM dataSource = (QuestMarkerVM)(generatedWidgetData.Data = _datasource_Root_Quests[i]);
				settlementOverlay__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_Overlay_SettlementMenuOverlayVM_Dependency_12_ItemTemplate.AddComponent(generatedWidgetData);
				_widget_0_3.AddChildAtIndex(settlementOverlay__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_Overlay_SettlementMenuOverlayVM_Dependency_12_ItemTemplate, i);
				settlementOverlay__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_Overlay_SettlementMenuOverlayVM_Dependency_12_ItemTemplate.CreateWidgets();
				settlementOverlay__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_Overlay_SettlementMenuOverlayVM_Dependency_12_ItemTemplate.SetIds();
				settlementOverlay__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_Overlay_SettlementMenuOverlayVM_Dependency_12_ItemTemplate.SetAttributes();
				settlementOverlay__TaleWorlds_CampaignSystem_ViewModelCollection_GameMenu_Overlay_SettlementMenuOverlayVM_Dependency_12_ItemTemplate.SetDataSource(dataSource);
			}
		}
	}
}
