using System.ComponentModel;
using System.Numerics;
using TaleWorlds.CampaignSystem.ViewModelCollection.Inventory;
using TaleWorlds.Core;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.GauntletUI.Data;
using TaleWorlds.Library;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets.Inventory;

namespace SandBox.GauntletUI.AutoGenerated1;

public class Inventory__TaleWorlds_CampaignSystem_ViewModelCollection_Inventory_SPInventoryVM_Dependency_4_InventoryEquippedItemSlot__DependendPrefab : Widget
{
	private Widget _widget;

	private BrushWidget _widget_0;

	private HintWidget _widget_0_0;

	private InventoryEquippedItemSlotWidget _widget_1;

	private Widget _widget_1_0;

	private ImageIdentifierWidget _widget_1_1;

	private Inventory__TaleWorlds_CampaignSystem_ViewModelCollection_Inventory_SPInventoryVM_Dependency_22_Standard_CircleLoadingWidget__DependendPrefab _widget_1_1_0;

	private SPInventoryVM _datasource_Root;

	private SPItemVM _datasource_Root_CharacterCloakSlot;

	private ImageIdentifierVM _datasource_Root_CharacterCloakSlot_ImageIdentifier;

	public Inventory__TaleWorlds_CampaignSystem_ViewModelCollection_Inventory_SPInventoryVM_Dependency_4_InventoryEquippedItemSlot__DependendPrefab(UIContext context)
		: base(context)
	{
	}

	public void CreateWidgets()
	{
		_widget = this;
		_widget_0 = new BrushWidget(base.Context);
		_widget.AddChild(_widget_0);
		_widget_0_0 = new HintWidget(base.Context);
		_widget_0.AddChild(_widget_0_0);
		_widget_1 = new InventoryEquippedItemSlotWidget(base.Context);
		GeneratedWidgetData component = new GeneratedWidgetData(_widget_1);
		_widget_1.AddComponent(component);
		_widget.AddChild(_widget_1);
		_widget_1_0 = new Widget(base.Context);
		_widget_1.AddChild(_widget_1_0);
		_widget_1_1 = new ImageIdentifierWidget(base.Context);
		_widget_1.AddChild(_widget_1_1);
		_widget_1_1_0 = new Inventory__TaleWorlds_CampaignSystem_ViewModelCollection_Inventory_SPInventoryVM_Dependency_22_Standard_CircleLoadingWidget__DependendPrefab(base.Context);
		_widget_1_1.AddChild(_widget_1_1_0);
		_widget_1_1_0.CreateWidgets();
	}

	public void SetIds()
	{
		_widget_0.Id = "Background";
		_widget_1_1.Id = "ImageIdentifier";
		_widget_1_1_0.SetIds();
		_widget_1_1_0.Id = "LoadingIconWidget";
	}

	public void SetAttributes()
	{
		base.WidthSizePolicy = SizePolicy.Fixed;
		base.HeightSizePolicy = SizePolicy.Fixed;
		base.SuggestedWidth = 130f;
		base.SuggestedHeight = 65f;
		_widget_0.AcceptDrop = true;
		_widget_0.WidthSizePolicy = SizePolicy.StretchToParent;
		_widget_0.HeightSizePolicy = SizePolicy.StretchToParent;
		_widget_0.Brush = base.Context.GetBrush("InventoryCloakSlot");
		_widget_0_0.IsDisabled = true;
		_widget_0_0.WidthSizePolicy = SizePolicy.StretchToParent;
		_widget_0_0.HeightSizePolicy = SizePolicy.StretchToParent;
		_widget_1.IsRightSide = false;
		_widget_1.TargetEquipmentIndex = 9;
		_widget_1.AcceptDrag = true;
		_widget_1.DoNotPassEventsToChildren = true;
		_widget_1.WidthSizePolicy = SizePolicy.StretchToParent;
		_widget_1.HeightSizePolicy = SizePolicy.StretchToParent;
		_widget_1.Background = _widget_0;
		_widget_1.ImageIdentifier = _widget_1_1;
		_widget_1_0.WidthSizePolicy = SizePolicy.StretchToParent;
		_widget_1_0.HeightSizePolicy = SizePolicy.StretchToParent;
		_widget_1_0.MarginLeft = 3f;
		_widget_1_0.MarginRight = 4f;
		_widget_1_0.MarginTop = 3f;
		_widget_1_0.MarginBottom = 4f;
		_widget_1_0.Sprite = base.Context.SpriteData.GetSprite("Inventory\\portrait_cart");
		_widget_1_1.WidthSizePolicy = SizePolicy.StretchToParent;
		_widget_1_1.HeightSizePolicy = SizePolicy.StretchToParent;
		_widget_1_1.MarginLeft = 3f;
		_widget_1_1.MarginRight = 4f;
		_widget_1_1.MarginTop = 3f;
		_widget_1_1.MarginBottom = 4f;
		_widget_1_1.LoadingIconWidget = _widget_1_1_0;
		_widget_1_1_0.SetAttributes();
		_widget_1_1_0.HorizontalAlignment = HorizontalAlignment.Center;
		_widget_1_1_0.VerticalAlignment = VerticalAlignment.Center;
	}

	public void DestroyDataSource()
	{
		if (_datasource_Root == null)
		{
			return;
		}
		_datasource_Root.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
		_widget_0.EventFire -= EventListenerOf_widget_0;
		_widget_0_0.EventFire -= EventListenerOf_widget_0_0;
		if (_datasource_Root_CharacterCloakSlot != null)
		{
			_widget_1.GetComponent<GeneratedWidgetData>().Data = null;
			_datasource_Root_CharacterCloakSlot.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_CharacterCloakSlot;
			_datasource_Root_CharacterCloakSlot.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_CharacterCloakSlot;
			_datasource_Root_CharacterCloakSlot.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_CharacterCloakSlot;
			_datasource_Root_CharacterCloakSlot.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_CharacterCloakSlot;
			_datasource_Root_CharacterCloakSlot.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_CharacterCloakSlot;
			_datasource_Root_CharacterCloakSlot.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_CharacterCloakSlot;
			_datasource_Root_CharacterCloakSlot.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_CharacterCloakSlot;
			_datasource_Root_CharacterCloakSlot.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_CharacterCloakSlot;
			_datasource_Root_CharacterCloakSlot.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_CharacterCloakSlot;
			_widget_1.EventFire -= EventListenerOf_widget_1;
			_widget_1.PropertyChanged -= PropertyChangedListenerOf_widget_1;
			_widget_1.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_1;
			_widget_1.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_1;
			_widget_1.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_1;
			_widget_1.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_1;
			_widget_1.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_1;
			_widget_1.intPropertyChanged -= intPropertyChangedListenerOf_widget_1;
			_widget_1.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_1;
			_widget_1.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_1;
			if (_datasource_Root_CharacterCloakSlot_ImageIdentifier != null)
			{
				_widget_1_1_0.DestroyDataSource();
				_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
				_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
				_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
				_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
				_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
				_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
				_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
				_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
				_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
				_widget_1_1.PropertyChanged -= PropertyChangedListenerOf_widget_1_1;
				_widget_1_1.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_1_1;
				_widget_1_1.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_1_1;
				_widget_1_1.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_1_1;
				_widget_1_1.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_1_1;
				_widget_1_1.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_1_1;
				_widget_1_1.intPropertyChanged -= intPropertyChangedListenerOf_widget_1_1;
				_widget_1_1.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_1_1;
				_widget_1_1.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_1_1;
				_datasource_Root_CharacterCloakSlot_ImageIdentifier = null;
			}
			_datasource_Root_CharacterCloakSlot = null;
		}
		_datasource_Root = null;
	}

	public void SetDataSource(SPInventoryVM dataSource)
	{
		RefreshDataSource_datasource_Root(dataSource);
	}

	private void EventListenerOf_widget_0(Widget widget, string commandName, object[] args)
	{
		if (commandName == "Drop")
		{
			SPItemVM item = null;
			GeneratedWidgetData component = ((Widget)args[0]).GetComponent<GeneratedWidgetData>();
			if (component != null)
			{
				item = (SPItemVM)component.Data;
			}
			int index = (int)args[1];
			string targetTag = "Equipment_9";
			_datasource_Root.ExecuteTransferWithParameters(item, index, targetTag);
		}
	}

	private void EventListenerOf_widget_0_0(Widget widget, string commandName, object[] args)
	{
		_ = commandName == "HoverBegin";
		_ = commandName == "HoverEnd";
	}

	private void EventListenerOf_widget_1(Widget widget, string commandName, object[] args)
	{
		if (commandName == "PreviewItem")
		{
			_datasource_Root_CharacterCloakSlot.ExecutePreviewItem();
		}
		if (commandName == "SellItem")
		{
			_datasource_Root_CharacterCloakSlot.ExecuteSellSingle();
		}
		if (commandName == "UnequipItem")
		{
			_datasource_Root_CharacterCloakSlot.ExecuteUnequipItem();
		}
	}

	private void PropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_1(string propertyName)
	{
		if (propertyName == "ItemType")
		{
			_datasource_Root_CharacterCloakSlot.TypeId = _widget_1.ItemType;
		}
	}

	private void PropertyChangedListenerOf_widget_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_1_1(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_1_1(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_1_1(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_1_1(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_1_1(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_1_1(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_1_1(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_1_1(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_1_1(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_1_1(string propertyName)
	{
		if (!(propertyName == "ImageId") && !(propertyName == "AdditionalArgs"))
		{
			_ = propertyName == "ImageTypeCode";
		}
	}

	private void ViewModelPropertyChangedListenerOf_datasource_Root(object sender, PropertyChangedEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root(object sender, PropertyChangedWithValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root(object sender, PropertyChangedWithBoolValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root(object sender, PropertyChangedWithFloatValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithUIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root(object sender, PropertyChangedWithColorValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root(object sender, PropertyChangedWithDoubleValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root(object sender, PropertyChangedWithVec2ValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void HandleViewModelPropertyChangeOf_datasource_Root(string propertyName)
	{
		if (propertyName == "CharacterCloakSlot")
		{
			RefreshDataSource_datasource_Root_CharacterCloakSlot(_datasource_Root.CharacterCloakSlot);
		}
	}

	private void ViewModelPropertyChangedListenerOf_datasource_Root_CharacterCloakSlot(object sender, PropertyChangedEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_CharacterCloakSlot(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root_CharacterCloakSlot(object sender, PropertyChangedWithValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_CharacterCloakSlot(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_CharacterCloakSlot(object sender, PropertyChangedWithBoolValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_CharacterCloakSlot(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_CharacterCloakSlot(object sender, PropertyChangedWithIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_CharacterCloakSlot(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_CharacterCloakSlot(object sender, PropertyChangedWithFloatValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_CharacterCloakSlot(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_CharacterCloakSlot(object sender, PropertyChangedWithUIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_CharacterCloakSlot(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_CharacterCloakSlot(object sender, PropertyChangedWithColorValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_CharacterCloakSlot(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_CharacterCloakSlot(object sender, PropertyChangedWithDoubleValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_CharacterCloakSlot(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_CharacterCloakSlot(object sender, PropertyChangedWithVec2ValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_CharacterCloakSlot(e.PropertyName);
	}

	private void HandleViewModelPropertyChangeOf_datasource_Root_CharacterCloakSlot(string propertyName)
	{
		if (propertyName == "ImageIdentifier")
		{
			RefreshDataSource_datasource_Root_CharacterCloakSlot_ImageIdentifier(_datasource_Root_CharacterCloakSlot.ImageIdentifier);
		}
		else if (propertyName == "TypeId")
		{
			_widget_1.ItemType = _datasource_Root_CharacterCloakSlot.TypeId;
		}
	}

	private void ViewModelPropertyChangedListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier(object sender, PropertyChangedEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_CharacterCloakSlot_ImageIdentifier(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier(object sender, PropertyChangedWithValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_CharacterCloakSlot_ImageIdentifier(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier(object sender, PropertyChangedWithBoolValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_CharacterCloakSlot_ImageIdentifier(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier(object sender, PropertyChangedWithIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_CharacterCloakSlot_ImageIdentifier(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier(object sender, PropertyChangedWithFloatValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_CharacterCloakSlot_ImageIdentifier(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier(object sender, PropertyChangedWithUIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_CharacterCloakSlot_ImageIdentifier(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier(object sender, PropertyChangedWithColorValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_CharacterCloakSlot_ImageIdentifier(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier(object sender, PropertyChangedWithDoubleValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_CharacterCloakSlot_ImageIdentifier(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier(object sender, PropertyChangedWithVec2ValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_CharacterCloakSlot_ImageIdentifier(e.PropertyName);
	}

	private void HandleViewModelPropertyChangeOf_datasource_Root_CharacterCloakSlot_ImageIdentifier(string propertyName)
	{
		switch (propertyName)
		{
		case "Id":
			_widget_1_1.ImageId = _datasource_Root_CharacterCloakSlot_ImageIdentifier.Id;
			break;
		case "AdditionalArgs":
			_widget_1_1.AdditionalArgs = _datasource_Root_CharacterCloakSlot_ImageIdentifier.AdditionalArgs;
			break;
		case "ImageTypeCode":
			_widget_1_1.ImageTypeCode = _datasource_Root_CharacterCloakSlot_ImageIdentifier.ImageTypeCode;
			break;
		}
	}

	private void RefreshDataSource_datasource_Root(SPInventoryVM newDataSource)
	{
		if (_datasource_Root != null)
		{
			_datasource_Root.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
			_widget_0.EventFire -= EventListenerOf_widget_0;
			_widget_0_0.EventFire -= EventListenerOf_widget_0_0;
			if (_datasource_Root_CharacterCloakSlot != null)
			{
				_widget_1.GetComponent<GeneratedWidgetData>().Data = null;
				_datasource_Root_CharacterCloakSlot.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_CharacterCloakSlot;
				_datasource_Root_CharacterCloakSlot.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_CharacterCloakSlot;
				_datasource_Root_CharacterCloakSlot.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_CharacterCloakSlot;
				_datasource_Root_CharacterCloakSlot.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_CharacterCloakSlot;
				_datasource_Root_CharacterCloakSlot.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_CharacterCloakSlot;
				_datasource_Root_CharacterCloakSlot.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_CharacterCloakSlot;
				_datasource_Root_CharacterCloakSlot.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_CharacterCloakSlot;
				_datasource_Root_CharacterCloakSlot.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_CharacterCloakSlot;
				_datasource_Root_CharacterCloakSlot.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_CharacterCloakSlot;
				_widget_1.EventFire -= EventListenerOf_widget_1;
				_widget_1.PropertyChanged -= PropertyChangedListenerOf_widget_1;
				_widget_1.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_1;
				_widget_1.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_1;
				_widget_1.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_1;
				_widget_1.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_1;
				_widget_1.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_1;
				_widget_1.intPropertyChanged -= intPropertyChangedListenerOf_widget_1;
				_widget_1.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_1;
				_widget_1.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_1;
				if (_datasource_Root_CharacterCloakSlot_ImageIdentifier != null)
				{
					_widget_1_1_0.SetDataSource(null);
					_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
					_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
					_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
					_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
					_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
					_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
					_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
					_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
					_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
					_widget_1_1.PropertyChanged -= PropertyChangedListenerOf_widget_1_1;
					_widget_1_1.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_1_1;
					_widget_1_1.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_1_1;
					_widget_1_1.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_1_1;
					_widget_1_1.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_1_1;
					_widget_1_1.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_1_1;
					_widget_1_1.intPropertyChanged -= intPropertyChangedListenerOf_widget_1_1;
					_widget_1_1.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_1_1;
					_widget_1_1.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_1_1;
					_datasource_Root_CharacterCloakSlot_ImageIdentifier = null;
				}
				_datasource_Root_CharacterCloakSlot = null;
			}
			_datasource_Root = null;
		}
		_datasource_Root = newDataSource;
		if (_datasource_Root == null)
		{
			return;
		}
		_datasource_Root.PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithValue += ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithBoolValue += ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithIntValue += ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithFloatValue += ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithUIntValue += ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithColorValue += ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithDoubleValue += ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithVec2Value += ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
		_widget_0.EventFire += EventListenerOf_widget_0;
		_widget_0_0.EventFire += EventListenerOf_widget_0_0;
		_datasource_Root_CharacterCloakSlot = _datasource_Root.CharacterCloakSlot;
		if (_datasource_Root_CharacterCloakSlot != null)
		{
			_datasource_Root_CharacterCloakSlot.PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root_CharacterCloakSlot;
			_datasource_Root_CharacterCloakSlot.PropertyChangedWithValue += ViewModelPropertyChangedWithValueListenerOf_datasource_Root_CharacterCloakSlot;
			_datasource_Root_CharacterCloakSlot.PropertyChangedWithBoolValue += ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_CharacterCloakSlot;
			_datasource_Root_CharacterCloakSlot.PropertyChangedWithIntValue += ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_CharacterCloakSlot;
			_datasource_Root_CharacterCloakSlot.PropertyChangedWithFloatValue += ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_CharacterCloakSlot;
			_datasource_Root_CharacterCloakSlot.PropertyChangedWithUIntValue += ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_CharacterCloakSlot;
			_datasource_Root_CharacterCloakSlot.PropertyChangedWithColorValue += ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_CharacterCloakSlot;
			_datasource_Root_CharacterCloakSlot.PropertyChangedWithDoubleValue += ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_CharacterCloakSlot;
			_datasource_Root_CharacterCloakSlot.PropertyChangedWithVec2Value += ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_CharacterCloakSlot;
			_widget_1.ItemType = _datasource_Root_CharacterCloakSlot.TypeId;
			_widget_1.GetComponent<GeneratedWidgetData>().Data = _datasource_Root_CharacterCloakSlot;
			_widget_1.EventFire += EventListenerOf_widget_1;
			_widget_1.PropertyChanged += PropertyChangedListenerOf_widget_1;
			_widget_1.boolPropertyChanged += boolPropertyChangedListenerOf_widget_1;
			_widget_1.floatPropertyChanged += floatPropertyChangedListenerOf_widget_1;
			_widget_1.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_1;
			_widget_1.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_1;
			_widget_1.doublePropertyChanged += doublePropertyChangedListenerOf_widget_1;
			_widget_1.intPropertyChanged += intPropertyChangedListenerOf_widget_1;
			_widget_1.uintPropertyChanged += uintPropertyChangedListenerOf_widget_1;
			_widget_1.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_1;
			_datasource_Root_CharacterCloakSlot_ImageIdentifier = _datasource_Root_CharacterCloakSlot.ImageIdentifier;
			if (_datasource_Root_CharacterCloakSlot_ImageIdentifier != null)
			{
				_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
				_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChangedWithValue += ViewModelPropertyChangedWithValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
				_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChangedWithBoolValue += ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
				_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChangedWithIntValue += ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
				_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChangedWithFloatValue += ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
				_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChangedWithUIntValue += ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
				_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChangedWithColorValue += ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
				_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChangedWithDoubleValue += ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
				_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChangedWithVec2Value += ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
				_widget_1_1.ImageId = _datasource_Root_CharacterCloakSlot_ImageIdentifier.Id;
				_widget_1_1.AdditionalArgs = _datasource_Root_CharacterCloakSlot_ImageIdentifier.AdditionalArgs;
				_widget_1_1.ImageTypeCode = _datasource_Root_CharacterCloakSlot_ImageIdentifier.ImageTypeCode;
				_widget_1_1.PropertyChanged += PropertyChangedListenerOf_widget_1_1;
				_widget_1_1.boolPropertyChanged += boolPropertyChangedListenerOf_widget_1_1;
				_widget_1_1.floatPropertyChanged += floatPropertyChangedListenerOf_widget_1_1;
				_widget_1_1.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_1_1;
				_widget_1_1.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_1_1;
				_widget_1_1.doublePropertyChanged += doublePropertyChangedListenerOf_widget_1_1;
				_widget_1_1.intPropertyChanged += intPropertyChangedListenerOf_widget_1_1;
				_widget_1_1.uintPropertyChanged += uintPropertyChangedListenerOf_widget_1_1;
				_widget_1_1.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_1_1;
				_widget_1_1_0.SetDataSource(_datasource_Root_CharacterCloakSlot_ImageIdentifier);
			}
		}
	}

	private void RefreshDataSource_datasource_Root_CharacterCloakSlot(SPItemVM newDataSource)
	{
		if (_datasource_Root_CharacterCloakSlot != null)
		{
			_widget_1.GetComponent<GeneratedWidgetData>().Data = null;
			_datasource_Root_CharacterCloakSlot.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_CharacterCloakSlot;
			_datasource_Root_CharacterCloakSlot.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_CharacterCloakSlot;
			_datasource_Root_CharacterCloakSlot.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_CharacterCloakSlot;
			_datasource_Root_CharacterCloakSlot.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_CharacterCloakSlot;
			_datasource_Root_CharacterCloakSlot.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_CharacterCloakSlot;
			_datasource_Root_CharacterCloakSlot.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_CharacterCloakSlot;
			_datasource_Root_CharacterCloakSlot.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_CharacterCloakSlot;
			_datasource_Root_CharacterCloakSlot.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_CharacterCloakSlot;
			_datasource_Root_CharacterCloakSlot.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_CharacterCloakSlot;
			_widget_1.EventFire -= EventListenerOf_widget_1;
			_widget_1.PropertyChanged -= PropertyChangedListenerOf_widget_1;
			_widget_1.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_1;
			_widget_1.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_1;
			_widget_1.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_1;
			_widget_1.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_1;
			_widget_1.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_1;
			_widget_1.intPropertyChanged -= intPropertyChangedListenerOf_widget_1;
			_widget_1.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_1;
			_widget_1.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_1;
			if (_datasource_Root_CharacterCloakSlot_ImageIdentifier != null)
			{
				_widget_1_1_0.SetDataSource(null);
				_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
				_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
				_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
				_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
				_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
				_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
				_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
				_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
				_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
				_widget_1_1.PropertyChanged -= PropertyChangedListenerOf_widget_1_1;
				_widget_1_1.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_1_1;
				_widget_1_1.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_1_1;
				_widget_1_1.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_1_1;
				_widget_1_1.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_1_1;
				_widget_1_1.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_1_1;
				_widget_1_1.intPropertyChanged -= intPropertyChangedListenerOf_widget_1_1;
				_widget_1_1.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_1_1;
				_widget_1_1.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_1_1;
				_datasource_Root_CharacterCloakSlot_ImageIdentifier = null;
			}
			_datasource_Root_CharacterCloakSlot = null;
		}
		_datasource_Root_CharacterCloakSlot = newDataSource;
		_datasource_Root_CharacterCloakSlot = _datasource_Root.CharacterCloakSlot;
		if (_datasource_Root_CharacterCloakSlot != null)
		{
			_datasource_Root_CharacterCloakSlot.PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root_CharacterCloakSlot;
			_datasource_Root_CharacterCloakSlot.PropertyChangedWithValue += ViewModelPropertyChangedWithValueListenerOf_datasource_Root_CharacterCloakSlot;
			_datasource_Root_CharacterCloakSlot.PropertyChangedWithBoolValue += ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_CharacterCloakSlot;
			_datasource_Root_CharacterCloakSlot.PropertyChangedWithIntValue += ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_CharacterCloakSlot;
			_datasource_Root_CharacterCloakSlot.PropertyChangedWithFloatValue += ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_CharacterCloakSlot;
			_datasource_Root_CharacterCloakSlot.PropertyChangedWithUIntValue += ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_CharacterCloakSlot;
			_datasource_Root_CharacterCloakSlot.PropertyChangedWithColorValue += ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_CharacterCloakSlot;
			_datasource_Root_CharacterCloakSlot.PropertyChangedWithDoubleValue += ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_CharacterCloakSlot;
			_datasource_Root_CharacterCloakSlot.PropertyChangedWithVec2Value += ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_CharacterCloakSlot;
			_widget_1.ItemType = _datasource_Root_CharacterCloakSlot.TypeId;
			_widget_1.GetComponent<GeneratedWidgetData>().Data = _datasource_Root_CharacterCloakSlot;
			_widget_1.EventFire += EventListenerOf_widget_1;
			_widget_1.PropertyChanged += PropertyChangedListenerOf_widget_1;
			_widget_1.boolPropertyChanged += boolPropertyChangedListenerOf_widget_1;
			_widget_1.floatPropertyChanged += floatPropertyChangedListenerOf_widget_1;
			_widget_1.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_1;
			_widget_1.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_1;
			_widget_1.doublePropertyChanged += doublePropertyChangedListenerOf_widget_1;
			_widget_1.intPropertyChanged += intPropertyChangedListenerOf_widget_1;
			_widget_1.uintPropertyChanged += uintPropertyChangedListenerOf_widget_1;
			_widget_1.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_1;
			_datasource_Root_CharacterCloakSlot_ImageIdentifier = _datasource_Root_CharacterCloakSlot.ImageIdentifier;
			if (_datasource_Root_CharacterCloakSlot_ImageIdentifier != null)
			{
				_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
				_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChangedWithValue += ViewModelPropertyChangedWithValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
				_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChangedWithBoolValue += ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
				_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChangedWithIntValue += ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
				_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChangedWithFloatValue += ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
				_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChangedWithUIntValue += ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
				_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChangedWithColorValue += ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
				_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChangedWithDoubleValue += ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
				_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChangedWithVec2Value += ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
				_widget_1_1.ImageId = _datasource_Root_CharacterCloakSlot_ImageIdentifier.Id;
				_widget_1_1.AdditionalArgs = _datasource_Root_CharacterCloakSlot_ImageIdentifier.AdditionalArgs;
				_widget_1_1.ImageTypeCode = _datasource_Root_CharacterCloakSlot_ImageIdentifier.ImageTypeCode;
				_widget_1_1.PropertyChanged += PropertyChangedListenerOf_widget_1_1;
				_widget_1_1.boolPropertyChanged += boolPropertyChangedListenerOf_widget_1_1;
				_widget_1_1.floatPropertyChanged += floatPropertyChangedListenerOf_widget_1_1;
				_widget_1_1.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_1_1;
				_widget_1_1.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_1_1;
				_widget_1_1.doublePropertyChanged += doublePropertyChangedListenerOf_widget_1_1;
				_widget_1_1.intPropertyChanged += intPropertyChangedListenerOf_widget_1_1;
				_widget_1_1.uintPropertyChanged += uintPropertyChangedListenerOf_widget_1_1;
				_widget_1_1.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_1_1;
				_widget_1_1_0.SetDataSource(_datasource_Root_CharacterCloakSlot_ImageIdentifier);
			}
		}
	}

	private void RefreshDataSource_datasource_Root_CharacterCloakSlot_ImageIdentifier(ImageIdentifierVM newDataSource)
	{
		if (_datasource_Root_CharacterCloakSlot_ImageIdentifier != null)
		{
			_widget_1_1_0.SetDataSource(null);
			_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
			_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
			_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
			_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
			_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
			_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
			_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
			_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
			_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
			_widget_1_1.PropertyChanged -= PropertyChangedListenerOf_widget_1_1;
			_widget_1_1.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_1_1;
			_widget_1_1.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_1_1;
			_widget_1_1.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_1_1;
			_widget_1_1.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_1_1;
			_widget_1_1.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_1_1;
			_widget_1_1.intPropertyChanged -= intPropertyChangedListenerOf_widget_1_1;
			_widget_1_1.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_1_1;
			_widget_1_1.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_1_1;
			_datasource_Root_CharacterCloakSlot_ImageIdentifier = null;
		}
		_datasource_Root_CharacterCloakSlot_ImageIdentifier = newDataSource;
		_datasource_Root_CharacterCloakSlot_ImageIdentifier = _datasource_Root_CharacterCloakSlot.ImageIdentifier;
		if (_datasource_Root_CharacterCloakSlot_ImageIdentifier != null)
		{
			_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
			_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChangedWithValue += ViewModelPropertyChangedWithValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
			_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChangedWithBoolValue += ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
			_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChangedWithIntValue += ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
			_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChangedWithFloatValue += ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
			_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChangedWithUIntValue += ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
			_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChangedWithColorValue += ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
			_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChangedWithDoubleValue += ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
			_datasource_Root_CharacterCloakSlot_ImageIdentifier.PropertyChangedWithVec2Value += ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_CharacterCloakSlot_ImageIdentifier;
			_widget_1_1.ImageId = _datasource_Root_CharacterCloakSlot_ImageIdentifier.Id;
			_widget_1_1.AdditionalArgs = _datasource_Root_CharacterCloakSlot_ImageIdentifier.AdditionalArgs;
			_widget_1_1.ImageTypeCode = _datasource_Root_CharacterCloakSlot_ImageIdentifier.ImageTypeCode;
			_widget_1_1.PropertyChanged += PropertyChangedListenerOf_widget_1_1;
			_widget_1_1.boolPropertyChanged += boolPropertyChangedListenerOf_widget_1_1;
			_widget_1_1.floatPropertyChanged += floatPropertyChangedListenerOf_widget_1_1;
			_widget_1_1.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_1_1;
			_widget_1_1.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_1_1;
			_widget_1_1.doublePropertyChanged += doublePropertyChangedListenerOf_widget_1_1;
			_widget_1_1.intPropertyChanged += intPropertyChangedListenerOf_widget_1_1;
			_widget_1_1.uintPropertyChanged += uintPropertyChangedListenerOf_widget_1_1;
			_widget_1_1.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_1_1;
			_widget_1_1_0.SetDataSource(_datasource_Root_CharacterCloakSlot_ImageIdentifier);
		}
	}
}
