using System.ComponentModel;
using SandBox.ViewModelCollection.Map;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.GauntletUI.Data;
using TaleWorlds.Library;

namespace SandBox.GauntletUI.AutoGenerated1;

public class MapMobilePartyTracker__SandBox_ViewModelCollection_Map_MapMobilePartyTrackerVM : Widget, IGeneratedGauntletMovieRoot
{
	private Widget _widget;

	private Widget _widget_0;

	private MapMobilePartyTrackerVM _datasource_Root;

	private MBBindingList<MobilePartyTrackItemVM> _datasource_Root_Trackers;

	public MapMobilePartyTracker__SandBox_ViewModelCollection_Map_MapMobilePartyTrackerVM(UIContext context)
		: base(context)
	{
	}

	public void CreateWidgets()
	{
		_widget = this;
		_widget_0 = new Widget(base.Context);
		_widget.AddChild(_widget_0);
	}

	public void SetIds()
	{
	}

	public void SetAttributes()
	{
		base.HeightSizePolicy = SizePolicy.StretchToParent;
		base.WidthSizePolicy = SizePolicy.StretchToParent;
		base.DoNotAcceptEvents = true;
		_widget_0.HeightSizePolicy = SizePolicy.StretchToParent;
		_widget_0.WidthSizePolicy = SizePolicy.StretchToParent;
		_widget_0.DoNotAcceptEvents = true;
	}

	public void RefreshBindingWithChildren()
	{
		MapMobilePartyTrackerVM datasource_Root = _datasource_Root;
		SetDataSource(null);
		SetDataSource(datasource_Root);
	}

	public void DestroyDataSource()
	{
		if (_datasource_Root == null)
		{
			return;
		}
		_datasource_Root.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
		if (_datasource_Root_Trackers != null)
		{
			_datasource_Root_Trackers.ListChanged -= OnList_datasource_Root_TrackersChanged;
			for (int num = _widget_0.ChildCount - 1; num >= 0; num--)
			{
				Widget child = _widget_0.GetChild(num);
				((MapMobilePartyTracker__SandBox_ViewModelCollection_Map_MapMobilePartyTrackerVM_Dependency_1_ItemTemplate)child).OnBeforeRemovedChild(child);
				((MapMobilePartyTracker__SandBox_ViewModelCollection_Map_MapMobilePartyTrackerVM_Dependency_1_ItemTemplate)_widget_0.GetChild(num)).DestroyDataSource();
			}
			_datasource_Root_Trackers = null;
		}
		_datasource_Root = null;
	}

	public void SetDataSource(MapMobilePartyTrackerVM dataSource)
	{
		RefreshDataSource_datasource_Root(dataSource);
	}

	private void ViewModelPropertyChangedListenerOf_datasource_Root(object sender, PropertyChangedEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root(object sender, PropertyChangedWithValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root(object sender, PropertyChangedWithBoolValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root(object sender, PropertyChangedWithFloatValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithUIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root(object sender, PropertyChangedWithColorValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root(object sender, PropertyChangedWithDoubleValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root(object sender, PropertyChangedWithVec2ValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void HandleViewModelPropertyChangeOf_datasource_Root(string propertyName)
	{
		if (propertyName == "Trackers")
		{
			RefreshDataSource_datasource_Root_Trackers(_datasource_Root.Trackers);
		}
	}

	public void OnList_datasource_Root_TrackersChanged(object sender, TaleWorlds.Library.ListChangedEventArgs e)
	{
		switch (e.ListChangedType)
		{
		case TaleWorlds.Library.ListChangedType.Reset:
		{
			for (int num = _widget_0.ChildCount - 1; num >= 0; num--)
			{
				Widget child3 = _widget_0.GetChild(num);
				((MapMobilePartyTracker__SandBox_ViewModelCollection_Map_MapMobilePartyTrackerVM_Dependency_1_ItemTemplate)child3).OnBeforeRemovedChild(child3);
				Widget child4 = _widget_0.GetChild(num);
				((MapMobilePartyTracker__SandBox_ViewModelCollection_Map_MapMobilePartyTrackerVM_Dependency_1_ItemTemplate)child4).SetDataSource(null);
				_widget_0.RemoveChild(child4);
			}
			break;
		}
		case TaleWorlds.Library.ListChangedType.Sorted:
		{
			for (int i = 0; i < _datasource_Root_Trackers.Count; i++)
			{
				MobilePartyTrackItemVM bindingObject = _datasource_Root_Trackers[i];
				_widget_0.FindChild((Widget widget) => widget.GetComponent<GeneratedWidgetData>().Data == bindingObject).SetSiblingIndex(i);
			}
			break;
		}
		case TaleWorlds.Library.ListChangedType.ItemAdded:
		{
			MapMobilePartyTracker__SandBox_ViewModelCollection_Map_MapMobilePartyTrackerVM_Dependency_1_ItemTemplate mapMobilePartyTracker__SandBox_ViewModelCollection_Map_MapMobilePartyTrackerVM_Dependency_1_ItemTemplate = new MapMobilePartyTracker__SandBox_ViewModelCollection_Map_MapMobilePartyTrackerVM_Dependency_1_ItemTemplate(base.Context);
			GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(mapMobilePartyTracker__SandBox_ViewModelCollection_Map_MapMobilePartyTrackerVM_Dependency_1_ItemTemplate);
			MobilePartyTrackItemVM dataSource = (MobilePartyTrackItemVM)(generatedWidgetData.Data = _datasource_Root_Trackers[e.NewIndex]);
			mapMobilePartyTracker__SandBox_ViewModelCollection_Map_MapMobilePartyTrackerVM_Dependency_1_ItemTemplate.AddComponent(generatedWidgetData);
			_widget_0.AddChildAtIndex(mapMobilePartyTracker__SandBox_ViewModelCollection_Map_MapMobilePartyTrackerVM_Dependency_1_ItemTemplate, e.NewIndex);
			mapMobilePartyTracker__SandBox_ViewModelCollection_Map_MapMobilePartyTrackerVM_Dependency_1_ItemTemplate.CreateWidgets();
			mapMobilePartyTracker__SandBox_ViewModelCollection_Map_MapMobilePartyTrackerVM_Dependency_1_ItemTemplate.SetIds();
			mapMobilePartyTracker__SandBox_ViewModelCollection_Map_MapMobilePartyTrackerVM_Dependency_1_ItemTemplate.SetAttributes();
			mapMobilePartyTracker__SandBox_ViewModelCollection_Map_MapMobilePartyTrackerVM_Dependency_1_ItemTemplate.SetDataSource(dataSource);
			break;
		}
		case TaleWorlds.Library.ListChangedType.ItemBeforeDeleted:
		{
			Widget child2 = _widget_0.GetChild(e.NewIndex);
			((MapMobilePartyTracker__SandBox_ViewModelCollection_Map_MapMobilePartyTrackerVM_Dependency_1_ItemTemplate)child2).OnBeforeRemovedChild(child2);
			break;
		}
		case TaleWorlds.Library.ListChangedType.ItemDeleted:
		{
			Widget child = _widget_0.GetChild(e.NewIndex);
			((MapMobilePartyTracker__SandBox_ViewModelCollection_Map_MapMobilePartyTrackerVM_Dependency_1_ItemTemplate)child).SetDataSource(null);
			_widget_0.RemoveChild(child);
			break;
		}
		case TaleWorlds.Library.ListChangedType.ItemChanged:
			break;
		}
	}

	private void RefreshDataSource_datasource_Root(MapMobilePartyTrackerVM newDataSource)
	{
		if (_datasource_Root != null)
		{
			_datasource_Root.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
			if (_datasource_Root_Trackers != null)
			{
				_datasource_Root_Trackers.ListChanged -= OnList_datasource_Root_TrackersChanged;
				for (int num = _widget_0.ChildCount - 1; num >= 0; num--)
				{
					Widget child = _widget_0.GetChild(num);
					((MapMobilePartyTracker__SandBox_ViewModelCollection_Map_MapMobilePartyTrackerVM_Dependency_1_ItemTemplate)child).OnBeforeRemovedChild(child);
					Widget child2 = _widget_0.GetChild(num);
					((MapMobilePartyTracker__SandBox_ViewModelCollection_Map_MapMobilePartyTrackerVM_Dependency_1_ItemTemplate)child2).SetDataSource(null);
					_widget_0.RemoveChild(child2);
				}
				_datasource_Root_Trackers = null;
			}
			_datasource_Root = null;
		}
		_datasource_Root = newDataSource;
		if (_datasource_Root == null)
		{
			return;
		}
		_datasource_Root.PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithValue += ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithBoolValue += ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithIntValue += ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithFloatValue += ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithUIntValue += ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithColorValue += ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithDoubleValue += ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithVec2Value += ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
		_datasource_Root_Trackers = _datasource_Root.Trackers;
		if (_datasource_Root_Trackers != null)
		{
			_datasource_Root_Trackers.ListChanged += OnList_datasource_Root_TrackersChanged;
			for (int i = 0; i < _datasource_Root_Trackers.Count; i++)
			{
				MapMobilePartyTracker__SandBox_ViewModelCollection_Map_MapMobilePartyTrackerVM_Dependency_1_ItemTemplate mapMobilePartyTracker__SandBox_ViewModelCollection_Map_MapMobilePartyTrackerVM_Dependency_1_ItemTemplate = new MapMobilePartyTracker__SandBox_ViewModelCollection_Map_MapMobilePartyTrackerVM_Dependency_1_ItemTemplate(base.Context);
				GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(mapMobilePartyTracker__SandBox_ViewModelCollection_Map_MapMobilePartyTrackerVM_Dependency_1_ItemTemplate);
				MobilePartyTrackItemVM dataSource = (MobilePartyTrackItemVM)(generatedWidgetData.Data = _datasource_Root_Trackers[i]);
				mapMobilePartyTracker__SandBox_ViewModelCollection_Map_MapMobilePartyTrackerVM_Dependency_1_ItemTemplate.AddComponent(generatedWidgetData);
				_widget_0.AddChildAtIndex(mapMobilePartyTracker__SandBox_ViewModelCollection_Map_MapMobilePartyTrackerVM_Dependency_1_ItemTemplate, i);
				mapMobilePartyTracker__SandBox_ViewModelCollection_Map_MapMobilePartyTrackerVM_Dependency_1_ItemTemplate.CreateWidgets();
				mapMobilePartyTracker__SandBox_ViewModelCollection_Map_MapMobilePartyTrackerVM_Dependency_1_ItemTemplate.SetIds();
				mapMobilePartyTracker__SandBox_ViewModelCollection_Map_MapMobilePartyTrackerVM_Dependency_1_ItemTemplate.SetAttributes();
				mapMobilePartyTracker__SandBox_ViewModelCollection_Map_MapMobilePartyTrackerVM_Dependency_1_ItemTemplate.SetDataSource(dataSource);
			}
		}
	}

	private void RefreshDataSource_datasource_Root_Trackers(MBBindingList<MobilePartyTrackItemVM> newDataSource)
	{
		if (_datasource_Root_Trackers != null)
		{
			_datasource_Root_Trackers.ListChanged -= OnList_datasource_Root_TrackersChanged;
			for (int num = _widget_0.ChildCount - 1; num >= 0; num--)
			{
				Widget child = _widget_0.GetChild(num);
				((MapMobilePartyTracker__SandBox_ViewModelCollection_Map_MapMobilePartyTrackerVM_Dependency_1_ItemTemplate)child).OnBeforeRemovedChild(child);
				Widget child2 = _widget_0.GetChild(num);
				((MapMobilePartyTracker__SandBox_ViewModelCollection_Map_MapMobilePartyTrackerVM_Dependency_1_ItemTemplate)child2).SetDataSource(null);
				_widget_0.RemoveChild(child2);
			}
			_datasource_Root_Trackers = null;
		}
		_datasource_Root_Trackers = newDataSource;
		_datasource_Root_Trackers = _datasource_Root.Trackers;
		if (_datasource_Root_Trackers != null)
		{
			_datasource_Root_Trackers.ListChanged += OnList_datasource_Root_TrackersChanged;
			for (int i = 0; i < _datasource_Root_Trackers.Count; i++)
			{
				MapMobilePartyTracker__SandBox_ViewModelCollection_Map_MapMobilePartyTrackerVM_Dependency_1_ItemTemplate mapMobilePartyTracker__SandBox_ViewModelCollection_Map_MapMobilePartyTrackerVM_Dependency_1_ItemTemplate = new MapMobilePartyTracker__SandBox_ViewModelCollection_Map_MapMobilePartyTrackerVM_Dependency_1_ItemTemplate(base.Context);
				GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(mapMobilePartyTracker__SandBox_ViewModelCollection_Map_MapMobilePartyTrackerVM_Dependency_1_ItemTemplate);
				MobilePartyTrackItemVM dataSource = (MobilePartyTrackItemVM)(generatedWidgetData.Data = _datasource_Root_Trackers[i]);
				mapMobilePartyTracker__SandBox_ViewModelCollection_Map_MapMobilePartyTrackerVM_Dependency_1_ItemTemplate.AddComponent(generatedWidgetData);
				_widget_0.AddChildAtIndex(mapMobilePartyTracker__SandBox_ViewModelCollection_Map_MapMobilePartyTrackerVM_Dependency_1_ItemTemplate, i);
				mapMobilePartyTracker__SandBox_ViewModelCollection_Map_MapMobilePartyTrackerVM_Dependency_1_ItemTemplate.CreateWidgets();
				mapMobilePartyTracker__SandBox_ViewModelCollection_Map_MapMobilePartyTrackerVM_Dependency_1_ItemTemplate.SetIds();
				mapMobilePartyTracker__SandBox_ViewModelCollection_Map_MapMobilePartyTrackerVM_Dependency_1_ItemTemplate.SetAttributes();
				mapMobilePartyTracker__SandBox_ViewModelCollection_Map_MapMobilePartyTrackerVM_Dependency_1_ItemTemplate.SetDataSource(dataSource);
			}
		}
	}
}
