using System.ComponentModel;
using System.Numerics;
using StoryMode.ViewModelCollection.Missions;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.GauntletUI.Data;
using TaleWorlds.GauntletUI.ExtraWidgets;
using TaleWorlds.GauntletUI.Layout;
using TaleWorlds.Library;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets.Tutorial;

namespace StoryMode.GauntletUI.AutoGenerated;

public class TrainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM : Widget, IGeneratedGauntletMovieRoot
{
	private Widget _widget;

	private ListPanel _widget_0;

	private ListPanel _widget_0_0;

	private RichTextWidget _widget_0_1;

	private ListPanel _widget_1;

	private RichTextWidget _widget_1_0;

	private TextWidget _widget_1_1;

	private Widget _widget_1_2;

	private Widget _widget_1_2_0;

	private Widget _widget_1_2_0_0;

	private TutorialMouseWidget _widget_1_2_0_1;

	private Widget _widget_1_2_0_1_0;

	private Widget _widget_1_2_0_1_1;

	private Widget _widget_1_2_0_1_2;

	private Widget _widget_1_2_1;

	private Widget _widget_1_2_1_0;

	private TutorialStickWidget _widget_1_2_1_1;

	private TextWidget _widget_1_2_1_1_0;

	private InputKeyVisualWidget _widget_1_2_1_2;

	private InputKeyVisualWidget _widget_1_2_1_3;

	private Widget _widget_1_2_2;

	private Widget _widget_1_2_3;

	private TrainingFieldObjectivesVM _datasource_Root;

	private MBBindingList<TrainingFieldObjectiveItemVM> _datasource_Root_ObjectiveItems;

	public TrainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM(UIContext context)
		: base(context)
	{
	}

	public void CreateWidgets()
	{
		_widget = this;
		_widget_0 = new ListPanel(base.Context);
		_widget.AddChild(_widget_0);
		_widget_0_0 = new ListPanel(base.Context);
		_widget_0.AddChild(_widget_0_0);
		_widget_0_1 = new RichTextWidget(base.Context);
		_widget_0.AddChild(_widget_0_1);
		_widget_1 = new ListPanel(base.Context);
		_widget.AddChild(_widget_1);
		_widget_1_0 = new RichTextWidget(base.Context);
		_widget_1.AddChild(_widget_1_0);
		_widget_1_1 = new TextWidget(base.Context);
		_widget_1.AddChild(_widget_1_1);
		_widget_1_2 = new Widget(base.Context);
		_widget_1.AddChild(_widget_1_2);
		_widget_1_2_0 = new Widget(base.Context);
		_widget_1_2.AddChild(_widget_1_2_0);
		_widget_1_2_0_0 = new Widget(base.Context);
		_widget_1_2_0.AddChild(_widget_1_2_0_0);
		_widget_1_2_0_1 = new TutorialMouseWidget(base.Context);
		_widget_1_2_0.AddChild(_widget_1_2_0_1);
		_widget_1_2_0_1_0 = new Widget(base.Context);
		_widget_1_2_0_1.AddChild(_widget_1_2_0_1_0);
		_widget_1_2_0_1_1 = new Widget(base.Context);
		_widget_1_2_0_1.AddChild(_widget_1_2_0_1_1);
		_widget_1_2_0_1_2 = new Widget(base.Context);
		_widget_1_2_0_1.AddChild(_widget_1_2_0_1_2);
		_widget_1_2_1 = new Widget(base.Context);
		_widget_1_2.AddChild(_widget_1_2_1);
		_widget_1_2_1_0 = new Widget(base.Context);
		_widget_1_2_1.AddChild(_widget_1_2_1_0);
		_widget_1_2_1_1 = new TutorialStickWidget(base.Context);
		_widget_1_2_1.AddChild(_widget_1_2_1_1);
		_widget_1_2_1_1_0 = new TextWidget(base.Context);
		_widget_1_2_1_1.AddChild(_widget_1_2_1_1_0);
		_widget_1_2_1_2 = new InputKeyVisualWidget(base.Context);
		_widget_1_2_1.AddChild(_widget_1_2_1_2);
		_widget_1_2_1_3 = new InputKeyVisualWidget(base.Context);
		_widget_1_2_1.AddChild(_widget_1_2_1_3);
		_widget_1_2_2 = new Widget(base.Context);
		_widget_1_2.AddChild(_widget_1_2_2);
		_widget_1_2_3 = new Widget(base.Context);
		_widget_1_2.AddChild(_widget_1_2_3);
	}

	public void SetIds()
	{
		_widget_1.Id = "ControlTutorialParent";
		_widget_1_2.Id = "MouseStickParent";
		_widget_1_2_0.Id = "MouseContainerWidget";
		_widget_1_2_0_0.Id = "GhostMouseVisualWidget";
		_widget_1_2_0_1_0.Id = "LeftMouseClickVisualWidget";
		_widget_1_2_0_1_1.Id = "RightMouseClickVisualWidget";
		_widget_1_2_0_1_2.Id = "MiddleMouseClickVisualWidget";
		_widget_1_2_1.Id = "ControllerContainerWidget";
		_widget_1_2_1_0.Id = "GhostStickVisualWidget";
		_widget_1_2_1_2.Id = "AttackClickVisualWidget";
		_widget_1_2_1_3.Id = "DefendClickVisualWidget";
		_widget_1_2_2.Id = "VerticalArrow";
		_widget_1_2_3.Id = "HorizontalArrow";
	}

	public void SetAttributes()
	{
		base.WidthSizePolicy = SizePolicy.StretchToParent;
		base.HeightSizePolicy = SizePolicy.StretchToParent;
		base.IsEnabled = false;
		_widget_0.WidthSizePolicy = SizePolicy.Fixed;
		_widget_0.HeightSizePolicy = SizePolicy.CoverChildren;
		_widget_0.MarginLeft = 25f;
		_widget_0.MarginTop = 25f;
		_widget_0.StackLayout.LayoutMethod = LayoutMethod.VerticalBottomToTop;
		_widget_0_0.WidthSizePolicy = SizePolicy.CoverChildren;
		_widget_0_0.HeightSizePolicy = SizePolicy.CoverChildren;
		_widget_0_0.MinWidth = 350f;
		_widget_0_0.StackLayout.LayoutMethod = LayoutMethod.VerticalBottomToTop;
		_widget_0_0.Sprite = base.Context.SpriteData.GetSprite("BlankWhiteSquare_9");
		_widget_0_0.Color = new Color(0f, 0f, 0f);
		_widget_0_0.AlphaFactor = 0.5f;
		_widget_0_1.WidthSizePolicy = SizePolicy.CoverChildren;
		_widget_0_1.HeightSizePolicy = SizePolicy.CoverChildren;
		_widget_0_1.Brush = base.Context.GetBrush("Objective.Text.WithOutline");
		_widget_0_1.MarginTop = 25f;
		_widget_1.WidthSizePolicy = SizePolicy.StretchToParent;
		_widget_1.HeightSizePolicy = SizePolicy.CoverChildren;
		_widget_1.HorizontalAlignment = HorizontalAlignment.Center;
		_widget_1.StackLayout.LayoutMethod = LayoutMethod.VerticalBottomToTop;
		_widget_1_0.WidthSizePolicy = SizePolicy.StretchToParent;
		_widget_1_0.HeightSizePolicy = SizePolicy.CoverChildren;
		_widget_1_0.HorizontalAlignment = HorizontalAlignment.Center;
		_widget_1_0.MarginTop = 25f;
		_widget_1_0.Brush = base.Context.GetBrush("Training.Main.Text");
		_widget_1_0.ClipContents = false;
		_widget_1_1.WidthSizePolicy = SizePolicy.StretchToParent;
		_widget_1_1.HeightSizePolicy = SizePolicy.CoverChildren;
		_widget_1_1.HorizontalAlignment = HorizontalAlignment.Center;
		_widget_1_1.MarginTop = 15f;
		_widget_1_1.Brush.FontSize = 45;
		_widget_1_1.ClipContents = false;
		_widget_1_2.WidthSizePolicy = SizePolicy.Fixed;
		_widget_1_2.HeightSizePolicy = SizePolicy.Fixed;
		_widget_1_2.SuggestedWidth = 190f;
		_widget_1_2.SuggestedHeight = 160f;
		_widget_1_2.HorizontalAlignment = HorizontalAlignment.Center;
		_widget_1_2.VerticalAlignment = VerticalAlignment.Center;
		_widget_1_2.Sprite = base.Context.SpriteData.GetSprite("BlankWhiteSquare_9");
		_widget_1_2.Color = new Color(0f, 0f, 0f);
		_widget_1_2.AlphaFactor = 0f;
		_widget_1_2_0.WidthSizePolicy = SizePolicy.Fixed;
		_widget_1_2_0.HeightSizePolicy = SizePolicy.Fixed;
		_widget_1_2_0.SuggestedWidth = 65f;
		_widget_1_2_0.SuggestedHeight = 99f;
		_widget_1_2_0.HorizontalAlignment = HorizontalAlignment.Center;
		_widget_1_2_0.VerticalAlignment = VerticalAlignment.Center;
		_widget_1_2_0_0.WidthSizePolicy = SizePolicy.Fixed;
		_widget_1_2_0_0.HeightSizePolicy = SizePolicy.Fixed;
		_widget_1_2_0_0.SuggestedWidth = 65f;
		_widget_1_2_0_0.SuggestedHeight = 99f;
		_widget_1_2_0_0.Sprite = base.Context.SpriteData.GetSprite("General\\Mouse\\mouse_body");
		_widget_1_2_0_0.HorizontalAlignment = HorizontalAlignment.Center;
		_widget_1_2_0_0.VerticalAlignment = VerticalAlignment.Center;
		_widget_1_2_0_0.AlphaFactor = 0f;
		_widget_1_2_0_1.WidthSizePolicy = SizePolicy.Fixed;
		_widget_1_2_0_1.HeightSizePolicy = SizePolicy.Fixed;
		_widget_1_2_0_1.SuggestedWidth = 65f;
		_widget_1_2_0_1.SuggestedHeight = 99f;
		_widget_1_2_0_1.Sprite = base.Context.SpriteData.GetSprite("General\\Mouse\\mouse_body");
		_widget_1_2_0_1.HorizontalAlignment = HorizontalAlignment.Center;
		_widget_1_2_0_1.VerticalAlignment = VerticalAlignment.Center;
		_widget_1_2_0_1.AlphaFactor = 0f;
		_widget_1_2_0_1.LeftMouseClickVisualWidget = _widget_1_2_0_1_0;
		_widget_1_2_0_1.RightMouseClickVisualWidget = _widget_1_2_0_1_1;
		_widget_1_2_0_1.MiddleMouseClickVisualWidget = _widget_1_2_0_1_2;
		_widget_1_2_0_1.GhostMouseVisualWidget = _widget_1_2_0_0;
		_widget_1_2_0_1.VerticalArrowWidget = _widget_1_2_2;
		_widget_1_2_0_1.HorizontalArrowWidget = _widget_1_2_3;
		_widget_1_2_0_1_0.WidthSizePolicy = SizePolicy.Fixed;
		_widget_1_2_0_1_0.HeightSizePolicy = SizePolicy.Fixed;
		_widget_1_2_0_1_0.SuggestedWidth = 32f;
		_widget_1_2_0_1_0.SuggestedHeight = 36f;
		_widget_1_2_0_1_0.Sprite = base.Context.SpriteData.GetSprite("General\\Mouse\\mouse_left_click");
		_widget_1_2_0_1_0.HorizontalAlignment = HorizontalAlignment.Left;
		_widget_1_2_0_1_0.VerticalAlignment = VerticalAlignment.Top;
		_widget_1_2_0_1_0.PositionYOffset = 1f;
		_widget_1_2_0_1_0.PositionXOffset = 2f;
		_widget_1_2_0_1_0.AlphaFactor = 0f;
		_widget_1_2_0_1_1.WidthSizePolicy = SizePolicy.Fixed;
		_widget_1_2_0_1_1.HeightSizePolicy = SizePolicy.Fixed;
		_widget_1_2_0_1_1.SuggestedWidth = 32f;
		_widget_1_2_0_1_1.SuggestedHeight = 36f;
		_widget_1_2_0_1_1.Sprite = base.Context.SpriteData.GetSprite("General\\Mouse\\mouse_left_click");
		_widget_1_2_0_1_1.HorizontalAlignment = HorizontalAlignment.Right;
		_widget_1_2_0_1_1.VerticalAlignment = VerticalAlignment.Top;
		_widget_1_2_0_1_1.PositionYOffset = 1f;
		_widget_1_2_0_1_1.PositionXOffset = -2f;
		_widget_1_2_0_1_1.HorizontalFlip = true;
		_widget_1_2_0_1_1.AlphaFactor = 0f;
		_widget_1_2_0_1_2.WidthSizePolicy = SizePolicy.Fixed;
		_widget_1_2_0_1_2.HeightSizePolicy = SizePolicy.Fixed;
		_widget_1_2_0_1_2.SuggestedWidth = 9f;
		_widget_1_2_0_1_2.SuggestedHeight = 25f;
		_widget_1_2_0_1_2.Sprite = base.Context.SpriteData.GetSprite("General\\Mouse\\mouse_mid_click");
		_widget_1_2_0_1_2.HorizontalAlignment = HorizontalAlignment.Center;
		_widget_1_2_0_1_2.VerticalAlignment = VerticalAlignment.Top;
		_widget_1_2_0_1_2.PositionYOffset = 17f;
		_widget_1_2_0_1_2.AlphaFactor = 0f;
		_widget_1_2_1.WidthSizePolicy = SizePolicy.Fixed;
		_widget_1_2_1.HeightSizePolicy = SizePolicy.Fixed;
		_widget_1_2_1.SuggestedWidth = 65f;
		_widget_1_2_1.SuggestedHeight = 99f;
		_widget_1_2_1.HorizontalAlignment = HorizontalAlignment.Center;
		_widget_1_2_1.VerticalAlignment = VerticalAlignment.Center;
		_widget_1_2_1_0.WidthSizePolicy = SizePolicy.Fixed;
		_widget_1_2_1_0.HeightSizePolicy = SizePolicy.Fixed;
		_widget_1_2_1_0.SuggestedWidth = 65f;
		_widget_1_2_1_0.SuggestedHeight = 65f;
		_widget_1_2_1_0.Sprite = base.Context.SpriteData.GetSprite("General\\Mouse\\stick_body");
		_widget_1_2_1_0.HorizontalAlignment = HorizontalAlignment.Center;
		_widget_1_2_1_0.VerticalAlignment = VerticalAlignment.Center;
		_widget_1_2_1_0.AlphaFactor = 0f;
		_widget_1_2_1_1.WidthSizePolicy = SizePolicy.Fixed;
		_widget_1_2_1_1.HeightSizePolicy = SizePolicy.Fixed;
		_widget_1_2_1_1.SuggestedWidth = 32f;
		_widget_1_2_1_1.SuggestedHeight = 32f;
		_widget_1_2_1_1.Sprite = base.Context.SpriteData.GetSprite("General\\Mouse\\stick_click");
		_widget_1_2_1_1.HorizontalAlignment = HorizontalAlignment.Center;
		_widget_1_2_1_1.VerticalAlignment = VerticalAlignment.Center;
		_widget_1_2_1_1.AlphaFactor = 0f;
		_widget_1_2_1_1.LeftMouseClickVisualWidget = _widget_1_2_1_2;
		_widget_1_2_1_1.RightMouseClickVisualWidget = _widget_1_2_1_3;
		_widget_1_2_1_1.GhostMouseVisualWidget = _widget_1_2_1_0;
		_widget_1_2_1_1.VerticalArrowWidget = _widget_1_2_2;
		_widget_1_2_1_1.HorizontalArrowWidget = _widget_1_2_3;
		_widget_1_2_1_1_0.WidthSizePolicy = SizePolicy.CoverChildren;
		_widget_1_2_1_1_0.HeightSizePolicy = SizePolicy.CoverChildren;
		_widget_1_2_1_1_0.HorizontalAlignment = HorizontalAlignment.Center;
		_widget_1_2_1_1_0.VerticalAlignment = VerticalAlignment.Center;
		_widget_1_2_1_1_0.Brush = base.Context.GetBrush("Objective.Text");
		_widget_1_2_1_2.WidthSizePolicy = SizePolicy.Fixed;
		_widget_1_2_1_2.HeightSizePolicy = SizePolicy.Fixed;
		_widget_1_2_1_2.SuggestedWidth = 70f;
		_widget_1_2_1_2.SuggestedHeight = 70f;
		_widget_1_2_1_2.HorizontalAlignment = HorizontalAlignment.Center;
		_widget_1_2_1_2.VerticalAlignment = VerticalAlignment.Center;
		_widget_1_2_1_2.PositionXOffset = 50f;
		_widget_1_2_1_2.AlphaFactor = 0f;
		_widget_1_2_1_2.KeyID = "ControllerRTrigger";
		_widget_1_2_1_3.WidthSizePolicy = SizePolicy.Fixed;
		_widget_1_2_1_3.HeightSizePolicy = SizePolicy.Fixed;
		_widget_1_2_1_3.SuggestedWidth = 70f;
		_widget_1_2_1_3.SuggestedHeight = 70f;
		_widget_1_2_1_3.HorizontalAlignment = HorizontalAlignment.Center;
		_widget_1_2_1_3.VerticalAlignment = VerticalAlignment.Center;
		_widget_1_2_1_3.PositionXOffset = -60f;
		_widget_1_2_1_3.AlphaFactor = 0f;
		_widget_1_2_1_3.KeyID = "ControllerLTrigger";
		_widget_1_2_2.WidthSizePolicy = SizePolicy.Fixed;
		_widget_1_2_2.HeightSizePolicy = SizePolicy.Fixed;
		_widget_1_2_2.SuggestedWidth = 31f;
		_widget_1_2_2.SuggestedHeight = 121f;
		_widget_1_2_2.Sprite = base.Context.SpriteData.GetSprite("crosshair_arrow_vertical");
		_widget_1_2_2.VerticalAlignment = VerticalAlignment.Center;
		_widget_1_2_2.HorizontalAlignment = HorizontalAlignment.Right;
		_widget_1_2_2.AlphaFactor = 0f;
		_widget_1_2_2.PositionXOffset = 0f;
		_widget_1_2_3.WidthSizePolicy = SizePolicy.Fixed;
		_widget_1_2_3.HeightSizePolicy = SizePolicy.Fixed;
		_widget_1_2_3.SuggestedWidth = 121f;
		_widget_1_2_3.SuggestedHeight = 31f;
		_widget_1_2_3.Sprite = base.Context.SpriteData.GetSprite("crosshair_arrow");
		_widget_1_2_3.VerticalAlignment = VerticalAlignment.Bottom;
		_widget_1_2_3.HorizontalAlignment = HorizontalAlignment.Center;
		_widget_1_2_3.AlphaFactor = 0f;
		_widget_1_2_3.PositionYOffset = 0f;
	}

	public void RefreshBindingWithChildren()
	{
		TrainingFieldObjectivesVM datasource_Root = _datasource_Root;
		SetDataSource(null);
		SetDataSource(datasource_Root);
	}

	public void DestroyDataSource()
	{
		if (_datasource_Root == null)
		{
			return;
		}
		_datasource_Root.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
		_widget_0_1.PropertyChanged -= PropertyChangedListenerOf_widget_0_1;
		_widget_0_1.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_1;
		_widget_0_1.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_1;
		_widget_0_1.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_1;
		_widget_0_1.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_1;
		_widget_0_1.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_1;
		_widget_0_1.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_1;
		_widget_0_1.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_1;
		_widget_0_1.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_1;
		_widget_1_0.PropertyChanged -= PropertyChangedListenerOf_widget_1_0;
		_widget_1_0.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_1_0;
		_widget_1_0.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_1_0;
		_widget_1_0.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_1_0;
		_widget_1_0.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_1_0;
		_widget_1_0.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_1_0;
		_widget_1_0.intPropertyChanged -= intPropertyChangedListenerOf_widget_1_0;
		_widget_1_0.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_1_0;
		_widget_1_0.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_1_0;
		_widget_1_1.PropertyChanged -= PropertyChangedListenerOf_widget_1_1;
		_widget_1_1.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_1_1;
		_widget_1_1.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_1_1;
		_widget_1_1.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_1_1;
		_widget_1_1.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_1_1;
		_widget_1_1.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_1_1;
		_widget_1_1.intPropertyChanged -= intPropertyChangedListenerOf_widget_1_1;
		_widget_1_1.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_1_1;
		_widget_1_1.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_1_1;
		_widget_1_2_0.PropertyChanged -= PropertyChangedListenerOf_widget_1_2_0;
		_widget_1_2_0.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_1_2_0;
		_widget_1_2_0.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_1_2_0;
		_widget_1_2_0.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_1_2_0;
		_widget_1_2_0.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_1_2_0;
		_widget_1_2_0.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_1_2_0;
		_widget_1_2_0.intPropertyChanged -= intPropertyChangedListenerOf_widget_1_2_0;
		_widget_1_2_0.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_1_2_0;
		_widget_1_2_0.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_1_2_0;
		_widget_1_2_0_1.PropertyChanged -= PropertyChangedListenerOf_widget_1_2_0_1;
		_widget_1_2_0_1.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_1_2_0_1;
		_widget_1_2_0_1.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_1_2_0_1;
		_widget_1_2_0_1.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_1_2_0_1;
		_widget_1_2_0_1.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_1_2_0_1;
		_widget_1_2_0_1.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_1_2_0_1;
		_widget_1_2_0_1.intPropertyChanged -= intPropertyChangedListenerOf_widget_1_2_0_1;
		_widget_1_2_0_1.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_1_2_0_1;
		_widget_1_2_0_1.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_1_2_0_1;
		_widget_1_2_1.PropertyChanged -= PropertyChangedListenerOf_widget_1_2_1;
		_widget_1_2_1.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_1_2_1;
		_widget_1_2_1.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_1_2_1;
		_widget_1_2_1.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_1_2_1;
		_widget_1_2_1.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_1_2_1;
		_widget_1_2_1.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_1_2_1;
		_widget_1_2_1.intPropertyChanged -= intPropertyChangedListenerOf_widget_1_2_1;
		_widget_1_2_1.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_1_2_1;
		_widget_1_2_1.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_1_2_1;
		_widget_1_2_1_1.PropertyChanged -= PropertyChangedListenerOf_widget_1_2_1_1;
		_widget_1_2_1_1.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_1_2_1_1;
		_widget_1_2_1_1.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_1_2_1_1;
		_widget_1_2_1_1.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_1_2_1_1;
		_widget_1_2_1_1.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_1_2_1_1;
		_widget_1_2_1_1.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_1_2_1_1;
		_widget_1_2_1_1.intPropertyChanged -= intPropertyChangedListenerOf_widget_1_2_1_1;
		_widget_1_2_1_1.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_1_2_1_1;
		_widget_1_2_1_1.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_1_2_1_1;
		_widget_1_2_1_1_0.PropertyChanged -= PropertyChangedListenerOf_widget_1_2_1_1_0;
		_widget_1_2_1_1_0.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_1_2_1_1_0;
		_widget_1_2_1_1_0.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_1_2_1_1_0;
		_widget_1_2_1_1_0.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_1_2_1_1_0;
		_widget_1_2_1_1_0.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_1_2_1_1_0;
		_widget_1_2_1_1_0.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_1_2_1_1_0;
		_widget_1_2_1_1_0.intPropertyChanged -= intPropertyChangedListenerOf_widget_1_2_1_1_0;
		_widget_1_2_1_1_0.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_1_2_1_1_0;
		_widget_1_2_1_1_0.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_1_2_1_1_0;
		if (_datasource_Root_ObjectiveItems != null)
		{
			_datasource_Root_ObjectiveItems.ListChanged -= OnList_datasource_Root_ObjectiveItemsChanged;
			for (int num = _widget_0_0.ChildCount - 1; num >= 0; num--)
			{
				Widget child = _widget_0_0.GetChild(num);
				((TrainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_1_ItemTemplate)child).OnBeforeRemovedChild(child);
				((TrainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_1_ItemTemplate)_widget_0_0.GetChild(num)).DestroyDataSource();
			}
			_datasource_Root_ObjectiveItems = null;
		}
		_datasource_Root = null;
	}

	public void SetDataSource(TrainingFieldObjectivesVM dataSource)
	{
		RefreshDataSource_datasource_Root(dataSource);
	}

	private void PropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_0_1(string propertyName)
	{
		if (propertyName == "Text")
		{
			_datasource_Root.LeaveAnyTimeText = _widget_0_1.Text;
		}
	}

	private void PropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_1_0(string propertyName)
	{
		if (propertyName == "Text")
		{
			_datasource_Root.CurrentObjectiveText = _widget_1_0.Text;
		}
	}

	private void PropertyChangedListenerOf_widget_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_1_1(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_1_1(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_1_1(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_1_1(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_1_1(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_1_1(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_1_1(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_1_1(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_1_1(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_1_1(string propertyName)
	{
		if (propertyName == "Text")
		{
			_datasource_Root.TimerText = _widget_1_1.Text;
		}
	}

	private void PropertyChangedListenerOf_widget_1_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_1_2_0(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_1_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_1_2_0(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_1_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_1_2_0(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_1_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_1_2_0(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_1_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_1_2_0(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_1_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_1_2_0(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_1_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_1_2_0(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_1_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_1_2_0(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_1_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_1_2_0(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_1_2_0(string propertyName)
	{
		if (propertyName == "IsHidden")
		{
			_datasource_Root.IsGamepadActive = _widget_1_2_0.IsHidden;
		}
	}

	private void PropertyChangedListenerOf_widget_1_2_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_1_2_0_1(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_1_2_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_1_2_0_1(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_1_2_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_1_2_0_1(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_1_2_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_1_2_0_1(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_1_2_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_1_2_0_1(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_1_2_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_1_2_0_1(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_1_2_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_1_2_0_1(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_1_2_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_1_2_0_1(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_1_2_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_1_2_0_1(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_1_2_0_1(string propertyName)
	{
		if (propertyName == "CurrentObjectiveType")
		{
			_datasource_Root.CurrentMouseObjective = _widget_1_2_0_1.CurrentObjectiveType;
		}
	}

	private void PropertyChangedListenerOf_widget_1_2_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_1_2_1(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_1_2_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_1_2_1(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_1_2_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_1_2_1(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_1_2_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_1_2_1(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_1_2_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_1_2_1(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_1_2_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_1_2_1(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_1_2_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_1_2_1(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_1_2_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_1_2_1(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_1_2_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_1_2_1(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_1_2_1(string propertyName)
	{
		if (propertyName == "IsVisible")
		{
			_datasource_Root.IsGamepadActive = _widget_1_2_1.IsVisible;
		}
	}

	private void PropertyChangedListenerOf_widget_1_2_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_1_2_1_1(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_1_2_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_1_2_1_1(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_1_2_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_1_2_1_1(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_1_2_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_1_2_1_1(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_1_2_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_1_2_1_1(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_1_2_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_1_2_1_1(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_1_2_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_1_2_1_1(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_1_2_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_1_2_1_1(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_1_2_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_1_2_1_1(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_1_2_1_1(string propertyName)
	{
		if (propertyName == "CurrentObjectiveType")
		{
			_datasource_Root.CurrentMouseObjective = _widget_1_2_1_1.CurrentObjectiveType;
		}
	}

	private void PropertyChangedListenerOf_widget_1_2_1_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_1_2_1_1_0(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_1_2_1_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_1_2_1_1_0(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_1_2_1_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_1_2_1_1_0(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_1_2_1_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_1_2_1_1_0(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_1_2_1_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_1_2_1_1_0(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_1_2_1_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_1_2_1_1_0(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_1_2_1_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_1_2_1_1_0(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_1_2_1_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_1_2_1_1_0(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_1_2_1_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_1_2_1_1_0(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_1_2_1_1_0(string propertyName)
	{
		if (propertyName == "Text")
		{
			_datasource_Root.RightStickAbbreviatedText = _widget_1_2_1_1_0.Text;
		}
	}

	private void ViewModelPropertyChangedListenerOf_datasource_Root(object sender, PropertyChangedEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root(object sender, PropertyChangedWithValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root(object sender, PropertyChangedWithBoolValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root(object sender, PropertyChangedWithFloatValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithUIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root(object sender, PropertyChangedWithColorValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root(object sender, PropertyChangedWithDoubleValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root(object sender, PropertyChangedWithVec2ValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void HandleViewModelPropertyChangeOf_datasource_Root(string propertyName)
	{
		switch (propertyName)
		{
		case "ObjectiveItems":
			RefreshDataSource_datasource_Root_ObjectiveItems(_datasource_Root.ObjectiveItems);
			break;
		case "LeaveAnyTimeText":
			_widget_0_1.Text = _datasource_Root.LeaveAnyTimeText;
			break;
		case "CurrentObjectiveText":
			_widget_1_0.Text = _datasource_Root.CurrentObjectiveText;
			break;
		case "TimerText":
			_widget_1_1.Text = _datasource_Root.TimerText;
			break;
		case "IsGamepadActive":
			_widget_1_2_0.IsHidden = _datasource_Root.IsGamepadActive;
			_widget_1_2_1.IsVisible = _datasource_Root.IsGamepadActive;
			break;
		case "CurrentMouseObjective":
			_widget_1_2_0_1.CurrentObjectiveType = _datasource_Root.CurrentMouseObjective;
			_widget_1_2_1_1.CurrentObjectiveType = _datasource_Root.CurrentMouseObjective;
			break;
		case "RightStickAbbreviatedText":
			_widget_1_2_1_1_0.Text = _datasource_Root.RightStickAbbreviatedText;
			break;
		}
	}

	public void OnList_datasource_Root_ObjectiveItemsChanged(object sender, TaleWorlds.Library.ListChangedEventArgs e)
	{
		switch (e.ListChangedType)
		{
		case TaleWorlds.Library.ListChangedType.Reset:
		{
			for (int num = _widget_0_0.ChildCount - 1; num >= 0; num--)
			{
				Widget child3 = _widget_0_0.GetChild(num);
				((TrainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_1_ItemTemplate)child3).OnBeforeRemovedChild(child3);
				Widget child4 = _widget_0_0.GetChild(num);
				((TrainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_1_ItemTemplate)child4).SetDataSource(null);
				_widget_0_0.RemoveChild(child4);
			}
			break;
		}
		case TaleWorlds.Library.ListChangedType.Sorted:
		{
			for (int i = 0; i < _datasource_Root_ObjectiveItems.Count; i++)
			{
				TrainingFieldObjectiveItemVM bindingObject = _datasource_Root_ObjectiveItems[i];
				_widget_0_0.FindChild((Widget widget) => widget.GetComponent<GeneratedWidgetData>().Data == bindingObject).SetSiblingIndex(i);
			}
			break;
		}
		case TaleWorlds.Library.ListChangedType.ItemAdded:
		{
			TrainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_1_ItemTemplate trainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_1_ItemTemplate = new TrainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_1_ItemTemplate(base.Context);
			GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(trainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_1_ItemTemplate);
			TrainingFieldObjectiveItemVM dataSource = (TrainingFieldObjectiveItemVM)(generatedWidgetData.Data = _datasource_Root_ObjectiveItems[e.NewIndex]);
			trainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_1_ItemTemplate.AddComponent(generatedWidgetData);
			_widget_0_0.AddChildAtIndex(trainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_1_ItemTemplate, e.NewIndex);
			trainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_1_ItemTemplate.CreateWidgets();
			trainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_1_ItemTemplate.SetIds();
			trainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_1_ItemTemplate.SetAttributes();
			trainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_1_ItemTemplate.SetDataSource(dataSource);
			break;
		}
		case TaleWorlds.Library.ListChangedType.ItemBeforeDeleted:
		{
			Widget child2 = _widget_0_0.GetChild(e.NewIndex);
			((TrainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_1_ItemTemplate)child2).OnBeforeRemovedChild(child2);
			break;
		}
		case TaleWorlds.Library.ListChangedType.ItemDeleted:
		{
			Widget child = _widget_0_0.GetChild(e.NewIndex);
			((TrainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_1_ItemTemplate)child).SetDataSource(null);
			_widget_0_0.RemoveChild(child);
			break;
		}
		case TaleWorlds.Library.ListChangedType.ItemChanged:
			break;
		}
	}

	private void RefreshDataSource_datasource_Root(TrainingFieldObjectivesVM newDataSource)
	{
		if (_datasource_Root != null)
		{
			_datasource_Root.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
			_widget_0_1.PropertyChanged -= PropertyChangedListenerOf_widget_0_1;
			_widget_0_1.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_1;
			_widget_0_1.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_1;
			_widget_0_1.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_1;
			_widget_0_1.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_1;
			_widget_0_1.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_1;
			_widget_0_1.intPropertyChanged -= intPropertyChangedListenerOf_widget_0_1;
			_widget_0_1.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_1;
			_widget_0_1.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_1;
			_widget_1_0.PropertyChanged -= PropertyChangedListenerOf_widget_1_0;
			_widget_1_0.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_1_0;
			_widget_1_0.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_1_0;
			_widget_1_0.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_1_0;
			_widget_1_0.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_1_0;
			_widget_1_0.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_1_0;
			_widget_1_0.intPropertyChanged -= intPropertyChangedListenerOf_widget_1_0;
			_widget_1_0.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_1_0;
			_widget_1_0.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_1_0;
			_widget_1_1.PropertyChanged -= PropertyChangedListenerOf_widget_1_1;
			_widget_1_1.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_1_1;
			_widget_1_1.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_1_1;
			_widget_1_1.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_1_1;
			_widget_1_1.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_1_1;
			_widget_1_1.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_1_1;
			_widget_1_1.intPropertyChanged -= intPropertyChangedListenerOf_widget_1_1;
			_widget_1_1.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_1_1;
			_widget_1_1.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_1_1;
			_widget_1_2_0.PropertyChanged -= PropertyChangedListenerOf_widget_1_2_0;
			_widget_1_2_0.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_1_2_0;
			_widget_1_2_0.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_1_2_0;
			_widget_1_2_0.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_1_2_0;
			_widget_1_2_0.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_1_2_0;
			_widget_1_2_0.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_1_2_0;
			_widget_1_2_0.intPropertyChanged -= intPropertyChangedListenerOf_widget_1_2_0;
			_widget_1_2_0.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_1_2_0;
			_widget_1_2_0.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_1_2_0;
			_widget_1_2_0_1.PropertyChanged -= PropertyChangedListenerOf_widget_1_2_0_1;
			_widget_1_2_0_1.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_1_2_0_1;
			_widget_1_2_0_1.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_1_2_0_1;
			_widget_1_2_0_1.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_1_2_0_1;
			_widget_1_2_0_1.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_1_2_0_1;
			_widget_1_2_0_1.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_1_2_0_1;
			_widget_1_2_0_1.intPropertyChanged -= intPropertyChangedListenerOf_widget_1_2_0_1;
			_widget_1_2_0_1.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_1_2_0_1;
			_widget_1_2_0_1.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_1_2_0_1;
			_widget_1_2_1.PropertyChanged -= PropertyChangedListenerOf_widget_1_2_1;
			_widget_1_2_1.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_1_2_1;
			_widget_1_2_1.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_1_2_1;
			_widget_1_2_1.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_1_2_1;
			_widget_1_2_1.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_1_2_1;
			_widget_1_2_1.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_1_2_1;
			_widget_1_2_1.intPropertyChanged -= intPropertyChangedListenerOf_widget_1_2_1;
			_widget_1_2_1.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_1_2_1;
			_widget_1_2_1.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_1_2_1;
			_widget_1_2_1_1.PropertyChanged -= PropertyChangedListenerOf_widget_1_2_1_1;
			_widget_1_2_1_1.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_1_2_1_1;
			_widget_1_2_1_1.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_1_2_1_1;
			_widget_1_2_1_1.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_1_2_1_1;
			_widget_1_2_1_1.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_1_2_1_1;
			_widget_1_2_1_1.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_1_2_1_1;
			_widget_1_2_1_1.intPropertyChanged -= intPropertyChangedListenerOf_widget_1_2_1_1;
			_widget_1_2_1_1.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_1_2_1_1;
			_widget_1_2_1_1.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_1_2_1_1;
			_widget_1_2_1_1_0.PropertyChanged -= PropertyChangedListenerOf_widget_1_2_1_1_0;
			_widget_1_2_1_1_0.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_1_2_1_1_0;
			_widget_1_2_1_1_0.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_1_2_1_1_0;
			_widget_1_2_1_1_0.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_1_2_1_1_0;
			_widget_1_2_1_1_0.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_1_2_1_1_0;
			_widget_1_2_1_1_0.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_1_2_1_1_0;
			_widget_1_2_1_1_0.intPropertyChanged -= intPropertyChangedListenerOf_widget_1_2_1_1_0;
			_widget_1_2_1_1_0.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_1_2_1_1_0;
			_widget_1_2_1_1_0.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_1_2_1_1_0;
			if (_datasource_Root_ObjectiveItems != null)
			{
				_datasource_Root_ObjectiveItems.ListChanged -= OnList_datasource_Root_ObjectiveItemsChanged;
				for (int num = _widget_0_0.ChildCount - 1; num >= 0; num--)
				{
					Widget child = _widget_0_0.GetChild(num);
					((TrainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_1_ItemTemplate)child).OnBeforeRemovedChild(child);
					Widget child2 = _widget_0_0.GetChild(num);
					((TrainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_1_ItemTemplate)child2).SetDataSource(null);
					_widget_0_0.RemoveChild(child2);
				}
				_datasource_Root_ObjectiveItems = null;
			}
			_datasource_Root = null;
		}
		_datasource_Root = newDataSource;
		if (_datasource_Root == null)
		{
			return;
		}
		_datasource_Root.PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithValue += ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithBoolValue += ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithIntValue += ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithFloatValue += ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithUIntValue += ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithColorValue += ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithDoubleValue += ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithVec2Value += ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
		_widget_0_1.Text = _datasource_Root.LeaveAnyTimeText;
		_widget_0_1.PropertyChanged += PropertyChangedListenerOf_widget_0_1;
		_widget_0_1.boolPropertyChanged += boolPropertyChangedListenerOf_widget_0_1;
		_widget_0_1.floatPropertyChanged += floatPropertyChangedListenerOf_widget_0_1;
		_widget_0_1.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_0_1;
		_widget_0_1.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_0_1;
		_widget_0_1.doublePropertyChanged += doublePropertyChangedListenerOf_widget_0_1;
		_widget_0_1.intPropertyChanged += intPropertyChangedListenerOf_widget_0_1;
		_widget_0_1.uintPropertyChanged += uintPropertyChangedListenerOf_widget_0_1;
		_widget_0_1.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_0_1;
		_widget_1_0.Text = _datasource_Root.CurrentObjectiveText;
		_widget_1_0.PropertyChanged += PropertyChangedListenerOf_widget_1_0;
		_widget_1_0.boolPropertyChanged += boolPropertyChangedListenerOf_widget_1_0;
		_widget_1_0.floatPropertyChanged += floatPropertyChangedListenerOf_widget_1_0;
		_widget_1_0.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_1_0;
		_widget_1_0.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_1_0;
		_widget_1_0.doublePropertyChanged += doublePropertyChangedListenerOf_widget_1_0;
		_widget_1_0.intPropertyChanged += intPropertyChangedListenerOf_widget_1_0;
		_widget_1_0.uintPropertyChanged += uintPropertyChangedListenerOf_widget_1_0;
		_widget_1_0.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_1_0;
		_widget_1_1.Text = _datasource_Root.TimerText;
		_widget_1_1.PropertyChanged += PropertyChangedListenerOf_widget_1_1;
		_widget_1_1.boolPropertyChanged += boolPropertyChangedListenerOf_widget_1_1;
		_widget_1_1.floatPropertyChanged += floatPropertyChangedListenerOf_widget_1_1;
		_widget_1_1.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_1_1;
		_widget_1_1.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_1_1;
		_widget_1_1.doublePropertyChanged += doublePropertyChangedListenerOf_widget_1_1;
		_widget_1_1.intPropertyChanged += intPropertyChangedListenerOf_widget_1_1;
		_widget_1_1.uintPropertyChanged += uintPropertyChangedListenerOf_widget_1_1;
		_widget_1_1.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_1_1;
		_widget_1_2_0.IsHidden = _datasource_Root.IsGamepadActive;
		_widget_1_2_0.PropertyChanged += PropertyChangedListenerOf_widget_1_2_0;
		_widget_1_2_0.boolPropertyChanged += boolPropertyChangedListenerOf_widget_1_2_0;
		_widget_1_2_0.floatPropertyChanged += floatPropertyChangedListenerOf_widget_1_2_0;
		_widget_1_2_0.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_1_2_0;
		_widget_1_2_0.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_1_2_0;
		_widget_1_2_0.doublePropertyChanged += doublePropertyChangedListenerOf_widget_1_2_0;
		_widget_1_2_0.intPropertyChanged += intPropertyChangedListenerOf_widget_1_2_0;
		_widget_1_2_0.uintPropertyChanged += uintPropertyChangedListenerOf_widget_1_2_0;
		_widget_1_2_0.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_1_2_0;
		_widget_1_2_0_1.CurrentObjectiveType = _datasource_Root.CurrentMouseObjective;
		_widget_1_2_0_1.PropertyChanged += PropertyChangedListenerOf_widget_1_2_0_1;
		_widget_1_2_0_1.boolPropertyChanged += boolPropertyChangedListenerOf_widget_1_2_0_1;
		_widget_1_2_0_1.floatPropertyChanged += floatPropertyChangedListenerOf_widget_1_2_0_1;
		_widget_1_2_0_1.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_1_2_0_1;
		_widget_1_2_0_1.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_1_2_0_1;
		_widget_1_2_0_1.doublePropertyChanged += doublePropertyChangedListenerOf_widget_1_2_0_1;
		_widget_1_2_0_1.intPropertyChanged += intPropertyChangedListenerOf_widget_1_2_0_1;
		_widget_1_2_0_1.uintPropertyChanged += uintPropertyChangedListenerOf_widget_1_2_0_1;
		_widget_1_2_0_1.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_1_2_0_1;
		_widget_1_2_1.IsVisible = _datasource_Root.IsGamepadActive;
		_widget_1_2_1.PropertyChanged += PropertyChangedListenerOf_widget_1_2_1;
		_widget_1_2_1.boolPropertyChanged += boolPropertyChangedListenerOf_widget_1_2_1;
		_widget_1_2_1.floatPropertyChanged += floatPropertyChangedListenerOf_widget_1_2_1;
		_widget_1_2_1.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_1_2_1;
		_widget_1_2_1.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_1_2_1;
		_widget_1_2_1.doublePropertyChanged += doublePropertyChangedListenerOf_widget_1_2_1;
		_widget_1_2_1.intPropertyChanged += intPropertyChangedListenerOf_widget_1_2_1;
		_widget_1_2_1.uintPropertyChanged += uintPropertyChangedListenerOf_widget_1_2_1;
		_widget_1_2_1.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_1_2_1;
		_widget_1_2_1_1.CurrentObjectiveType = _datasource_Root.CurrentMouseObjective;
		_widget_1_2_1_1.PropertyChanged += PropertyChangedListenerOf_widget_1_2_1_1;
		_widget_1_2_1_1.boolPropertyChanged += boolPropertyChangedListenerOf_widget_1_2_1_1;
		_widget_1_2_1_1.floatPropertyChanged += floatPropertyChangedListenerOf_widget_1_2_1_1;
		_widget_1_2_1_1.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_1_2_1_1;
		_widget_1_2_1_1.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_1_2_1_1;
		_widget_1_2_1_1.doublePropertyChanged += doublePropertyChangedListenerOf_widget_1_2_1_1;
		_widget_1_2_1_1.intPropertyChanged += intPropertyChangedListenerOf_widget_1_2_1_1;
		_widget_1_2_1_1.uintPropertyChanged += uintPropertyChangedListenerOf_widget_1_2_1_1;
		_widget_1_2_1_1.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_1_2_1_1;
		_widget_1_2_1_1_0.Text = _datasource_Root.RightStickAbbreviatedText;
		_widget_1_2_1_1_0.PropertyChanged += PropertyChangedListenerOf_widget_1_2_1_1_0;
		_widget_1_2_1_1_0.boolPropertyChanged += boolPropertyChangedListenerOf_widget_1_2_1_1_0;
		_widget_1_2_1_1_0.floatPropertyChanged += floatPropertyChangedListenerOf_widget_1_2_1_1_0;
		_widget_1_2_1_1_0.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_1_2_1_1_0;
		_widget_1_2_1_1_0.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_1_2_1_1_0;
		_widget_1_2_1_1_0.doublePropertyChanged += doublePropertyChangedListenerOf_widget_1_2_1_1_0;
		_widget_1_2_1_1_0.intPropertyChanged += intPropertyChangedListenerOf_widget_1_2_1_1_0;
		_widget_1_2_1_1_0.uintPropertyChanged += uintPropertyChangedListenerOf_widget_1_2_1_1_0;
		_widget_1_2_1_1_0.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_1_2_1_1_0;
		_datasource_Root_ObjectiveItems = _datasource_Root.ObjectiveItems;
		if (_datasource_Root_ObjectiveItems != null)
		{
			_datasource_Root_ObjectiveItems.ListChanged += OnList_datasource_Root_ObjectiveItemsChanged;
			for (int i = 0; i < _datasource_Root_ObjectiveItems.Count; i++)
			{
				TrainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_1_ItemTemplate trainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_1_ItemTemplate = new TrainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_1_ItemTemplate(base.Context);
				GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(trainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_1_ItemTemplate);
				TrainingFieldObjectiveItemVM dataSource = (TrainingFieldObjectiveItemVM)(generatedWidgetData.Data = _datasource_Root_ObjectiveItems[i]);
				trainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_1_ItemTemplate.AddComponent(generatedWidgetData);
				_widget_0_0.AddChildAtIndex(trainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_1_ItemTemplate, i);
				trainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_1_ItemTemplate.CreateWidgets();
				trainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_1_ItemTemplate.SetIds();
				trainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_1_ItemTemplate.SetAttributes();
				trainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_1_ItemTemplate.SetDataSource(dataSource);
			}
		}
	}

	private void RefreshDataSource_datasource_Root_ObjectiveItems(MBBindingList<TrainingFieldObjectiveItemVM> newDataSource)
	{
		if (_datasource_Root_ObjectiveItems != null)
		{
			_datasource_Root_ObjectiveItems.ListChanged -= OnList_datasource_Root_ObjectiveItemsChanged;
			for (int num = _widget_0_0.ChildCount - 1; num >= 0; num--)
			{
				Widget child = _widget_0_0.GetChild(num);
				((TrainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_1_ItemTemplate)child).OnBeforeRemovedChild(child);
				Widget child2 = _widget_0_0.GetChild(num);
				((TrainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_1_ItemTemplate)child2).SetDataSource(null);
				_widget_0_0.RemoveChild(child2);
			}
			_datasource_Root_ObjectiveItems = null;
		}
		_datasource_Root_ObjectiveItems = newDataSource;
		_datasource_Root_ObjectiveItems = _datasource_Root.ObjectiveItems;
		if (_datasource_Root_ObjectiveItems != null)
		{
			_datasource_Root_ObjectiveItems.ListChanged += OnList_datasource_Root_ObjectiveItemsChanged;
			for (int i = 0; i < _datasource_Root_ObjectiveItems.Count; i++)
			{
				TrainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_1_ItemTemplate trainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_1_ItemTemplate = new TrainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_1_ItemTemplate(base.Context);
				GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(trainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_1_ItemTemplate);
				TrainingFieldObjectiveItemVM dataSource = (TrainingFieldObjectiveItemVM)(generatedWidgetData.Data = _datasource_Root_ObjectiveItems[i]);
				trainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_1_ItemTemplate.AddComponent(generatedWidgetData);
				_widget_0_0.AddChildAtIndex(trainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_1_ItemTemplate, i);
				trainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_1_ItemTemplate.CreateWidgets();
				trainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_1_ItemTemplate.SetIds();
				trainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_1_ItemTemplate.SetAttributes();
				trainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_1_ItemTemplate.SetDataSource(dataSource);
			}
		}
	}
}
